// === aliens.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function paddleSegments() {
    let segs = [[paddle.x, paddle.x + paddle.w]];
    for (const h of paddleHoles) {
        const h0 = paddle.x + h.x - h.w / 2;
        const h1 = paddle.x + h.x + h.w / 2;
        const next = [];
        for (const [a, b] of segs) {
            if (h1 <= a || h0 >= b) {
                next.push([a, b]);
                continue;
            }
            if (h0 > a) next.push([a, h0]);
            if (h1 < b) next.push([h1, b]);
        }
        segs = next;
    }
    return segs;
}

// Split Paddle's second half: a plain reflection of the real (input-driven) paddle around the centre of
// the screen, recomputed fresh every frame from paddle.x — so it needs no input plumbing of its own and
// is exactly as wide. Its own velocity is the negative of paddleVX, since it's a mirror image in motion
// too, not just in position.
function mirrorPaddleRect() {
    if (splitTimer <= 0) return null;
    return { x: CANVAS_W - paddle.w - paddle.x, y: paddle.y, w: paddle.w, h: paddle.h };
}

// Circle vs the solid parts of the paddle (identical to a plain paddle rectangle when it has no holes),
// and, while Split Paddle is active, its mirrored half too. Returns whichever rect it touched — carrying
// that rect's own x/w/vx so the bounce can steer off the half actually hit, not always the input paddle —
// or null.

function paddleHit(px, py, r) {
    const cy = Math.max(paddle.y, Math.min(py, paddle.y + paddle.h));
    for (const [a, b] of paddleSegments()) {
        const dx = px - Math.max(a, Math.min(px, b));
        const dy = py - cy;
        if (dx * dx + dy * dy < r * r) return { x: paddle.x, y: paddle.y, w: paddle.w, vx: paddleVX, mirror: false };
    }
    const m = mirrorPaddleRect();
    if (m) {
        const dx = px - Math.max(m.x, Math.min(px, m.x + m.w));
        const dy = py - cy;
        if (dx * dx + dy * dy < r * r) return { x: m.x, y: m.y, w: m.w, vx: -paddleVX, mirror: true };
    }
    return null;
}

function paddleOverlap(px, py, r) {
    return !!paddleHit(px, py, r);
}


function punchHole(worldX, seconds = HOLE_SECONDS) {
    const lx = Math.max(HOLE_W / 2, Math.min(paddle.w - HOLE_W / 2, worldX - paddle.x)); // hole stays inside the paddle
    const near = paddleHoles.find(h => Math.abs(h.x - lx) < HOLE_W * 0.6);
    if (near) {
        near.life = Math.max(near.life, seconds); // hitting an existing hole just refreshes it
    } else {
        paddleHoles.push({ x: lx, w: HOLE_W, life: seconds });
        const maxHoles = Math.max(1, Math.floor(paddle.w / 45)); // a narrow paddle can't lose most of its width
        while (paddleHoles.length > maxHoles) paddleHoles.shift();
    }
    spawnParticles(worldX, paddle.y + paddle.h / 2, '#ff9a3c', 14);
    addShake(4);
    haptic([25, 20, 35], true);
    tone(700, 0.18, { type: 'sawtooth', vol: 0.22, slideTo: 120, key: 'zap' });
    addPopup(paddle.x + paddle.w / 2, paddle.y - 22, 'HIT!', '#ff6b6b', { life: 0.8 });
}

// A bolt hitting the Split Paddle mirror half: same impact, but the mirror is a plain reflection, not a
// tracked entity of its own, so there's no hole to punch — it just blocks the shot.
function blockMirrorBolt(worldX) {
    spawnParticles(worldX, paddle.y + paddle.h / 2, '#ff9a3c', 14);
    addShake(4);
    haptic([25, 20, 35], true);
    tone(700, 0.18, { type: 'sawtooth', vol: 0.22, slideTo: 120, key: 'zap' });
    addPopup(worldX, paddle.y - 22, 'BLOCKED!', '#7fe9ff', { life: 0.8 });
}

// -- Aliens --

function resetAliens(graceSeconds = 8, spreadSeconds = 8) {
    aliens.length = 0;
    alienBullets.length = 0;
    alienTimer = Math.round(60 * (graceSeconds + Math.random() * spreadSeconds));
}


function alienMax(l = level) {
    return Math.min(1 + Math.floor((l - 1) / 5), 3);
}

// Frames between arrivals: shorter on later levels, never under ~8s, randomised +-30%

function alienInterval() {
    const base = Math.max(8, 20 - level * 0.9);
    return Math.round(60 * base * (0.7 + Math.random() * 0.6));
}


function alienFireEvery() {
    return Math.round(60 * Math.max(0.9, 2.2 - level * 0.1) * (0.75 + Math.random() * 0.5));
}


function alienBoltSpeed() {
    return Math.min(3.6 + level * 0.25, 6.5);
}

// Where a bolt fired now would be aimed: the paddle centre, led a little in the direction it's moving

function alienAimX() {
    return Math.max(0, Math.min(CANVAS_W, paddle.x + paddle.w / 2 + paddleVX * 10));
}


function spawnAlien() {
    const fromLeft = Math.random() < 0.5;
    const speed = Math.min(1.1 + level * 0.08, 2.4);
    const hp = Math.min(1 + Math.floor(level / 4), 3);
    aliens.push({
        x: fromLeft ? -ALIEN_W : CANVAS_W + ALIEN_W,
        y: 0,
        baseY: 250 + Math.random() * 110,
        w: ALIEN_W,
        h: ALIEN_H,
        vx: (fromLeft ? 1 : -1) * speed,
        hp: hp,
        maxHp: hp,
        entered: false,
        leaving: false,
        life: Math.round(60 * (10 + Math.random() * 5)),
        fireIn: Math.round(70 + Math.random() * 50),
        flash: 0,
        cool: 0,
        t: Math.floor(Math.random() * 100)
    });
    if (!boss) addPopup(CANVAS_W / 2, 46, 'ALIEN INCOMING!', ALIEN_COLOR, { size: 24, life: 1.4, rise: 0.2, pop: true }); // (a boss's summons need no banner over its health bar)
    tone(330, 0.15, { type: 'triangle', vol: 0.2, key: 'warn' });
    tone(440, 0.2, { type: 'triangle', vol: 0.2, delay: 0.15, force: true });
    haptic([15, 40, 15], true);
}


function fireAlien(a) {
    const speed = alienBoltSpeed();
    const y0 = a.y + a.h / 2;
    const travel = Math.max(1, (paddle.y - y0) / speed);
    alienBullets.push({ x: a.x, y: y0, vx: (alienAimX() - a.x) / travel, vy: speed });
    tone(1200, 0.1, { type: 'square', vol: 0.12, slideTo: 420, key: 'laser' });
}


function killAlien(i, a) {
    aliens.splice(i, 1);
    runStats.aliens++;
    const points = 250 * (doubleTimer > 0 ? 2 : 1);
    addScore(points);
    spawnParticles(a.x, a.y, ALIEN_COLOR, 22);
    spawnParticles(a.x, a.y, '#ffffff', 8);
    addBlast(a.x, a.y);
    addPopup(a.x, a.y - 12, 'ALIEN DOWN! +' + points, ALIEN_COLOR, { size: 20, life: 1.3, pop: true });
    spawnPowerup(a.x, a.y + 14); // guaranteed drop
    addShake(6);
    haptic([30, 30, 50], true);
    tone(520, 0.3, { type: 'sawtooth', vol: 0.25, slideTo: 60, key: 'alienDown' });
    alienKillBonus();
}

// A downed alien has a 50% chance of something fun happening right on the spot: either a warp rift opens,
// or one of the timed weird events (upside down, reversed controls, full flip, time warp) kicks off
// immediately, picked at random between whichever of the two are currently possible. The chaos event is a
// bonus and does not spend the level's own chaos budget (see the matching chaosEventsLeft++ below).

function alienKillBonus() {
    if (Math.random() >= WARP_ON_ALIEN_KILL_CHANCE) return;
    const canWarp = canSpawnWarp();
    const canChaos = chaosPool().length > 0 && !chaos.type && chaos.warn === 0;
    if (canWarp && (!canChaos || Math.random() < 0.5)) {
        spawnWarpRift();
        warpTimer = warpInterval();
    } else if (canChaos) {
        chaosEventsLeft++;
        startChaosWarning();
    }
}


function updateAliens() {
    // Holes repair themselves
    for (let i = paddleHoles.length - 1; i >= 0; i--) {
        paddleHoles[i].life -= 1 / 60;
        if (paddleHoles[i].life <= 0) paddleHoles.splice(i, 1);
    }

    // Random arrivals (not when the level is nearly cleared)
    if (plan.aliens && aliens.length < plan.aliens.max && bricksLeft > 3 && --alienTimer <= 0) {
        spawnAlien();
        alienTimer = alienInterval();
    }

    for (let i = aliens.length - 1; i >= 0; i--) {
        const a = aliens[i];
        a.t++;
        a.x += a.vx * timeScale;
        a.y = a.baseY + Math.sin(a.t / 25) * 12;
        if (a.flash > 0) a.flash--;
        if (a.cool > 0) a.cool--;
        if (!a.entered) {
            if (a.x > a.w / 2 && a.x < CANVAS_W - a.w / 2) a.entered = true;
        } else if (!a.leaving) {
            if (a.x < a.w / 2 || a.x > CANVAS_W - a.w / 2) {
                a.x = Math.max(a.w / 2, Math.min(CANVAS_W - a.w / 2, a.x));
                a.vx *= -1;
            }
            if (--a.life <= 0) a.leaving = true;
            if (--a.fireIn <= 0) {
                fireAlien(a);
                a.fireIn = alienFireEvery();
            }
        } else if (a.x < -a.w || a.x > CANVAS_W + a.w) {
            aliens.splice(i, 1); // flew off the far side
        }
    }

    for (let i = alienBullets.length - 1; i >= 0; i--) {
        const b = alienBullets[i];
        b.x += b.vx * timeScale;
        b.y += b.vy * timeScale;
        // A ball destroys bolts
        if (balls.some(ball => Math.hypot(ball.x - b.x, ball.y - b.y) < ball.r + 4)) {
            spawnParticles(b.x, b.y, ALIEN_COLOR, 6);
            beep(900, 'shot');
            alienBullets.splice(i, 1);
            continue;
        }
        // Any bolt crossing a supply crate breaks it (the boss shooting down its own supplies)
        const hitCrate = crates.find(cr => cr.alive && b.x >= cr.x - 3 && b.x <= cr.x + cr.w + 3 && b.y >= cr.y - 3 && b.y <= cr.y + cr.h + 3);
        if (hitCrate) {
            breakCrate(hitCrate);
            spawnParticles(b.x, b.y, ALIEN_COLOR, 6);
            alienBullets.splice(i, 1);
            continue;
        }
        // Hits solid paddle (a bolt over an existing hole just passes through)
        const atPaddleHeight = b.y + 6 >= paddle.y && b.y - 6 <= paddle.y + paddle.h;
        if (atPaddleHeight && paddleSegments().some(([s0, s1]) => b.x >= s0 && b.x <= s1)) {
            punchHole(b.x, b.hole || HOLE_SECONDS);
            alienBullets.splice(i, 1);
            continue;
        }
        const m = mirrorPaddleRect();
        if (atPaddleHeight && m && b.x >= m.x && b.x <= m.x + m.w) {
            blockMirrorBolt(b.x);
            alienBullets.splice(i, 1);
            continue;
        }
        if (b.y > CANVAS_H + 10 || b.x < -10 || b.x > CANVAS_W + 10) alienBullets.splice(i, 1);
    }
}

// Ball vs aliens: damage, bounce (a fire ball pierces) and a short cooldown so one contact = one hit

function alienBallCollision(b) {
    for (let i = aliens.length - 1; i >= 0; i--) {
        const a = aliens[i];
        if (a.cool > 0) continue;
        const left = a.x - a.w / 2;
        const top = a.y - a.h / 2;
        const cx = Math.max(left, Math.min(b.x, left + a.w));
        const cy = Math.max(top, Math.min(b.y, top + a.h));
        const dx = b.x - cx;
        const dy = b.y - cy;
        if (dx * dx + dy * dy >= b.r * b.r) continue;

        a.cool = 10;
        a.hp--;
        a.flash = 6;
        if (fireTimer <= 0) {
            if (Math.abs(dx) > Math.abs(dy)) {
                const dir = dx > 0 ? 1 : -1;
                b.vx = dir * Math.abs(b.vx);
                b.x = dir > 0 ? left + a.w + b.r : left - b.r;
            } else {
                const dir = dy >= 0 ? 1 : -1;
                b.vy = dir * Math.abs(b.vy);
                b.y = dir > 0 ? top + a.h + b.r : top - b.r;
            }
        }
        if (a.hp <= 0) {
            killAlien(i, a);
        } else {
            clink();
            addShake(2);
            haptic(15);
            spawnParticles(b.x, b.y, ALIEN_COLOR, 6);
        }
    }
}

// -- Drawing --
// Each animation frame x colour is drawn once into a small sprite (the sprite is 60+ cell fills)

function drawAliens() {
    for (const a of aliens) {
        const charging = a.entered && !a.leaving && a.fireIn <= 30;
        const cell = 3;
        const sx = a.x - (11 * cell) / 2;
        const sy = a.y - (8 * cell) / 2;

        if (charging) {
            // Aim line to where the bolt would go right now: time to dodge
            ctx.save();
            ctx.strokeStyle = 'rgba(255, 90, 90, 0.4)';
            ctx.lineWidth = 1.5;
            ctx.setLineDash([4, 6]);
            ctx.beginPath();
            ctx.moveTo(a.x, a.y + a.h / 2);
            ctx.lineTo(alienAimX(), paddle.y);
            ctx.stroke();
            ctx.restore();
        }

        ctx.save();
        ctx.globalAlpha = 0.2; // glow underlay
        ctx.fillStyle = charging ? '#ff5a5a' : ALIEN_COLOR;
        ctx.beginPath();
        ctx.ellipse(a.x, a.y, 26, 18, 0, 0, Math.PI * 2);
        ctx.fill();
        ctx.globalAlpha = 1;

        const color = a.flash > 0 ? '#ffffff' : (charging && Math.floor(a.t / 3) % 2 === 0 ? '#ff5a5a' : ALIEN_COLOR);
        ctx.drawImage(alienSprite(Math.floor(a.t / 14) % 2, color), sx, sy);
        // Remaining hit points for tougher aliens
        if (a.maxHp > 1) {
            for (let h = 0; h < a.maxHp; h++) {
                ctx.fillStyle = h < a.hp ? '#ffffff' : 'rgba(255, 255, 255, 0.25)';
                ctx.fillRect(a.x - (a.maxHp * 6) / 2 + h * 6 + 1, sy - 7, 4, 3);
            }
        }
        ctx.restore();
    }
}


function drawAlienBullets() {
    if (!alienBullets.length) return;
    ctx.save();
    for (const b of alienBullets) {
        ctx.globalAlpha = 0.3; // halo
        ctx.fillStyle = ALIEN_COLOR;
        ctx.fillRect(b.x - 5, b.y - 9, 10, 18);
        ctx.globalAlpha = 1;
        ctx.fillStyle = '#eafff0';
        ctx.fillRect(b.x - 1.5, b.y - 7, 3, 14);
    }
    ctx.restore();
}

