// === audio.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function toggleMute() {
    isMuted = !isMuted;
    const btn = document.getElementById('mute-btn');
    if (btn) {
        btn.classList.toggle('active', isMuted);
        btn.title = isMuted ? 'Unmute sound and vibration (M)' : 'Mute sound and vibration (M)';
    }
}

// Create/resume the AudioContext. Browsers (notably Chrome on Android) start it suspended until
// a user gesture, so this is also called from input handlers.

function ensureAudio() {
    try {
        if (!audioCtx) audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        if (audioCtx.state === 'suspended') audioCtx.resume();
    } catch (e) {
        return null; // Audio not available; ignore
    }
    return audioCtx.state === 'running' ? audioCtx : null;
}

// One-shot tone: optional pitch slide and start delay (seconds).
// `key` throttles repeats of the same sound; `force` (jingles, fanfares) bypasses throttle and cap.

function tone(freq, dur, { type = 'square', vol = 0.15, slideTo = null, delay = 0, key = null, force = false } = {}) {
    if (isMuted || document.hidden) return;
    const ac = ensureAudio();
    if (!ac) return;
    if (!force) {
        const now = performance.now();
        if (activeVoices >= MAX_VOICES) return;
        if (key !== null) {
            if (now - (lastPlayedAt[key] || 0) < MIN_GAP_MS) return;
            lastPlayedAt[key] = now;
        }
    }
    try {
        const t0 = ac.currentTime + delay;
        const osc = ac.createOscillator();
        const gain = ac.createGain();
        osc.type = type;
        osc.frequency.setValueAtTime(freq, t0);
        if (slideTo) osc.frequency.exponentialRampToValueAtTime(slideTo, t0 + dur);
        gain.gain.setValueAtTime(vol, t0);
        gain.gain.exponentialRampToValueAtTime(0.001, t0 + dur);
        osc.connect(gain);
        gain.connect(ac.destination);
        activeVoices++;
        osc.onended = () => {
            activeVoices--;
            osc.disconnect();
            gain.disconnect();
        };
        osc.start(t0);
        osc.stop(t0 + dur);
    } catch (e) {
        // Audio not available; ignore
    }
}

// --- Haptics (navigator.vibrate: Chrome on Android; a no-op on iOS and desktop) ---
// Follows the mute button, and is skipped for reduced-motion users. Light hits are throttled so a
// burst of collisions doesn't buzz constantly (each vibrate() call replaces the previous one);
// `strong` events always go through.

function haptic(pattern, strong = false) {
    if (isMuted || reduceMotion || document.hidden) return;
    // Chrome ignores (and logs a warning for) vibrate() before the user has interacted with the page
    if (navigator.userActivation && !navigator.userActivation.hasBeenActive) return;
    const now = performance.now();
    if (!strong && now - lastHapticAt < MIN_HAPTIC_GAP_MS) return;
    lastHapticAt = now;
    if (navigator.vibrate) {
        try {
            navigator.vibrate(pattern);
        } catch (e) {
            // Vibration not available; ignore
        }
    } else {
        iosHapticTick(); // iOS Safari has no navigator.vibrate at all; see iosHapticTick()
    }
}

// iOS Safari has never implemented navigator.vibrate(). Toggling a native <input type="checkbox" switch>
// (the iOS 17.4+ "switch" control, https://www.npmjs.com/package/ios-vibrator-pro-max) fires the OS's
// switch-flip haptic tick, the closest thing to vibrate() iOS exposes to the web. It is one short, fixed
// tap only (no custom patterns or durations) and is silently a no-op on every other browser.

function ensureIosHapticEl() {
    if (iosHapticEl || typeof document === 'undefined' || !document.body) return iosHapticEl;
    const label = document.createElement('label');
    label.style.cssText = 'position:fixed; left:-9999px; top:-9999px; width:1px; height:1px; overflow:hidden;';
    const input = document.createElement('input');
    input.type = 'checkbox';
    input.setAttribute('switch', '');
    input.tabIndex = -1;
    input.setAttribute('aria-hidden', 'true');
    label.appendChild(input);
    document.body.appendChild(label);
    iosHapticEl = input;
    return iosHapticEl;
}

function iosHapticTick() {
    try {
        const el = ensureIosHapticEl();
        if (el) el.click();
    } catch (e) {
        // Not supported on this browser; ignore
    }
}


function beep(freq = 440, key = 'beep') {
    tone(freq, 0.08, { type: 'square', vol: 0.15, key: key });
}

// Short metallic clink when hitting steel brick

function clink() {
    tone(1100, 0.07, { type: 'triangle', vol: 0.2, slideTo: 600, key: 'clink' });
}

// Short explosion boom (low, thuddy)

function boom() {
    tone(90, 0.25, { type: 'sawtooth', vol: 0.3, slideTo: 30, key: 'boom' });
}

// Win jingle: cheerful rising arpeggio (C5, E5, G5, C6)

function playWinJingle() {
    [523.25, 659.25, 783.99, 1046.50].forEach((freq, idx) => {
        tone(freq, 0.25, { type: 'sine', vol: 0.2, delay: idx * 0.1, force: true });
    });
}

// Lose jingle: descending sad tones (G4, F4, Eb4, C4)

function playLoseJingle() {
    [392.00, 349.23, 311.13, 261.63].forEach((freq, idx) => {
        tone(freq, 0.3, { type: 'sawtooth', vol: 0.18, delay: idx * 0.15, force: true });
    });
}

// Particles are capped: they're pure decoration and a few hundred fillRects per frame add up
