// === boss.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function bossChainMult(n) {
    return n >= 4 ? 3 : n >= 2 ? 2 : 1;
}


function bossPhase() {
    const ratio = boss.hp / boss.maxHp;
    return ratio > 0.66 ? 1 : ratio > 0.33 ? 2 : 3;
}


// Four boss types share this arena slot: the mothership (below), the snake (snakeBoss.js), the rival
// (pongBoss.js) and the asteroid field (asteroidsBoss.js). Each debuts in BOSS_ORDER, one per encounter;
// after that a boss level picks one at random, seeded per level like everything else here, so ?level=N
// always gives the same boss.
function spawnBoss() {
    const n = Math.floor(level / UNLOCK.boss);
    const kind = n <= BOSS_ORDER.length
        ? BOSS_ORDER[n - 1]
        : BOSS_ORDER[Math.floor(seededRandom(level * 11113 + 5)() * BOSS_ORDER.length)];
    if (kind === 'snake') {
        spawnSnakeBoss();
        return;
    }
    if (kind === 'pong') {
        spawnPongBoss(n);
        return;
    }
    if (kind === 'asteroids') {
        spawnAsteroidsBoss(n);
        return;
    }
    const hp = 6 + 8 * n; // 14, 22, 30, 38 ... (a chain multiplies damage, so later bosses need to grow faster)
    boss = {
        kind: 'mothership', n, hp, maxHp: hp, x: CANVAS_W / 2, y: -70, homeY: 130, t: 0, mt: 0, intro: 100,
        atk: null, atkIn: 150, lastAtk: null, minionIn: 60 * 12, flash: 0, cool: 0,
        dying: 0, beamFx: 0, beamX: 0, lastPhase: 1, chain: 0, chainT: 0, cheatRolled: false
    };
    spawnCrates();
}

// Hull and dome as two rectangles (x0, y0, x1, y1)

function bossRects() {
    if (boss.kind === 'snake') return snakeRects(); // used for guided-ball targeting; see snakeBoss.js
    if (boss.kind === 'asteroids') return asteroidsRects();
    if (boss.kind === 'pong') { // its one-way bricks: the guided ball helps clear a way through
        return boss.wall.filter(pongBrickSolid).map(w => [w.x, w.y, w.x + BRICK_W, w.y + BRICK_H]);
    }
    const B = boss;
    return [[B.x - 108, B.y - 17, B.x + 108, B.y + 43], [B.x - 46, B.y - 43, B.x + 46, B.y - 17]];
}

// The weak point: a fixed hatch on the belly. A ball touching the hull from below is ~21px under its centre.
// (The snake has no equivalent critical zone — hitting nearer its head already does more, by construction.)

function bossCore() {
    return { x: boss.x, y: boss.y + 30 };
}


function inBossHatch(x, y) {
    if (boss.kind !== 'mothership') return false;
    const core = bossCore();
    return Math.hypot(x - core.x, y - core.y) < 34;
}


function bossInterval() {
    // Frames between attacks: 260 / 240 / 220 (phases 1-3) for the first boss, noticeably faster for later ones
    return Math.max(110, 280 - 20 * boss.n - (bossPhase() - 1) * 20);
}


function bossBoltSpeed() {
    return Math.min(3 + 0.2 * boss.n + 0.3 * bossPhase(), 6);
}


function fireBossFan() {
    const B = boss;
    const count = bossPhase() >= 2 ? 4 : 3;
    const speed = bossBoltSpeed();
    const y0 = B.y + 40;
    const base = Math.atan2(paddle.x + paddle.w / 2 - B.x, paddle.y - y0);
    for (let i = 0; i < count; i++) {
        const a = base + (i - (count - 1) / 2) * 0.28;
        alienBullets.push({ x: B.x, y: y0, vx: Math.sin(a) * speed, vy: Math.cos(a) * speed, hole: BOSS_HOLE_SECONDS });
    }
    tone(900, 0.14, { type: 'square', vol: 0.15, slideTo: 300, key: 'laser' });
}


function startBossAttack() {
    const B = boss;
    const phase = bossPhase();
    const pool = ['fan'];
    if (phase >= 2) pool.push('rain', 'fan');
    if (phase >= 3) pool.push('beam', 'rain');
    let kind = pool[Math.floor(Math.random() * pool.length)];
    if (kind === B.lastAtk) kind = pool[Math.floor(Math.random() * pool.length)]; // avoid the same attack twice in a row
    const atk = { kind, t: 0, dur: kind === 'fan' ? 40 : kind === 'rain' ? 46 : 90 };
    if (kind === 'rain') {
        atk.cols = [];
        const count = Math.min(3 + B.n, 7);
        for (let tries = 0; atk.cols.length < count && tries < 60; tries++) {
            const x = 30 + Math.random() * (CANVAS_W - 60);
            if (atk.cols.every(c => Math.abs(c - x) > 60)) atk.cols.push(x);
        }
    }
    if (kind === 'beam') atk.x = paddle.x + paddle.w / 2;
    B.atk = atk;
    tone(220, 0.25, { type: 'triangle', vol: 0.2, slideTo: 330, key: 'bossWarn' });
}


function endBossAttack() {
    const B = boss;
    B.lastAtk = B.atk.kind;
    B.atk = null;
    B.atkIn = Math.round(bossInterval() * (0.8 + Math.random() * 0.4));
}


function updateBossAttacks() {
    const B = boss;
    if (!B.atk) {
        if (--B.atkIn <= 0) startBossAttack();
    } else {
        const a = B.atk;
        a.t++;
        if (a.kind === 'fan') {
            if (a.t === a.dur) {
                fireBossFan();
                endBossAttack();
            }
        } else if (a.kind === 'rain') {
            if (a.t === a.dur) {
                const speed = Math.min(3.6 + 0.25 * B.n, 6);
                for (const x of a.cols) alienBullets.push({ x, y: 70, vx: 0, vy: speed, hole: BOSS_HOLE_SECONDS });
                tone(700, 0.2, { type: 'square', vol: 0.14, slideTo: 250, key: 'laser' });
                endBossAttack();
            }
        } else if (a.kind === 'beam') {
            if (a.t < a.dur - 30) a.x = paddle.x + paddle.w / 2; // tracks you, then locks on (30 frames to get out of the way)
            if (a.t === a.dur) {
                B.beamFx = 18;
                B.beamX = a.x;
                addShake(7);
                tone(150, 0.4, { type: 'sawtooth', vol: 0.3, slideTo: 60, key: 'beam', force: true });
                if (paddle.x < a.x + BEAM_HALF && paddle.x + paddle.w > a.x - BEAM_HALF) {
                    reverseFrames = reverseTotal = 180;
                    refreshInputMapping();
                    addPopup(paddle.x + paddle.w / 2, paddle.y - 40, 'MIND FLIP!', '#ff4dd8', { size: 24, life: 1.4, pop: true });
                    haptic([40, 30, 40, 30, 80], true);
                }
            }
            if (a.t >= a.dur + 18) endBossAttack();
        }
    }
    if (B.phase >= 2 || bossPhase() >= 2) {
        if (--B.minionIn <= 0) {
            if (aliens.length < 1) spawnAlien();
            B.minionIn = 60 * 18;
        }
    }
}


function updateBoss() {
    const B = boss;
    if (!B) return;
    if (B.kind === 'snake') {
        updateSnakeBoss();
        return;
    }
    if (B.kind === 'pong') {
        updatePongBoss();
        return;
    }
    if (B.kind === 'asteroids') {
        updateAsteroidsBoss();
        return;
    }
    B.t++;
    if (B.dying > 0) {
        updateBossDeath();
        return;
    }
    if (B.intro > 0) {
        if (B.t === 1) {
            addPopup(CANVAS_W / 2, 215, 'BOSS INCOMING!', '#ff4d6a', { size: 30, life: 1.8, rise: 0.3, pop: true });
            tone(300, 0.5, { type: 'sawtooth', vol: 0.25, slideTo: 200, key: 'siren', force: true });
            haptic([60, 40, 60], true);
            shield = Math.min(shield + 1, SHIELD_MAX); // a free miss to start the fight, on top of any already banked
            addPopup(CANVAS_W / 2, CANVAS_H - 60, 'Free shield!', '#33ddff', { size: 18, life: 1.8, rise: 0.2 }); // by the shield line, clear of the intro card
        }
        B.intro--;
        const k = 1 - B.intro / 100;
        B.y = -70 + (B.homeY + 70) * (1 - (1 - k) * (1 - k)); // ease out
        return;
    }
    const phase = bossPhase();
    const rate = 0.011 + 0.0015 * B.n + 0.002 * (phase - 1);
    B.mt += timeScale; // boss motion follows Time Warp; its attack timers do not
    B.x = CANVAS_W / 2 + Math.sin(B.mt * rate) * (CANVAS_W / 2 - 108 - 14);
    B.y = B.homeY + Math.sin(B.mt / 40) * 8;
    if (B.flash > 0) B.flash--;
    if (B.cool > 0) B.cool--;
    if (B.beamFx > 0) B.beamFx--;
    if (B.chainT > 0 && --B.chainT === 0) B.chain = 0; // the chain ran out
    updateBossAttacks();
}


function checkBossPhase() {
    const B = boss;
    const p = bossPhase();
    if (p === B.lastPhase) return;
    B.lastPhase = p;
    B.atk = null;
    B.atkIn = 110;
    alienBullets.length = 0; // a breather between phases
    addPopup(CANVAS_W / 2, 215, p === 3 ? 'ENRAGED!' : 'PHASE ' + p, '#ff8a2a', { size: 30, life: 1.6, rise: 0.3, pop: true });
    addShake(9);
    haptic([50, 30, 50], true);
    tone(180, 0.5, { type: 'sawtooth', vol: 0.28, slideTo: 90, key: 'phase', force: true });
    // Entering the last stretch: the boss's own shot at a cheat-code capsule (see maybeDropBossCheatCapsule)
    if (p === 3) maybeDropBossCheatCapsule(B.x, B.y + 20);
}


function bossBallCollision(b) {
    const B = boss;
    if (!B) return;
    if (B.kind === 'snake') {
        snakeBallCollision(b);
        return;
    }
    if (B.kind === 'pong') {
        pongBallCollision(b);
        return;
    }
    if (B.kind === 'asteroids') {
        asteroidsBallCollision(b);
        return;
    }
    if (B.intro > 0 || B.dying > 0 || B.cool > 0) return;
    for (const [x0, y0, x1, y1] of bossRects()) {
        const cx = Math.max(x0, Math.min(b.x, x1));
        const cy = Math.max(y0, Math.min(b.y, y1));
        const dx = b.x - cx;
        const dy = b.y - cy;
        if (dx * dx + dy * dy >= b.r * b.r) continue;

        B.cool = 8; // one contact = one hit
        B.flash = 6;
        const crit = inBossHatch(b.x, b.y);
        const prevMult = B.chainT > 0 ? bossChainMult(B.chain) : 1;
        B.chain = B.chainT > 0 ? B.chain + 1 : 1; // hitting again in time extends the chain
        B.chainT = BOSS_CHAIN_FRAMES;
        const chainMult = bossChainMult(B.chain);
        let dmg = (fireTimer > 0 ? 3 : 1) * (crit ? 3 : 1) * chainMult;
        if (explosiveReady) {
            explosiveReady = false;
            dmg += 5;
            addBlast(b.x, b.y);
            boom();
            addShake(10);
        }
        B.hp -= dmg;
        addScore(15 * dmg * (doubleTimer > 0 ? 2 : 1));
        addPopup(b.x, b.y - 12, (crit ? 'CRITICAL! -' : '-') + dmg + (chainMult > 1 ? '  \u00d7' + chainMult : ''), crit ? '#FFD700' : '#ffffff',
            { size: crit ? 22 : 16, pop: crit, life: 0.9 });
        if (chainMult > prevMult) { // the chain just stepped up
            if (chainMult >= 3) noteMoment(55, 'BOSS CHAIN x3!');
            addPopup(B.x, B.y - 62, 'CHAIN \u00d7' + chainMult + '!', '#ffb300', { size: 24, life: 1.1, rise: 0.5, pop: true });
            tone(660 + 220 * chainMult, 0.12, { type: 'triangle', vol: 0.25, key: 'chain' });
            addShake(4);
            haptic([15, 20, 25], true);
        }
        spawnParticles(b.x, b.y, crit ? '#ffd23f' : '#c9a0ff', crit ? 14 : 6);
        if (crit) {
            noteMoment(40, 'CRITICAL HIT!');
            tone(880, 0.1, { type: 'triangle', vol: 0.25, key: 'crit' });
            tone(1320, 0.14, { type: 'triangle', vol: 0.25, delay: 0.06, force: true });
        } else {
            clink();
        }
        sfxMothershipHurt(crit);
        addShake(crit ? 6 : 3);
        haptic(crit ? [20, 20, 40] : 20, crit);
        if (fireTimer <= 0) { // a fire ball goes straight through; anything else bounces off
            if (Math.abs(dx) > Math.abs(dy)) {
                const dir = dx >= 0 ? 1 : -1;
                b.vx = dir * Math.abs(b.vx);
                b.x = dir > 0 ? x1 + b.r : x0 - b.r;
            } else {
                const dir = dy >= 0 ? 1 : -1;
                b.vy = dir * Math.abs(b.vy);
                b.y = dir > 0 ? y1 + b.r : y0 - b.r;
            }
        }
        if (B.hp <= 0) killBoss();
        else checkBossPhase();
        return;
    }
}

// The newer bosses' shared entrance: a call-out, the siren, and the same free shield every boss hands out
// at the start of its fight (see updateBoss / updateSnakeBoss for the older two's own versions)
function announceBoss(text, color, freeShield = true) {
    addPopup(CANVAS_W / 2, 250, text, color, { size: 28, life: 1.8, rise: 0.3, pop: true });
    tone(260, 0.4, { type: 'sawtooth', vol: 0.22, slideTo: 500, key: 'siren', force: true });
    haptic([50, 30, 50], true);
    if (!freeShield) return;
    shield = Math.min(shield + 1, SHIELD_MAX);
    addPopup(CANVAS_W / 2, CANVAS_H - 60, 'Free shield!', '#33ddff', { size: 18, life: 1.8, rise: 0.2 });
}

// A plain health bar with a label, for the bosses without extras (phase notches, chain meter) on theirs
function drawSimpleBossBar(label, ratio) {
    if (!boss || boss.dying > 0) return;
    const w = 460, x = (CANVAS_W - w) / 2, y = 64, h = 12;
    ctx.save();
    ctx.fillStyle = 'rgba(0, 0, 0, 0.65)';
    ctx.fillRect(x - 3, y - 3, w + 6, h + 6);
    ctx.fillStyle = ratio > 0.66 ? '#4de08c' : ratio > 0.33 ? '#ff9a2e' : '#ff4d4d';
    ctx.fillRect(x, y, w * Math.max(0, ratio), h);
    ctx.font = termFont(19);
    ctx.textAlign = 'center';
    ctx.fillStyle = '#ffffff';
    ctx.fillText(label, CANVAS_W / 2, y - 6);
    ctx.restore();
}

// A lost ball gives the boss a breather too (it never heals)

function bossBreather() {
    if (!boss || boss.dying > 0) return;
    if (boss.kind === 'snake') {
        snakeBreather();
        return;
    }
    if (boss.kind === 'pong') {
        pongBreather();
        return;
    }
    if (boss.kind === 'asteroids') return; // rocks don't regroup; nothing to reset
    boss.atk = null;
    boss.atkIn = 150;
    boss.beamFx = 0;
    boss.chain = 0;
    boss.chainT = 0;
}


function killBoss() {
    const B = boss;
    B.dying = 150;
    B.atk = null;
    B.beamFx = 0;
    alienBullets.length = 0;
    for (const a of aliens) { // its summoned aliens go down with the ship
        spawnParticles(a.x, a.y, ALIEN_COLOR, 14);
        addBlast(a.x, a.y);
    }
    aliens.length = 0;
    addShake(12);
    haptic([60, 40, 60, 40, 120], true);
    tone(400, 0.6, { type: 'sawtooth', vol: 0.3, slideTo: 40, key: 'bossDie', force: true });
    noteMoment(100, 'MOTHERSHIP DESTROYED!', 30); // mid-explosion, not the instant of the hit
    addPopup(CANVAS_W / 2, 250, 'MOTHERSHIP DESTROYED!', '#ffd23f', { size: 28, life: 2.2, rise: 0.2, pop: true });
}


function updateBossDeath() {
    const B = boss;
    B.dying--;
    if (B.dying % 6 === 0) {
        const ex = B.x + (Math.random() - 0.5) * 190;
        const ey = B.y + (Math.random() - 0.5) * 70;
        addBlast(ex, ey);
        spawnParticles(ex, ey, Math.random() < 0.5 ? '#ff9a1f' : '#ffffff', 10);
        addShake(5);
        haptic(15);
        beep(200 + Math.random() * 300, 'bossBoom');
    }
    if (B.dying <= 0) finishBoss();
}


function finishBoss() {
    const points = 1500 * boss.n * (doubleTimer > 0 ? 2 : 1);
    addScore(points);
    runStats.bosses++;
    lives = Math.min(lives + 1, 5);
    boss = null;
    addPopup(CANVAS_W / 2, 210, 'BOSS DEFEATED! +' + points, '#ffd23f', { size: 26, life: 2.4, rise: 0.2, pop: true });
    addPopup(CANVAS_W / 2, 245, '+1 LIFE', '#33cc33', { size: 20, life: 2.4, rise: 0.2 });
    completeLevel();
}

// --- Boss supply crates ---
// A few gold crates hang in the arena during a boss fight, each holding a guaranteed powerup (its icon is on
// the face, so you can choose). The ball breaks them, and so does any bolt that crosses one (the boss's or a
// summoned alien's): either way the powerup drops for you to catch. Every fight has at least one damage
// powerup (fire / explosive / guided) and one defensive one (wide / shield / sticky).

function drawBossTelegraph(B) {
    const a = B.atk;
    const y0 = B.y + 40;
    ctx.save();
    if (a.kind === 'fan') {
        const count = bossPhase() >= 2 ? 4 : 3;
        const base = Math.atan2(paddle.x + paddle.w / 2 - B.x, paddle.y - y0);
        ctx.strokeStyle = 'rgba(255, 90, 90, 0.35)';
        ctx.lineWidth = 1.5;
        ctx.setLineDash([4, 6]);
        ctx.beginPath();
        for (let i = 0; i < count; i++) {
            const ang = base + (i - (count - 1) / 2) * 0.28;
            ctx.moveTo(B.x, y0);
            ctx.lineTo(B.x + Math.sin(ang) * (paddle.y - y0) / Math.cos(ang), paddle.y);
        }
        ctx.stroke();
    } else if (a.kind === 'rain') {
        ctx.fillStyle = 'rgba(255, 70, 70, ' + (0.1 + 0.08 * Math.sin(performance.now() / 60)) + ')';
        for (const x of a.cols) ctx.fillRect(x - 5, 0, 10, paddle.y);
    } else if (a.kind === 'beam' && B.beamFx <= 0) {
        ctx.strokeStyle = 'rgba(255, 77, 216, ' + (a.t > a.dur - 30 ? 0.8 : 0.4) + ')'; // brighter once it has locked on
        ctx.lineWidth = 2;
        ctx.setLineDash([6, 6]);
        ctx.strokeRect(a.x - BEAM_HALF, B.y + 43, BEAM_HALF * 2, CANVAS_H - B.y - 43);
    }
    ctx.restore();
}


function drawBoss() {
    const B = boss;
    if (!B) return;
    if (B.kind === 'snake') {
        drawSnakeBoss();
        return;
    }
    if (B.kind === 'pong') {
        drawPongBoss();
        return;
    }
    if (B.kind === 'asteroids') {
        drawAsteroidsBoss();
        return;
    }
    if (B.atk) drawBossTelegraph(B);
    if (!bossSprite) bossSprite = makeSprite(240, 110, paintBossSprite);
    const jitter = B.dying > 0 ? (Math.random() - 0.5) * 8 : 0;
    const sx = B.x - 120 + jitter;
    const sy = B.y - 55 + (B.dying > 0 ? (Math.random() - 0.5) * 8 : 0);
    ctx.drawImage(bossSprite, sx, sy);

    // Blinking rim lights
    const beat = Math.floor(B.t / 8);
    for (let i = 0; i < 9; i++) {
        const th = Math.PI * (0.12 + i * 0.095);
        ctx.fillStyle = (beat + i) % 2 === 0 ? '#ffd23f' : '#ff4d6a';
        ctx.beginPath();
        ctx.arc(B.x + jitter + Math.cos(th) * 96, B.y + 13 + Math.sin(th) * 26, 3, 0, Math.PI * 2);
        ctx.fill();
    }

    // A soft pulse around the hatch draws the eye to the weak point
    const core = bossCore();
    ctx.strokeStyle = 'rgba(255, 210, 90, ' + (0.35 + 0.3 * Math.sin(B.t / 10)) + ')';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(core.x + jitter, core.y, 40 + 3 * Math.sin(B.t / 10), 0, Math.PI * 2);
    ctx.stroke();

    if (B.flash > 0) { // damage flash
        ctx.save();
        ctx.globalCompositeOperation = 'lighter';
        ctx.globalAlpha = (B.flash / 6) * 0.7;
        ctx.drawImage(bossSprite, sx, sy);
        ctx.restore();
    }

    if (B.beamFx > 0) { // the mind-flip beam itself
        ctx.save();
        ctx.globalAlpha = B.beamFx / 18;
        ctx.fillStyle = '#ff4dd8';
        ctx.fillRect(B.beamX - BEAM_HALF, B.y + 43, BEAM_HALF * 2, CANVAS_H - B.y - 43);
        ctx.fillStyle = '#ffffff';
        ctx.fillRect(B.beamX - 8, B.y + 43, 16, CANVAS_H - B.y - 43);
        ctx.restore();
    }
}


function drawBossBar() {
    const B = boss;
    if (!B || B.dying > 0) return;
    if (B.kind === 'snake') {
        drawSnakeBossBar();
        return;
    }
    if (B.kind === 'pong') {
        drawPongBossBar();
        return;
    }
    if (B.kind === 'asteroids') {
        drawAsteroidsBossBar();
        return;
    }
    const w = 460;
    const x = (CANVAS_W - w) / 2;
    const y = 64; // below the event banner, which can appear over the top of the playfield
    const h = 12;
    const phase = bossPhase();
    const roman = ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'][B.n] || B.n;
    ctx.save();
    ctx.fillStyle = 'rgba(0, 0, 0, 0.65)';
    ctx.fillRect(x - 3, y - 3, w + 6, h + 6);
    ctx.fillStyle = phase === 1 ? '#4de08c' : phase === 2 ? '#ff9a2e' : '#ff4d4d';
    ctx.fillRect(x, y, w * Math.max(0, B.hp / B.maxHp), h);
    ctx.fillStyle = 'rgba(255, 255, 255, 0.5)'; // phase notches
    ctx.fillRect(x + w * 0.33 - 1, y, 2, h);
    ctx.fillRect(x + w * 0.66 - 1, y, 2, h);
    ctx.font = termFont(19);
    ctx.textAlign = 'center';
    ctx.fillStyle = '#ffffff';
    ctx.fillText('MOTHERSHIP ' + roman + '   ' + Math.max(0, B.hp) + ' / ' + B.maxHp, CANVAS_W / 2, y - 6);
    if (B.chainT > 0) {
        const mult = bossChainMult(B.chain);
        const next = bossChainMult(B.chain + 1);
        const pw = 220;
        const ph = 16;
        const px = (CANVAS_W - pw) / 2;
        const py = y + h + 9;
        ctx.fillStyle = 'rgba(0, 0, 0, 0.65)';
        ctx.fillRect(px - 3, py - 3, pw + 6, ph + 6);
        ctx.fillStyle = '#ffb300';
        ctx.fillRect(px, py, pw * (B.chainT / BOSS_CHAIN_FRAMES), ph);
        ctx.fillStyle = '#2a1c00';
        ctx.font = termFont(17);
        ctx.textBaseline = 'middle';
        ctx.fillText((mult > 1 ? 'CHAIN \u00d7' + mult : 'HIT IT AGAIN!') + (next > mult ? '  \u2192 next \u00d7' + next : '  MAX'), CANVAS_W / 2, py + ph / 2 + 1);
    }
    ctx.restore();
}

// --- Warp rifts ---
// A rare, random shortcut: a shimmering portal appears somewhere in the open play area, gives a few
// seconds' warning, then sits there for a while, pulling the ball in like gravity once it's within range.
// Getting sucked in jumps you forward 1-5 levels (randomly, never more), so a run stuck on a hard level
// always has an escape hatch. It skips boss intros/deaths so it can't interrupt those, and killing an
// alien has a 50% chance of opening one on the spot, as a bonus for the fight.
