// === chaos.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function controlsReversed() {
    return chaos.type === 'reverse' || reverseFrames > 0;
}

function viewMirrored() {
    return chaos.type === 'fullFlip';
}
// Left/right in what you touch vs canvas coordinates: swapped when the view is mirrored (so touch follows
// the screen) and swapped again when controls are reversed

function mapMirror() {
    return viewMirrored() !== controlsReversed();
}


function chaosPool() {
    return Object.keys(CHAOS).filter(k => level >= CHAOS[k].unlock && !(reduceMotion && CHAOS[k].visual));
}


function scheduleChaos(minSeconds, spreadSeconds) {
    chaosTimer = Math.round(60 * (minSeconds + Math.random() * spreadSeconds));
}


function applyView() {
    if (!canvas) return;
    canvas.style.transform = chaos.type === 'upsideDown' ? 'scaleY(-1)' : chaos.type === 'fullFlip' ? 'rotate(180deg)' : '';
}

// A drag in progress must not jump when the mapping flips underneath it

function refreshInputMapping() {
    if (dragPointerId === null || lastDragClientX === null) return;
    if (touchMode === 'follow') followTarget = followPaddleTarget(lastDragClientX);
    else dragOffset = paddle.x - canvasX(lastDragClientX);
}


function setBanner(text, fraction = 0, kind = 'active', low = false) {
    const el = document.getElementById('event-banner');
    if (!el) return;
    if (text === null) {
        if (bannerCache.text !== null) {
            el.style.display = 'none';
            bannerCache.text = null;
        }
        return;
    }
    const pct = Math.round(fraction * 100);
    const cls = kind + (low ? ' low' : '');
    if (bannerCache.text !== text || bannerCache.kind !== cls) {
        el.lastElementChild.textContent = text;
        el.className = cls;
        el.style.display = 'block';
        bannerCache.text = text;
        bannerCache.kind = cls;
        bannerCache.pct = -1;
    }
    if (bannerCache.pct !== pct) {
        el.firstElementChild.style.width = pct + '%';
        bannerCache.pct = pct;
    }
}


function chaosLabel(key) {
    if (key === 'timeWarp') return chaos.scale > 1 ? '\u23e9 TURBO \u00d7' + chaos.scale : '\ud83d\udc22 SLOW-MO \u00d7' + chaos.scale;
    return CHAOS[key].name;
}


function updateBanner() {
    if (chaos.warn > 0) {
        setBanner('\u26a0 ' + chaosLabel(chaos.pending) + ' in ' + Math.ceil(chaos.warn / 60) + '\u2026', chaos.warn / CHAOS_WARN_FRAMES, 'warn');
    } else if (chaos.type) {
        const flippedVertically = chaos.type === 'upsideDown' || chaos.type === 'fullFlip';
        setBanner(chaosLabel(chaos.type) + '  ' + Math.ceil(chaos.left / 60) + 's', chaos.left / chaos.total, 'active', flippedVertically);
    } else if (reverseFrames > 0) {
        setBanner('MIND FLIP: CONTROLS REVERSED ' + Math.ceil(reverseFrames / 60) + 's', reverseFrames / reverseTotal, 'active');
    } else {
        setBanner(null);
    }
}


function endChaos(reschedule) {
    chaos.type = null;
    chaos.pending = null;
    chaos.warn = 0;
    chaos.left = 0;
    timeScale = 1;
    reverseFrames = 0;
    applyView();
    refreshInputMapping();
    setBanner(null);
    if (reschedule && chaosEventsLeft > 0) scheduleChaos(20, 20);
}


function initChaos() {
    endChaos(false);
    chaosEventsLeft = plan.chaos ? plan.chaos.events : 0;
    if (plan.chaos) scheduleChaos(22, 18); // the first one arrives 22-40 seconds in
    else chaosTimer = Infinity;
}


function startChaosWarning() {
    const pool = chaosPool();
    if (!pool.length) {
        chaosEventsLeft = 0;
        return;
    }
    chaos.pending = pool[Math.floor(Math.random() * pool.length)];
    if (chaos.pending === 'timeWarp') chaos.scale = Math.random() < 0.5 ? TIME_WARP.turbo : TIME_WARP.slow;
    chaos.warn = CHAOS_WARN_FRAMES;
    tone(330, 0.15, { type: 'sawtooth', vol: 0.18, key: 'chaos' });
    tone(440, 0.15, { type: 'sawtooth', vol: 0.18, delay: 0.17, force: true });
    tone(330, 0.15, { type: 'sawtooth', vol: 0.18, delay: 0.34, force: true });
    haptic([30, 50, 30], true);
}


function startChaos(key) {
    chaos.type = key;
    chaos.pending = null;
    chaos.warn = 0;
    chaos.total = chaos.left = CHAOS[key].seconds * 60;
    chaosEventsLeft--;
    if (key === 'timeWarp') timeScale = chaos.scale;
    applyView();
    refreshInputMapping();
    addShake(6);
    haptic([40, 40, 80], true);
    tone(200, 0.4, { type: 'sawtooth', vol: 0.25, slideTo: 800, key: 'chaosStart', force: true });
}


function updateChaos() {
    if (reverseFrames > 0 && --reverseFrames === 0) refreshInputMapping();
    if (chaos.warn > 0) {
        if (--chaos.warn === 0) startChaos(chaos.pending);
    } else if (chaos.type) {
        if (--chaos.left <= 0) endChaos(true);
    } else if (chaosEventsLeft > 0 && --chaosTimer <= 0) {
        startChaosWarning();
    }
    updateBanner();
}

// --- Boss fights (every 5th level) ---
// A mothership with a health bar and a weak point (the amber x3 hatch on its belly, worth triple damage). Three phases as its health drops: aimed fans of bolts; then bolt rain and
// summoned aliens; then a "mind flip" beam that reverses your controls. Bolts punch holes in the paddle
// like any alien's. Beating it clears the level, awards points and an extra life.

function drawTimeWarpFx() {
    if (timeScale === 1) return;
    ctx.save();
    if (timeScale > 1) {
        ctx.fillStyle = 'rgba(255, 110, 30, 0.10)';
        ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
        ctx.fillStyle = 'rgba(255, 255, 255, 0.16)';
        for (let i = 0; i < 10; i++) ctx.fillRect(Math.random() * CANVAS_W, Math.random() * CANVAS_H, 50 + Math.random() * 90, 1.5);
    } else {
        ctx.fillStyle = 'rgba(70, 130, 255, 0.14)';
        ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
    }
    ctx.restore();
}

