// === constants.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

const CANVAS_W = 900;

const CANVAS_H = 600;

// Canvas text uses the page's retro fonts (loaded by the <link> in index.html). Press Start 2P runs about
// 1em per glyph, far wider than the sans text it replaced, so headlines use it at a smaller size; VT323
// renders small for its nominal size, so labels use it larger.
const PIXEL_FONT = "'Press Start 2P', 'Courier New', monospace";
const TERM_FONT = "VT323, 'Courier New', monospace";
function pixelFont(px) { return px + 'px ' + PIXEL_FONT; }
function termFont(px) { return px + 'px ' + TERM_FONT; }

// --- Game Entities ---

const COMBO_MAX = 5;

const reduceMotion = !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
// Add ?perf to the URL for an on-screen frame-rate / frame-time readout (for finding slowdowns on a device)

const PERF = /[?&]perf(=|&|$)/.test(window.location.search);

const BRICK_ROWS = 6;

const BRICK_COLS = 12;

const BRICK_W = 64;

const BRICK_H = 20;

const BRICK_OFFSET_TOP = 60;

const BRICK_OFFSET_LEFT = (CANVAS_W - BRICK_COLS * BRICK_W) / 2;

const PADDLE_W = 110;

const PADDLE_H = 12;

const BALL_RADIUS = 8;

// --- Device & Input Helpers ---

const CENTER_COL = (BRICK_COLS - 1) / 2;

const LAYOUTS = [
    { name: 'Wall', alive: () => true },
    { name: 'Checkerboard', alive: (c, r) => (c + r) % 2 === 0 },
    { name: 'Stripes', alive: (c) => c % 3 !== 2 },
    { name: 'Pyramid', alive: (c, r) => Math.abs(c - CENTER_COL) <= r + 1.2 },
    {
        // Battlements on top, side towers + centre gate in the middle, solid base
        name: 'Castle',
        alive: (c, r) => {
            if (r === 0) return c % 2 === 0;
            if (r <= 2) return c < 3 || c >= BRICK_COLS - 3 || c === 5 || c === 6;
            return true;
        }
    },
    { name: 'Diagonals', alive: (c, r) => (c + r) % 4 < 2 },
    { name: 'Lattice', alive: (c, r) => r % 2 === 0 || c % 2 === 0 }, // solid rows alternate with checkered gaps
    { name: 'Funnel', alive: (c, r) => Math.abs(c - CENTER_COL) <= (BRICK_ROWS - r) + 0.2 }, // inverted pyramid
    // Wide at the top and bottom, pinched in the middle: the ball has to squeeze through the waist
    { name: 'Hourglass', alive: (c, r) => Math.abs(c - CENTER_COL) <= 1 + 2 * Math.abs(r - (BRICK_ROWS - 1) / 2) },
    // A space invader, drawn in bricks (see INVADER_ART)
    { name: 'Invader', alive: (c, r) => INVADER_ART[r][c] === 'X' },
    // A hollow keep: an outer ring, empty moat, and a core that is only reachable through the ring
    {
        name: 'Fortress',
        alive: (c, r) => r === 0 || r === BRICK_ROWS - 1 || c <= 1 || c >= BRICK_COLS - 2 || (r >= 2 && r <= 3 && c >= 4 && c <= 7)
    },
    { name: 'Chevrons', alive: (c, r) => (r + Math.floor(Math.abs(c - CENTER_COL))) % 3 < 2 }, // V-shaped stripes
    { name: 'Diamond', alive: (c, r) => Math.abs(c - CENTER_COL) / 2 + Math.abs(r - (BRICK_ROWS - 1) / 2) <= 3 }
];

const INVADER_ART = [
    '..X......X..',
    '...XXXXXX...',
    '..XX.XX.XX..',
    '.XXXXXXXXXX.',
    '.X.XXXXXX.X.',
    '...XX..XX...'
];

const STEEL_STYLES = ['top row', 'clusters', 'diagonal'];

// Row-based scoring and colour, top to bottom

const ROW_STYLES = [
    { points: 30, color: '#FFD700' },
    { points: 25, color: '#FFA500' },
    { points: 20, color: '#FF4500' },
    { points: 15, color: '#FF0000' },
    { points: 10, color: '#8B0000' },
    { points: 5, color: '#006400' }
];


// The main game's curve, in curve levels (see curveLevel in level.js): level N after the tutorial is curve
// level N - TUTORIAL_LEVELS. Everything up to UNLOCK.chaos is taught by the tutorial and in play from the
// first level after it.
const UNLOCK = { tnt: 2, walls: 3, aliens: 3, chaos: 4, bumpers: 4, reverse: 6, fullFlip: 8, boss: 5, tetris: 7, cheat: 2 };

// --- Levels 1-5: the tutorial ---
// Five short levels with only a handful of bricks, each showing one new thing, before the main game.
// unlock: the curve level whose unlocks it has (so its drops and events are what it has taught so far).
const TUTORIAL = [
    { name: 'Warm-up', unlock: 1, alive: (c, r) => r >= 2 && r <= 3 && c >= 2 && c <= 9 },
    { name: 'Boom', unlock: 2, tnt: 2, alive: (c, r) => r >= 1 && r <= 3 && c >= 2 && c <= 9 },
    { name: 'Company', unlock: 3, walls: 1, aliens: true, alive: (c, r) => r >= 1 && r <= 2 && c >= 1 && c <= 10 },
    { name: 'Flip Side', unlock: 4, chaos: true, alive: (c, r) => r <= 3 && c >= 2 && c <= 9 && (c + r) % 2 === 0 },
    { name: 'Gold Rush', unlock: 4, code: true, steel: (c, r) => r === 1, alive: (c, r) => r >= 1 && r <= 3 && c >= 3 && c <= 8 }
];
const TUTORIAL_LEVELS = TUTORIAL.length;

// Each boss debuts in this order, one per boss encounter (levels 10, 15, 20, 25); after that every boss
// level picks one of them at random, seeded per level (see spawnBoss in boss.js). The mothership is the
// gentlest, so it comes first; the snake is the toughest to read, so it waits until you've seen two.
const BOSS_ORDER = ['mothership', 'pong', 'snake', 'asteroids', 'kong'];
// How tough each boss is on its debut, whatever encounter that is: the mothership and the snake at their
// gentlest, the rival and the asteroid field at the strength they were tuned at (their old debut spots).
// Past the debuts a boss's strength is simply the encounter number.
const BOSS_DEBUT_STRENGTH = { mothership: 1, pong: 3, snake: 1, asteroids: 4, kong: 3 };

// --- Pong boss: "The Rival" (pongBoss.js) ---
const PONG_Y = 104;                // the rival paddle's top edge, just under the boss health bar
const PONG_H = 12;
const PONG_WIDTHS = [140, 118, 96]; // paddle width in phases 1-3 (phase 3 has two of them)
const PONG_SPEED_BASE = 2.6;       // px per step the rival can move, before the per-encounter ramp
const PONG_SPEED_PER_N = 0.25;
const PONG_SPEED_PER_PHASE = 0.5;
const PONG_AIM_ERROR = 0.8;        // up to this share of its width off where the ball will really arrive
const PONG_SMASH = 1.06;           // from phase 2 each return speeds the ball up by this much...
const PONG_SMASH_CAP = 1.3;        // ...up to this multiple of the level's normal ball speed
const PONG_NET_Y = 330;
// Its one-way bricks: PONG_WALL_COUNT of them on random cells of a grid in its half of the court, from
// just under its paddle down towards the net (full-width columns, PONG_WALL_ROWS rows). Every few seconds
// each one fades out and reappears on another free cell.
const PONG_WALL_TOP = PONG_Y + PONG_H + 22;
const PONG_WALL_ROWS = 6;
const PONG_WALL_ROW_STEP = 26;
const PONG_WALL_COUNT = 8;
const PONG_HOP_MIN = 60 * 4;        // frames a brick stays put before hopping elsewhere...
const PONG_HOP_SPREAD = 60 * 3;     // ...plus up to this much, so they don't all hop at once
const PONG_HOP_FADE = 20;           // frames to fade out, and again to fade back in (not solid meanwhile)
const PONG_WALL_POINTS = 40;

// --- Asteroids boss: "Asteroid Field" (asteroidsBoss.js) ---
// Rock tiers: a hit splits a rock into two of the next tier down, and a tier-1 rock just breaks. Points
// follow the arcade original: the smaller (harder to hit) the rock, the more it's worth.
const ROCK_TIERS = { 3: { r: 62, speed: 1.0, points: 20 }, 2: { r: 36, speed: 1.8, points: 50 }, 1: { r: 19, speed: 2.7, points: 100 } };
// The vault the field guards: VAULT_ROWS rows of ordinary bricks from VAULT_TOP (just under the boss
// health bar), sealed by a lock row right below them. Rocks drift between the lock row and ROCK_BOTTOM.
const VAULT_TOP = 84;
const VAULT_ROWS = 2;
const ROCK_TOP = VAULT_TOP + (VAULT_ROWS + 1) * BRICK_H + 6;
const ROCK_BOTTOM = 470;           // low enough that a rock can come at you before you've read its bounce
// One key per third of the lock row, each in its own colour (the locks it opens share it): 0 opens the
// middle, 1 the left, 2 the right. None of them clash with the vault's yellow and orange bricks.
const KEY_COLORS = ['#2de2e6', '#ff2fb4', '#3dfc8a'];
const KEY_NAMES = ['CYAN', 'PINK', 'GREEN'];
const KEY_LOCK_SHADES = ['#136f73', '#7e1459', '#1b7a45']; // the locked bricks' body, a darker tone of each
const FIELD_KEYS = KEY_COLORS.length;
const KEY_FALL_VY = 1.7;           // a freed key drifts down, a little slower than a powerup capsule
const KEY_DROP_CHANCE = { 3: 0.35, 2: 0.6, 1: 1 }; // per key, each time the rock holding it is hit, by rock size

// --- Snake boss ---
const SNAKE_CELL = 28;      // square cells, unlike the bricks' 64x20 — a proper classic-Snake grid
const SNAKE_COLS = 22;
const SNAKE_ROWS = 13;
const SNAKE_LEFT = (CANVAS_W - SNAKE_COLS * SNAKE_CELL) / 2;
const SNAKE_TOP = 110;       // below the boss health bar / event banner area
const SNAKE_COLOR = '#3ddc6b';
const SNAKE_HEAD_COLOR = '#8dffab';
const SNAKE_OBSTACLE_COLOR = '#8a6d3b';
const SNAKE_REGROW_DELAY_FRAMES = 60 * 3;   // no hits for this long and it starts regrowing
const SNAKE_REGROW_INTERVAL_FRAMES = 45;    // then one segment back every 0.75s while under that grace
const SNAKE_OBSTACLE_RESPAWN_MIN = 1.5;     // seconds — snappier than the mothership's crates, since a
const SNAKE_OBSTACLE_RESPAWN_SPREAD = 1.5;  // stale gap in the grid just makes the fight feel slow, and a
                                             // full grid gives the ball more to ping-pong off on the way in
const SNAKE_OBSTACLE_GHOST_SHARE = 0.3;     // this fraction of obstacles are harmless see-through decoys
const SNAKE_WALL_W = 120;                   // a moving paddle-like wall floating between the arena and the
const SNAKE_WALL_H = 14;                    // player's paddle — a second surface to rally the ball off of,
const SNAKE_WALL_Y = SNAKE_TOP + SNAKE_ROWS * SNAKE_CELL + 20; // sits close under the grid, leaving most of
                                                                 // the gap as paddle reaction room below it —
                                                                 // it used to split that room evenly (~46px
                                                                 // to the paddle), which was tight enough to
                                                                 // lose a ball to a bad bounce right off spawn
const SNAKE_WALL_BASE_SPEED = 3.4;          // a bit brisker than the ordinary walls' opening speed, and
const SNAKE_WALL_SPEED_PER_N = 0.5;         // ramps with each repeat encounter, capped so it stays returnable
const SNAKE_WALL_MAX_SPEED = 7.5;
const SNAKE_MAX_CUT_FRACTION = 0.3;         // a single hit can never remove more than this share of the
                                             // snake's CURRENT length (so a head shot can't one-shot it,
                                             // and no single hit guts most of it either); the last segment
                                             // is always finishable in one hit regardless
const SNAKE_ASSIST_SEGMENTS = 3;    // at or below this many segments left, it's a small fast target —
const SNAKE_ASSIST_CHANCE = 0.55;   // drops get more frequent and lean toward Multi-ball & Shield to help land the finish

// -- Snake venom: the boss's own attack. It periodically lobs a poisoned capsule from its head on a
// side-to-side weave (echoing its own movement) instead of a normal straight drop — the curve alone tells
// you it's not a real powerup before you even register the color. Catching one, or grazing an "armed"
// ghost decoy, applies a short debuff instead of a bonus. --
const SNAKE_POISON_COLOR = '#a64dff';       // toxic purple — the unmistakable "don't catch this" tell
const SNAKE_POISON_GLOW = '#7dff5c';        // sickly green accent for the drip/glow around it
const SNAKE_SPIT_INTERVAL_MIN = 6;          // seconds between spits before the n-based ramp
const SNAKE_SPIT_INTERVAL_SPREAD = 3;
const SNAKE_SPIT_INTERVAL_PER_N = 0.35;
const SNAKE_SPIT_INTERVAL_FLOOR = 3;
const SNAKE_SPIT_GRACE_FRAMES = 60 * 4;     // no spit for the first few seconds of a fresh encounter
const SNAKE_SPIT_CURVE_AMPLITUDE = 50;      // px of side-to-side sway as the capsule falls
const SNAKE_SPIT_CURVE_FREQ = 0.045;
const SNAKE_SPIT_VY = 2.1;                  // a bit slower than a normal powerup — reads as lobbed, not dropped
const SNAKE_POISON_DEBUFFS = ['mirror', 'fast', 'shrink'];
const SNAKE_POISON_SHRINK_SECONDS = 7;
const SNAKE_GHOST_ARM_CHANCE = 0.009;       // per ghost obstacle, per frame
const SNAKE_GHOST_ARM_FRAMES = 210;         // ~3.5s window — long enough for normal ball traffic near a
                                             // decoy to plausibly clip it, not just a blink-and-miss-it flash
const SNAKE_GHOST_POISON_SCALE = 0.5;       // an armed-decoy graze is unlucky, not deliberate — half the spit's duration

const CHEAT_CHANCE_START = 0.4; // chance of a cheat-code brick right when they unlock
const CHEAT_CHANCE_FLOOR = 0.1; // they never get rarer than this, however high the level
const CHEAT_COLOR = '#e8b400'; // gold, distinct from TNT's red/yellow so the two are never confused
// First level each powerup can drop on (anything not listed is there from level 1)

const POWERUP_UNLOCK = { multi: 2, explosive: 2, double: 2, sticky: 3, shield: 3, fire: 4, guided: 6, split: 5 };
// Short "what's new" hints, shown when the level starts

// What's new on a level, shown as an intro card at launch (see showLevelIntro in level.js). One or two
// short lines: nobody reads more. Anything else is told the moment it happens (see bossTip in boss.js).
const LEVEL_INTROS = {
    1: { title: 'BREAK ALL THE BRICKS', lines: ['Catch the drops that fall for powerups'] },
    2: { title: 'NEW: TNT', lines: ['It blows up everything around it'] },
    3: { title: 'NEW: WALLS & ALIENS', lines: ['Shoot aliens down before they hole your paddle'] },
    4: { title: 'NEW: WEIRD EVENTS', lines: ['Now and then the world flips or changes speed'] },
    5: { title: 'NEW: LEVEL CODES', lines: ['Catch what falls from the gold ? brick', 'Grey steel bricks take two hits'] },
    6: { title: 'TRAINING OVER', lines: ['Every 5th level is a boss fight'] },
    9: { title: 'NEW: BUMPERS', lines: ['Pinball bumpers kick the ball away faster', 'Every hit scores. They never break'] },
    10: { lines: ['New drop: Split Paddle'] }, // joins the boss card (level 10 is the first boss)
    11: { title: 'NEW: MIND FLIPS', lines: ['Your controls may reverse'] },
    13: { title: 'NEW: FULL FLIP', lines: ['The whole screen may turn over'] }
};

// Each boss's goal, shown the first time you meet that boss in a session: just how you win. Its tricks
// are called out as they happen (see bossTip in boss.js). Which boss a level brings isn't fixed past the
// debuts (see BOSS_ORDER), so these can't be keyed by level like the intros above.
const BOSS_INTROS = {
    snake: { title: 'BOSS: THE SNAKE', lines: ['Chop it down to nothing!'] },
    mothership: { title: 'BOSS: MEGA INVADER', lines: ['Shoot it down!'] }, // (kind 'mothership': it was a flying saucer once)
    pong: { title: 'BOSS: THE RIVAL', lines: ['Score goals past its paddle!'] },
    asteroids: { title: 'BOSS: ASTEROID FIELD', lines: ['Smash the vault bricks at the top!'] },
    kong: { title: 'BOSS: BARREL KONG', lines: ['Get the ball up the tower and bash the ape!'] }
};

const CHAOS = {
    timeWarp: { name: 'TIME WARP', seconds: 9, unlock: UNLOCK.chaos },
    upsideDown: { name: 'UPSIDE DOWN', seconds: 10, unlock: UNLOCK.chaos, visual: true },
    reverse: { name: 'REVERSED CONTROLS', seconds: 8, unlock: UNLOCK.reverse },
    fullFlip: { name: 'FULL FLIP', seconds: 10, unlock: UNLOCK.fullFlip, visual: true }
};

const CHAOS_WARN_FRAMES = 120;

const TIME_WARP = { turbo: 1.6, slow: 0.5 };

const BOSS_HOLE_SECONDS = 5; // holes from a boss's bolts close faster than an alien's

const BEAM_HALF = 26;        // half-width of the mind-flip beam

const BOSS_CHAIN_FRAMES = 300; // hit the boss again within 5 seconds to keep a damage chain going

// Damage multiplier for the n-th boss hit in a chain: x1, then x2 from the 2nd hit, x3 from the 4th

const CRATE_COUNT = 4;

const WARP_MAX_STEPS = 5;

const WARP_WARN_FRAMES = 90;   // 1.5s telegraph before it's live

const WARP_LIFE_FRAMES = 480;  // ~8s to reach it once live, or it closes unused

const WARP_R = 30;             // the rift's own visible/consuming size

const WARP_PULL_R = 130;       // how far out it starts pulling the ball in

const WARP_PULL_MAX = 0.9;     // strongest pull, applied right at the edge of the rift itself

const WARP_ON_ALIEN_KILL_CHANCE = 0.5;

const WARP_TINT = '120, 90, 255'; // the rift's violet (see drawVortex in warpRift.js)

// --- Portal pairs (portals.js): ball in one, out the other, momentum kept ---
const PORTAL_UNLOCK = 3;
const PORTAL_R = WARP_R;            // the same size and gravity as a warp rift...
const PORTAL_PULL_R = WARP_PULL_R;
const PORTAL_PULL_MAX = WARP_PULL_MAX;
const PORTAL_EXIT_MIN_CLIMB = 0.5;  // ...and the ball always leaves the far one heading up, at least this steeply (|vy| / speed)
const PORTAL_WARN_FRAMES = 75;
const PORTAL_LIFE_FRAMES = 60 * 12;

// --- Pinball bumpers (bumpers.js): unbreakable round posts in the open band above the paddle ---
const BUMPER_R = 26;
const BUMPER_POINTS = 10;
const BUMPER_KICK = 1.12;       // each hit speeds the ball up by this much...
const BUMPER_KICK_CAP = 1.35;   // ...up to this multiple of the level's normal ball speed (a paddle bounce resets it)
const BUMPER_MIN_CLIMB = 0.3;   // the ball always leaves a bumper at least this steep (|vy| / speed), never flat
const BUMPER_COLOR = '#ff2fb4';
const BUMPER_CAP_COLOR = '#2de2e6';

const TETRIS_COLORS = ['#00e5ff', '#ffd23f', '#b56bff', '#4de08c', '#ff5a5a', '#3d7bff', '#ff9a2e', '#e05cff'];

const GHOST_CLEAR_DELAY = 14; // frames a finished row waits, so rows finished by the same pass clear together


const TNT_COLOR = '#7a1010';

const RALLY_WINDOW_FRAMES = 150; // ~2.5s between alternating touches to keep the rally alive

const RALLY_THRESHOLD = 4;       // touches needed (two full paddle<->wall round trips) before it calls out

const RALLY_MAX_SHOUT = 7;       // the popup stops growing past this streak; the bonus keeps scaling


const STAR_LAYERS = 3;

const BALL_LOOKS = {
    normal: { trailCore: '255, 140, 215', trailEdge: '255, 47, 180', trailA: 0.32, trailGrow: 0.9, halo: '255, 47, 180', haloA: 0.45, haloR: 2.6, mid: '#ffc8ec', edge: '#ff2fb4' },
    fire: { trailCore: '255, 190, 40', trailEdge: '255, 90, 0', trailA: 0.42, trailGrow: 1.3, halo: '255, 150, 20', haloA: 0.6, haloR: 3.4, mid: '#ffd23f', edge: '#ff5a00' },
    guided: { trailCore: '190, 140, 255', trailEdge: '110, 60, 230', trailA: 0.4, trailGrow: 1.1, halo: '160, 108, 255', haloA: 0.55, haloR: 3.0, mid: '#c9a0ff', edge: '#6a2fd0' }
};

// Lock-on reticle over the brick a guided ball is heading for

const MAX_VOICES = 8;

const MIN_GAP_MS = 45;

const MIN_HAPTIC_GAP_MS = 60;

const MAX_PARTICLES = 220;

const POWERUP_CHANCE = 0.25;
// weight: relative drop chance (extra life is the rarest)

const POWERUP_TYPES = [
// tip: what it does, told the first time you catch one (see explainDrop in powerups.js)
    { type: 'life', label: '+', color: '#33cc33', text: '+1 Life', weight: 1, tip: 'One extra life' },
    { type: 'slow', label: 'S', color: '#cc33cc', text: 'Slow Ball', weight: 2, tip: 'The ball slows down for a while' },
    { type: 'wide', label: 'W', color: '#ff9900', text: 'Wide Paddle', weight: 2, tip: 'A wider paddle for a while' },
    { type: 'explosive', label: 'E', color: '#ff3366', text: 'Explosive!', weight: 2, tip: 'Your next brick hit blows up the bricks around it' },
    { type: 'multi', label: 'M', color: '#3399ff', text: 'Multi-Ball!', weight: 2, tip: 'The ball splits in two on its next paddle bounce' },
    { type: 'double', label: '2×', color: '#c98f00', text: '2× Score!', weight: 1.5, tip: 'Double points for a while' },
    { type: 'shield', label: null, color: '#22bbdd', text: 'Shield!', weight: 1.5, tip: 'The line at the bottom saves one missed ball' }, // label null: drawn as a shield icon
    { type: 'fire', label: 'F', color: '#ff6a00', text: 'Fire Ball!', weight: 1.5, tip: 'The ball burns straight through bricks' },
    { type: 'sticky', label: 'G', color: '#7cb518', text: 'Sticky Paddle!', weight: 2, tip: 'The paddle catches the ball: aim, then release it' },
    { type: 'guided', label: 'A', color: '#a06cff', text: 'Guided Ball!', weight: 1.5, tip: 'The ball steers itself toward the best target' },
    { type: 'split', label: '⇄', color: '#14e6b4', text: 'Split Paddle!', weight: 1.5, tip: 'A mirrored second paddle on the other side' }
];

const GUIDED_SECONDS = 8;

const GUIDED_TURN = 0.045; // max steering per frame (radians), so the ball curves rather than snaps

const FIRE_SECONDS = 6;

const STICKY_CATCHES = 3;

const SHIELD_MAX = 5; // shields compound: each catch banks one more free miss, up to this cap

const STICKY_MAX_FRAMES = 180; // a stuck ball auto-releases after 3s so it can never soft-lock the game

// Split Paddle: your paddle becomes two half-width halves — one follows your input exactly like normal,
// the other mirrors it around the centre of the screen, so it always moves the opposite way. Great with
// Multi-ball: two independent catchers, moving in opposite directions from one input.
const SPLIT_SECONDS = 10;
const SPLIT_HALF_RATIO = 0.55; // each half's width, as a fraction of the normal single paddle's width

const HOLE_W = 28;        // wider than the 16px ball, so a ball over a hole really falls through

const HOLE_SECONDS = 9;

const ALIEN_W = 33;       // 11 x 8 sprite cells at 3px

const ALIEN_H = 24;

const ALIEN_COLOR = '#5CFF7A';

const ALIEN_SPRITES = [
    ['00100000100', '00010001000', '00111111100', '01101110110', '11111111111', '10111111101', '10100000101', '00011011000'],
    ['00100000100', '10010001001', '10111111101', '11101110111', '11111111111', '01111111110', '00100000100', '01000000010']
];

// -- Paddle holes --
// The solid parts of the paddle as [x0, x1] intervals in canvas coordinates

const SLOW_RECOVER_FRAMES = 30; // when Slow runs out, the balls ease back up to speed over this many steps

const STEP_MS = 1000 / 60;

const MAX_STEPS_PER_FRAME = 3; // if the device can't keep up, drop the backlog instead of spiralling

const FOLLOW_INSET = 0.05;    // share of the thumb pad's width at each end that already counts as the wall
const FOLLOW_MAX_STEP = 55;   // canvas px per 60 Hz step

const POINTER_LOCK_SENSITIVITY = 1.6;
