// === constants.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

const CANVAS_W = 900;

const CANVAS_H = 600;

// --- Game Entities ---

const COMBO_MAX = 5;

const reduceMotion = !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
// Add ?perf to the URL for an on-screen frame-rate / frame-time readout (for finding slowdowns on a device)

const PERF = /[?&]perf(=|&|$)/.test(window.location.search);

const BRICK_ROWS = 6;

const BRICK_COLS = 12;

const BRICK_W = 64;

const BRICK_H = 20;

const BRICK_OFFSET_TOP = 60;

const BRICK_OFFSET_LEFT = (CANVAS_W - BRICK_COLS * BRICK_W) / 2;

const PADDLE_W = 110;

const PADDLE_H = 12;

const BALL_RADIUS = 8;

// --- Device & Input Helpers ---

const CENTER_COL = (BRICK_COLS - 1) / 2;

const LAYOUTS = [
    { name: 'Wall', alive: () => true },
    { name: 'Checkerboard', alive: (c, r) => (c + r) % 2 === 0 },
    { name: 'Stripes', alive: (c) => c % 3 !== 2 },
    { name: 'Pyramid', alive: (c, r) => Math.abs(c - CENTER_COL) <= r + 1.2 },
    {
        // Battlements on top, side towers + centre gate in the middle, solid base
        name: 'Castle',
        alive: (c, r) => {
            if (r === 0) return c % 2 === 0;
            if (r <= 2) return c < 3 || c >= BRICK_COLS - 3 || c === 5 || c === 6;
            return true;
        }
    },
    { name: 'Diagonals', alive: (c, r) => (c + r) % 4 < 2 },
    { name: 'Lattice', alive: (c, r) => r % 2 === 0 || c % 2 === 0 }, // solid rows alternate with checkered gaps
    { name: 'Funnel', alive: (c, r) => Math.abs(c - CENTER_COL) <= (BRICK_ROWS - r) + 0.2 } // inverted pyramid
];

const STEEL_STYLES = ['top row', 'clusters', 'diagonal'];

// Row-based scoring and colour, top to bottom

const ROW_STYLES = [
    { points: 30, color: '#FFD700' },
    { points: 25, color: '#FFA500' },
    { points: 20, color: '#FF4500' },
    { points: 15, color: '#FF0000' },
    { points: 10, color: '#8B0000' },
    { points: 5, color: '#006400' }
];


const UNLOCK = { tnt: 2, walls: 3, aliens: 3, chaos: 4, reverse: 6, fullFlip: 8, boss: 5, tetris: 7, cheat: 2 };
const CHEAT_CHANCE_START = 0.4; // chance of a cheat-code brick right when they unlock
const CHEAT_CHANCE_FLOOR = 0.1; // they never get rarer than this, however high the level
const CHEAT_COLOR = '#e8b400'; // gold, distinct from TNT's red/yellow so the two are never confused
// First level each powerup can drop on (anything not listed is there from level 1)

const POWERUP_UNLOCK = { multi: 2, explosive: 2, double: 2, sticky: 3, shield: 3, fire: 4, guided: 6 };
// Short "what's new" hints, shown when the level starts

const LEVEL_INTROS = {
    2: ['NEW: TNT bricks chain-explode', 'NEW drops: Multi-ball, Explosive, 2× Score'],
    3: ['NEW: sliding walls', 'NEW: aliens shoot holes in your paddle: shoot them down!', 'NEW drops: Sticky, Shield'],
    4: ['NEW: weird events: the world may flip or change speed', 'NEW drop: Fire ball'],
    5: ['BOSS FIGHT', 'Hit the amber \u00d73 hatch on its belly for triple damage', 'Gold crates hold powerups (new ones keep appearing): break them, or catch what the boss shoots loose', 'Hit it again within 5 seconds to chain: \u00d72, then \u00d73 damage'],
    6: ['NEW: your controls may reverse', 'NEW drop: Guided ball'],
    8: ['NEW: the whole screen may flip']
};

const CHAOS = {
    timeWarp: { name: 'TIME WARP', seconds: 9, unlock: UNLOCK.chaos },
    upsideDown: { name: 'UPSIDE DOWN', seconds: 10, unlock: UNLOCK.chaos, visual: true },
    reverse: { name: 'REVERSED CONTROLS', seconds: 8, unlock: UNLOCK.reverse },
    fullFlip: { name: 'FULL FLIP', seconds: 10, unlock: UNLOCK.fullFlip, visual: true }
};

const CHAOS_WARN_FRAMES = 120;

const TIME_WARP = { turbo: 1.6, slow: 0.5 };

const BOSS_HOLE_SECONDS = 5; // holes from a boss's bolts close faster than an alien's

const BEAM_HALF = 26;        // half-width of the mind-flip beam

const BOSS_CHAIN_FRAMES = 300; // hit the boss again within 5 seconds to keep a damage chain going

// Damage multiplier for the n-th boss hit in a chain: x1, then x2 from the 2nd hit, x3 from the 4th

const CRATE_COUNT = 4;

const WARP_MAX_STEPS = 5;

const WARP_WARN_FRAMES = 90;   // 1.5s telegraph before it's live

const WARP_LIFE_FRAMES = 480;  // ~8s to reach it once live, or it closes unused

const WARP_R = 30;             // the rift's own visible/consuming size

const WARP_PULL_R = 130;       // how far out it starts pulling the ball in

const WARP_PULL_MAX = 0.9;     // strongest pull, applied right at the edge of the rift itself

const WARP_ON_ALIEN_KILL_CHANCE = 0.5;

const TETRIS_COLORS = ['#00e5ff', '#ffd23f', '#b56bff', '#4de08c', '#ff5a5a', '#3d7bff', '#ff9a2e', '#e05cff'];

const GHOST_CLEAR_DELAY = 14; // frames a finished row waits, so rows finished by the same pass clear together


const TNT_COLOR = '#7a1010';

const RALLY_WINDOW_FRAMES = 150; // ~2.5s between alternating touches to keep the rally alive

const RALLY_THRESHOLD = 4;       // touches needed (two full paddle<->wall round trips) before it calls out

const RALLY_MAX_SHOUT = 7;       // the popup stops growing past this streak; the bonus keeps scaling


const STAR_LAYERS = 3;

const BALL_LOOKS = {
    normal: { trailCore: '255, 150, 70', trailEdge: '255, 60, 60', trailA: 0.32, trailGrow: 0.9, halo: '255, 77, 77', haloA: 0.45, haloR: 2.6, mid: '#ff6b6b', edge: '#d40000' },
    fire: { trailCore: '255, 190, 40', trailEdge: '255, 90, 0', trailA: 0.42, trailGrow: 1.3, halo: '255, 150, 20', haloA: 0.6, haloR: 3.4, mid: '#ffd23f', edge: '#ff5a00' },
    guided: { trailCore: '190, 140, 255', trailEdge: '110, 60, 230', trailA: 0.4, trailGrow: 1.1, halo: '160, 108, 255', haloA: 0.55, haloR: 3.0, mid: '#c9a0ff', edge: '#6a2fd0' }
};

// Lock-on reticle over the brick a guided ball is heading for

const MAX_VOICES = 8;

const MIN_GAP_MS = 45;

const MIN_HAPTIC_GAP_MS = 60;

const MAX_PARTICLES = 220;

const POWERUP_CHANCE = 0.25;
// weight: relative drop chance (extra life is the rarest)

const POWERUP_TYPES = [
    { type: 'life', label: '+', color: '#33cc33', text: '+1 Life', weight: 1 },
    { type: 'slow', label: 'S', color: '#cc33cc', text: 'Slow Ball', weight: 2 },
    { type: 'wide', label: 'W', color: '#ff9900', text: 'Wide Paddle', weight: 2 },
    { type: 'explosive', label: 'E', color: '#ff3366', text: 'Explosive!', weight: 2 },
    { type: 'multi', label: 'M', color: '#3399ff', text: 'Multi-Ball!', weight: 2 },
    { type: 'double', label: '2×', color: '#c98f00', text: '2× Score!', weight: 1.5 },
    { type: 'shield', label: null, color: '#22bbdd', text: 'Shield!', weight: 1.5 }, // label null: drawn as a shield icon
    { type: 'fire', label: 'F', color: '#ff6a00', text: 'Fire Ball!', weight: 1.5 },
    { type: 'sticky', label: 'G', color: '#7cb518', text: 'Sticky Paddle!', weight: 2 },
    { type: 'guided', label: 'A', color: '#a06cff', text: 'Guided Ball!', weight: 1.5 }
];

const GUIDED_SECONDS = 8;

const GUIDED_TURN = 0.045; // max steering per frame (radians), so the ball curves rather than snaps

const FIRE_SECONDS = 6;

const STICKY_CATCHES = 3;

const SHIELD_MAX = 5; // shields compound: each catch banks one more free miss, up to this cap

const STICKY_MAX_FRAMES = 180; // a stuck ball auto-releases after 3s so it can never soft-lock the game

const HOLE_W = 28;        // wider than the 16px ball, so a ball over a hole really falls through

const HOLE_SECONDS = 9;

const ALIEN_W = 33;       // 11 x 8 sprite cells at 3px

const ALIEN_H = 24;

const ALIEN_COLOR = '#5CFF7A';

const ALIEN_SPRITES = [
    ['00100000100', '00010001000', '00111111100', '01101110110', '11111111111', '10111111101', '10100000101', '00011011000'],
    ['00100000100', '10010001001', '10111111101', '11101110111', '11111111111', '01111111110', '00100000100', '01000000010']
];

// -- Paddle holes --
// The solid parts of the paddle as [x0, x1] intervals in canvas coordinates

const STEP_MS = 1000 / 60;

const MAX_STEPS_PER_FRAME = 3; // if the device can't keep up, drop the backlog instead of spiralling

const FOLLOW_MAX_STEP = 55;   // canvas px per 60 Hz step

const POINTER_LOCK_SENSITIVITY = 1.6;
