// === crates.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function dropPowerup(type, x, y) {
    const t = POWERUP_TYPES.find(p => p.type === type);
    powerups.push({ x: x, y: y, type: t.type, label: t.label, color: t.color, vy: 2.5 });
}


function spawnCrates() {
    const pool = POWERUP_TYPES.filter(p => unlockLevel() >= (POWERUP_UNLOCK[p.type] || 1));
    const pickFrom = names => {
        const list = pool.filter(p => names.includes(p.type));
        return list[Math.floor(Math.random() * list.length)];
    };
    const chosen = [pickFrom(['fire', 'explosive', 'guided']), pickFrom(['wide', 'shield', 'sticky'])];
    while (chosen.length < CRATE_COUNT) {
        const p = pool[Math.floor(Math.random() * pool.length)];
        if (!chosen.includes(p)) chosen.push(p);
    }
    // Shuffle so the damage/defence crates aren't always in the same places
    for (let i = chosen.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [chosen[i], chosen[j]] = [chosen[j], chosen[i]];
    }
    const slot = (CANVAS_W - 2 * 60) / CRATE_COUNT;
    crates = chosen.map((def, i) => ({
        x: 60 + slot * i + Math.random() * (slot - BRICK_W),
        y: 255 + Math.random() * 70,
        w: BRICK_W,
        h: BRICK_H,
        alive: true,
        type: def.type,
        label: def.label,
        color: def.color,
        age: 999 // (replacement crates pop in; the first ones are just there)
    }));
    crateTimer = 0;
}

// A spot for a replacement crate: random, clear of other crates and of the balls

function freeCrateSpot() {
    for (let attempt = 0; attempt < 30; attempt++) {
        const x = 40 + Math.random() * (CANVAS_W - 80 - BRICK_W);
        const y = 250 + Math.random() * 80;
        const clear = crates.every(c => !c.alive || Math.abs(c.x - x) > BRICK_W + 12 || Math.abs(c.y - y) > BRICK_H + 12) &&
            balls.every(b => Math.hypot(b.x - (x + BRICK_W / 2), b.y - (y + BRICK_H / 2)) > 50);
        if (clear) return { x, y };
    }
    return null;
}


function respawnCrate() {
    const spot = freeCrateSpot();
    if (!spot) return false;
    const taken = crates.filter(c => c.alive).map(c => c.type);
    const options = POWERUP_TYPES.filter(p => unlockLevel() >= (POWERUP_UNLOCK[p.type] || 1) && !taken.includes(p.type));
    let roll = Math.random() * options.reduce((sum, p) => sum + p.weight, 0);
    let def = options[options.length - 1];
    for (const p of options) {
        roll -= p.weight;
        if (roll < 0) {
            def = p;
            break;
        }
    }
    crates = crates.filter(c => c.alive); // drop the broken ones from the list
    crates.push({ x: spot.x, y: spot.y, w: BRICK_W, h: BRICK_H, alive: true, type: def.type, label: def.label, color: def.color, age: 0 });
    const cx = spot.x + BRICK_W / 2;
    const cy = spot.y + BRICK_H / 2;
    spawnParticles(cx, cy, '#ffd23f', 10);
    addPopup(cx, cy - 14, 'NEW CRATE', '#ffe58a', { size: 14, life: 1 });
    tone(520, 0.12, { type: 'triangle', vol: 0.18, key: 'crateSpawn' });
    tone(780, 0.14, { type: 'triangle', vol: 0.18, delay: 0.08, force: true });
    return true;
}


function updateCrates() {
    if (!boss || boss.intro > 0 || boss.dying > 0) return;
    for (const c of crates) if (c.age !== undefined) c.age++; // drives the pop-in of new crates
    if (crateTimer > 0 && --crateTimer === 0) {
        if (crates.filter(c => c.alive).length < CRATE_COUNT) {
            const ok = respawnCrate();
            const stillMissing = crates.filter(c => c.alive).length < CRATE_COUNT;
            crateTimer = !ok ? 90 : (stillMissing ? Math.round(60 * (10 + Math.random() * 8)) : 0); // no room: retry in 1.5s
        }
    }
}


function drawCrates() {
    for (const cr of crates) {
        if (!cr.alive) continue;
        const k = cr.age === undefined ? 1 : Math.min(1, cr.age / 18);
        if (k >= 1) {
            ctx.drawImage(crateSprite(cr), cr.x, cr.y);
            continue;
        }
        // A new crate pops in: grows and fades up over ~0.3s
        const sc = 0.3 + 0.7 * k;
        ctx.save();
        ctx.globalAlpha = k;
        ctx.translate(cr.x + cr.w / 2, cr.y + cr.h / 2);
        ctx.scale(sc, sc);
        ctx.drawImage(crateSprite(cr), -cr.w / 2, -cr.h / 2);
        ctx.restore();
    }
}


function breakCrate(cr) {
    cr.alive = false;
    const cx = cr.x + cr.w / 2;
    const cy = cr.y + cr.h / 2;
    dropPowerup(cr.type, cx, cy + 6);
    spawnParticles(cx, cy, '#ffd23f', 12);
    addScore(25 * (doubleTimer > 0 ? 2 : 1));
    addPopup(cx, cy - 12, 'POWERUP!', '#ffe58a', { size: 14, life: 0.9 });
    beep(720, 'crate');
    addShake(2);
    haptic(15);
    if (crateTimer <= 0) crateTimer = Math.round(60 * (10 + Math.random() * 8)); // a replacement arrives in 10-18s
}

// Ball vs crates: it breaks one and bounces (a fire ball goes straight through)

function crateBallCollision(b) {
    for (const cr of crates) {
        if (!cr.alive) continue;
        const cx = Math.max(cr.x, Math.min(b.x, cr.x + cr.w));
        const cy = Math.max(cr.y, Math.min(b.y, cr.y + cr.h));
        const dx = b.x - cx;
        const dy = b.y - cy;
        if (dx * dx + dy * dy >= b.r * b.r) continue;
        breakCrate(cr);
        if (fireTimer <= 0) {
            if (Math.abs(dx) > Math.abs(dy)) {
                const dir = dx >= 0 ? 1 : -1;
                b.vx = dir * Math.abs(b.vx);
                b.x = dir > 0 ? cr.x + cr.w + b.r : cr.x - b.r;
            } else {
                const dir = dy >= 0 ? 1 : -1;
                b.vy = dir * Math.abs(b.vy);
                b.y = dir > 0 ? cr.y + cr.h + b.r : cr.y - b.r;
            }
        }
        return;
    }
}

// -- Boss drawing --
