// === fx.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function addScore(points) {
    if (points <= 0) return;
    score += points;
    if (score > bestScore) {
        bestScore = score;
        try {
            localStorage.setItem('breakout-best', bestScore);
        } catch (e) {
            // Storage unavailable; skip
        }
    }
    if (!newBestShown && bestAtStart > 0 && score > bestAtStart) {
        newBestShown = true;
        noteMoment(80, 'NEW HIGH SCORE!', 14);
        addPopup(CANVAS_W / 2, CANVAS_H * 0.55, 'New high score!', '#FFD700', { size: 30, life: 1.6, rise: 0.5, pop: true });
        addShake(4);
        haptic([20, 40, 20, 40, 60], true);
        sfxHighScore();
    }
}

// --- Sound ---
// Every sound goes through tone(). Each call builds an oscillator + gain node, so a burst of
// collisions (a ball riding a moving wall, multi-ball, explosions) used to pile up dozens of
// nodes and choke the audio thread and the game. tone() therefore:
//   - throttles repeats of the same sound (`key`) to one per MIN_GAP_MS,
//   - caps the number of voices playing at once,
//   - never queues sounds while the AudioContext is blocked or the tab is hidden.

function spawnParticles(x, y, color, count = 12) {
    count = Math.min(count, MAX_PARTICLES - particles.length);
    for (let i = 0; i < count; i++) {
        const angle = Math.random() * Math.PI * 2;
        const speed = 2 + Math.random() * 3;
        particles.push({
            x: x,
            y: y,
            vx: Math.cos(angle) * speed,
            vy: Math.sin(angle) * speed,
            life: 20 + Math.random() * 10,
            color: color
        });
    }
}


// Particles, blasts, popups and the intro card advance once per simulation step (see tickFx in main.js)
// and are only drawn here, since the game draws on every display refresh, not every step.
function updateParticles() {
    keepWhere(particles, p => {
        p.x += p.vx;
        p.y += p.vy;
        return --p.life > 0;
    });
}

// A burst's particles share a colour and sit together in the list, so each run of one colour goes out as
// a single path and fill, with fillStyle (a CSS string the canvas has to parse) set once per run rather
// than once per particle
function drawParticles() {
    let i = 0;
    while (i < particles.length) {
        const color = particles[i].color;
        ctx.fillStyle = color;
        ctx.beginPath();
        for (; i < particles.length && particles[i].color === color; i++) {
            const p = particles[i];
            ctx.rect(p.x - 2, p.y - 2, 4, 4);
        }
        ctx.fill();
    }
}

// --- Powerups ---
// A destroyed brick has a chance to drop a powerup; the paddle catches it.

function clearTimedEffects() {
    slowTimer = 0;
    slowRecover = 0;
    wideTimer = 0;
    narrowTimer = 0;
    splitTimer = 0;
    doubleTimer = 0;
    fireTimer = 0;
    guidedTimer = 0;
    stickyCatches = 0;
    explosiveReady = false;
    multiReady = false;
    paddle.w = PADDLE_W;
    paddleHoles.length = 0; // a new ball / level comes with a repaired paddle
}


function addBlast(x, y) {
    if (blasts.length < 24) blasts.push({ x, y, r: 12, life: 1 });
}

// Shockwave rings: expand and fade (frame-based, like popups and particles)

function updateBlasts() {
    keepWhere(blasts, b => {
        b.r += 5;
        b.life -= 0.06;
        return b.life > 0;
    });
}

function drawBlasts() {
    if (!blasts.length) return;
    ctx.save();
    for (const b of blasts) {
        ctx.globalAlpha = b.life * 0.8;
        ctx.strokeStyle = '#ffb347';
        ctx.lineWidth = 2 + b.life * 5;
        ctx.beginPath();
        ctx.arc(b.x, b.y, b.r, 0, Math.PI * 2);
        ctx.stroke();
        ctx.globalAlpha = b.life * 0.35;
        ctx.fillStyle = '#ff7a1a';
        ctx.beginPath();
        ctx.arc(b.x, b.y, b.r * 0.7, 0, Math.PI * 2);
        ctx.fill();
    }
    ctx.restore();
}


function addShake(amount) {
    if (reduceMotion) return;
    shake = Math.min(shake + amount, 16);
}


function addPopup(x, y, text, color, { life = 1, size = 16, rise = 1.5, pop = false, tag = null } = {}) {
    popups.push({ x, y, text, color, life, maxLife: life, size, rise, pop, tag });
}

// --- Level intro card ---
// What's new on a level, as a dark panel with a pixel-font title and word-wrapped lines, centred on y.
// Drawn under the ball and drops (see render in main.js) so it never hides the play while it's up.
// A panel rather than loose popups: over a busy playfield bare text was hard to read, and long lines ran
// off the canvas.
// The game waits while it's up (the ball stays on the paddle, see fixedStep), until it times out or a tap
// or Space skips it (skipIntroCard)
const INTRO_CARD_FRAMES = 60 * 6;
const INTRO_CARD_MAX_W = 620;

function showIntroCard(title, lines, y) {
    introCard = { title, lines, y, life: INTRO_CARD_FRAMES };
}

function wrapText(text, maxW) {
    const out = [];
    let line = '';
    for (const word of text.split(' ')) {
        const test = line ? line + ' ' + word : word;
        if (line && ctx.measureText(test).width > maxW) {
            out.push(line);
            line = word;
        } else {
            line = test;
        }
    }
    if (line) out.push(line);
    return out;
}

function introHold() {
    return gameState === 'playing' && introCard !== null;
}

function skipIntroCard() {
    if (introCard) introCard.life = Math.min(introCard.life, 12); // a quick fade, then play
}

function updateIntroCard() {
    if (introCard && --introCard.life <= 0) introCard = null;
}

function drawIntroCard() {
    const card = introCard;
    if (!card) return;
    const age = INTRO_CARD_FRAMES - card.life;
    ctx.save();
    ctx.globalAlpha = Math.min(1, age / 12, card.life / 30); // quick fade in, gentler fade out
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    if (!card.rows) { // word-wrapped and measured once, not on every frame it's up
        ctx.font = termFont(24);
        card.rows = card.lines.flatMap(l => wrapText(l, INTRO_CARD_MAX_W - 48));
        let textW = Math.max(...card.rows.map(r => ctx.measureText(r).width));
        ctx.font = pixelFont(15);
        textW = Math.max(textW, ctx.measureText(card.title).width);
        card.w = Math.min(INTRO_CARD_MAX_W, Math.max(340, textW + 48));
    }
    ctx.font = pixelFont(15);
    const rows = card.rows;
    const w = card.w;
    const h = 100 + rows.length * 28;
    const x = (CANVAS_W - w) / 2;
    const y = Math.round(card.y - h / 2);
    ctx.fillStyle = 'rgba(8, 4, 20, 0.86)';
    ctx.fillRect(x, y, w, h);
    ctx.strokeStyle = '#2de2e6';
    ctx.lineWidth = 2;
    ctx.strokeRect(x + 1, y + 1, w - 2, h - 2);
    ctx.fillStyle = '#7a1560';
    ctx.fillText(card.title, CANVAS_W / 2 + 2, y + 32);
    ctx.fillStyle = '#ffd319';
    ctx.fillText(card.title, CANVAS_W / 2, y + 30);
    ctx.font = termFont(24);
    ctx.fillStyle = '#ece8ff';
    rows.forEach((r, i) => ctx.fillText(r, CANVAS_W / 2, y + 66 + i * 28));
    if (Math.floor(age / 30) % 2 === 0) { // blinking, like an arcade's PRESS START
        ctx.font = pixelFont(11);
        ctx.fillStyle = '#2de2e6';
        ctx.fillText(isTouchDevice() ? 'TAP TO START' : 'PRESS SPACE TO START', CANVAS_W / 2, y + h - 20);
    }
    ctx.restore();
}

// Big "x3!" / "x4!" / "x5!" call-out when the combo multiplier climbs

function comboShout(mult, x, y) {
    const colors = { 3: '#FFD700', 4: '#FF9A2E', 5: '#FF4D4D' };
    addPopup(Math.max(60, Math.min(x, CANVAS_W - 60)), y - 26, 'x' + mult + '!', colors[mult] || '#FFD700',
        { size: 22 + mult * 4, life: 1.1, rise: 0.8, pop: true });
    noteMoment(20 + mult * 10, 'x' + mult + ' COMBO!');
    const f = 440 * Math.pow(2, mult / 6);
    tone(f, 0.1, { type: 'triangle', vol: 0.2 });
    tone(f * 1.5, 0.14, { type: 'triangle', vol: 0.2, delay: 0.07 });
    if (mult === COMBO_MAX) addShake(5);
    haptic(mult === COMBO_MAX ? [20, 30, 20, 30, 40] : [12, 30, 12], true);
}


function updatePopups() {
    keepWhere(popups, p => {
        p.y -= p.rise;
        p.life -= 0.02;
        return p.life > 0;
    });
}

// A popup's text is painted once into a little image (and cached by text, colour and size, since the same
// ones keep coming: +30, ZOOM!, PONG!...) and then drawn as an image. Painting the shadow, outline and fill
// of every popup's text on every frame was one of the costliest things on a busy screen, and a "pop"
// popup, re-rasterised at a new scale each frame for its punch-in, caused visible stutters on phones.
const popupSprites = new Map();
const POPUP_SPRITE_CACHE = 80;

function popupSprite(p) {
    const key = p.text + '|' + (p.color || '#ffffff') + '|' + p.size;
    let sp = popupSprites.get(key);
    if (sp) return sp;
    // Headlines in the pixel font with a hard arcade drop shadow; everything smaller in the terminal font
    const headline = p.size >= 20;
    const px = headline ? Math.round(p.size * 0.62) : Math.round(p.size * 1.4);
    const font = headline ? pixelFont(px) : termFont(px);
    ctx.font = font;
    const w = Math.ceil(ctx.measureText(p.text).width) + 12;
    const baseline = Math.ceil(px * 1.1) + 4;
    const h = baseline + Math.ceil(px * 0.35) + 8;
    sp = makeSprite(w, h, g => {
        g.font = font;
        g.textAlign = 'center';
        g.lineJoin = headline ? 'miter' : 'round';
        const x = w / 2 - (headline ? 1.5 : 0);
        if (headline) {
            g.fillStyle = 'rgba(0, 0, 0, 0.75)';
            g.fillText(p.text, x + 3, baseline + 3);
        }
        g.strokeStyle = 'rgba(0, 0, 0, 0.6)'; // dark outline keeps text readable (cheaper than a shadow blur)
        g.lineWidth = 3;
        g.strokeText(p.text, x, baseline);
        g.fillStyle = p.color || '#ffffff';
        g.fillText(p.text, x, baseline);
    });
    sp.baseline = baseline;
    sp.cx = w / 2 - (headline ? 1.5 : 0);
    if (popupSprites.size >= POPUP_SPRITE_CACHE) popupSprites.delete(popupSprites.keys().next().value); // oldest out
    popupSprites.set(key, sp);
    return sp;
}

function drawPopups() {
    for (const p of popups) {
        const sp = p.sprite || (p.sprite = popupSprite(p));
        const age = p.maxLife - p.life;
        const scale = p.pop ? 1 + 0.8 * Math.max(0, 1 - age / 0.12) : 1;
        ctx.globalAlpha = Math.max(0, Math.min(1, p.life * 2));
        if (scale === 1) {
            ctx.drawImage(sp, Math.round(p.x - sp.cx), Math.round(p.y - sp.baseline));
        } else {
            ctx.drawImage(sp, p.x - sp.cx * scale, p.y - sp.baseline * scale, sp.width * scale, sp.height * scale);
        }
    }
    ctx.globalAlpha = 1;
}

// Time Warp: a warm tint with speed streaks in turbo, a cool tint in slow-mo
