// === ghostRows.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function isGhostLevel(l) {
    if (isTutorial(l) || unlockLevel(l) < UNLOCK.tetris || isBossLevel(l)) return false;
    if (ghostLevelCache[l] === undefined) {
        ghostLevelCache[l] = unlockLevel(l) === UNLOCK.tetris || (seededRandom(l * 7368787 + 3)() < 0.3 && !isGhostLevel(l - 1));
    }
    return ghostLevelCache[l];
}


function buildGhostGrid(l) {
    const rand = seededRandom(l * 6700417 + 11);
    const rows = 6 + (l >= 12 ? 1 : 0) + (l >= 18 ? 1 : 0);
    const cells = [];
    for (let c = 0; c < BRICK_COLS; c++) {
        cells[c] = [];
        for (let r = 0; r < rows; r++) cells[c][r] = { state: 1, dy: 0 };
    }
    for (let r = 0; r < rows; r++) {
        // 0-2 gaps per row, so rows have different shapes and finish at different times
        const gaps = Math.floor(rand() * 3);
        for (let g = 0; g < gaps; g++) {
            const w = 1 + Math.floor(rand() * 3);
            const c0 = Math.floor(rand() * (BRICK_COLS - w + 1));
            for (let c = c0; c < c0 + w; c++) cells[c][r].state = 0;
        }
        // ...but never fewer than 5 cells in a row
        for (let c = 0; c < BRICK_COLS && cells.filter(col => col[r].state > 0).length < 5; c++) cells[c][r].state = 1;
    }
    return { rows, cells, cheatDone: false }; // cheatDone: see the cheat-code roll in clearRows()
}


function ghostCount() {
    let n = 0;
    for (const col of ghost.cells) for (const cell of col) if (cell.state > 0) n++;
    return n;
}


function ghostCellX(c) {
    return BRICK_OFFSET_LEFT + c * BRICK_W;
}

function ghostCellY(r) {
    return BRICK_OFFSET_TOP + r * BRICK_H;
}

// Every ghost cell around (x, y) that the ball currently overlaps

function ballOverlaps(b, c, r, margin = 0) {
    const x = ghostCellX(c);
    const y = ghostCellY(r);
    const cx = Math.max(x, Math.min(b.x, x + BRICK_W));
    const cy = Math.max(y, Math.min(b.y, y + BRICK_H));
    const dx = b.x - cx;
    const dy = b.y - cy;
    const rr = b.r + margin;
    return dx * dx + dy * dy < rr * rr;
}

// Cells the ball can never reach (all four neighbours solid, or walled off from outside) solidify

function fillPockets() {
    const R = ghost.rows;
    const seen = [];
    for (let c = 0; c < BRICK_COLS; c++) seen[c] = new Array(R).fill(false);
    const stack = [];
    const open = (c, r) => ghost.cells[c][r].state !== 3; // empty, ghost and arming cells can all be flown through
    const push = (c, r) => {
        if (c >= 0 && c < BRICK_COLS && r >= 0 && r < R && !seen[c][r] && open(c, r)) {
            seen[c][r] = true;
            stack.push([c, r]);
        }
    };
    // The ball can get at the grid from above, below and from both sides
    for (let c = 0; c < BRICK_COLS; c++) {
        push(c, 0);
        push(c, R - 1);
    }
    for (let r = 0; r < R; r++) {
        push(0, r);
        push(BRICK_COLS - 1, r);
    }
    while (stack.length) {
        const [c, r] = stack.pop();
        push(c + 1, r);
        push(c - 1, r);
        push(c, r + 1);
        push(c, r - 1);
    }
    let changed = false;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < R; r++) {
            const cell = ghost.cells[c][r];
            if ((cell.state === 1 || cell.state === 2) && !seen[c][r]) {
                cell.state = 3;
                changed = true;
            }
        }
    }
    return changed;
}

// Rows whose every cell is solid

function completeRows() {
    const full = [];
    for (let r = 0; r < ghost.rows; r++) {
        let n = 0;
        let solid = 0;
        for (let c = 0; c < BRICK_COLS; c++) {
            const st = ghost.cells[c][r].state;
            if (st > 0) {
                n++;
                if (st === 3) solid++;
            }
        }
        if (n > 0 && solid === n) full.push(r);
    }
    return full;
}


function clearRows(full) {
    const R = ghost.rows;
    // Score and fanfare
    const n = full.length;
    let removed = 0;
    for (const r of full) {
        for (let c = 0; c < BRICK_COLS; c++) if (ghost.cells[c][r].state > 0) removed++;
    }
    const points = 100 * n * n * (doubleTimer > 0 ? 2 : 1);
    addScore(points);
    runStats.bricks += removed;
    const label = ['', 'LINE!', 'DOUBLE!', 'TRIPLE!', 'TETRIS!'][Math.min(n, 4)];
    const topY = ghostCellY(full[0]);
    addPopup(CANVAS_W / 2, topY + 34, label + '  +' + points, ['', '#ffffff', '#ffd23f', '#ff9a2e', '#ff4d6a'][Math.min(n, 4)],
        { size: 20 + 4 * Math.min(n, 4), life: 1.5, rise: 0.4, pop: true });
    // A ghost level has no gold brick to place a cheat-code drop in, so each row clear gets its own shot
    // at one instead — at the normal per-level chance divided across every row the level has, so the odds
    // of seeing one at all stay comparable to a normal level's, just spread across however many rows
    // happen to clear. At most one per level (cheatDone), same as a gold brick.
    let cheatRow = null;
    if (plan.cheatEligible && !ghost.cheatDone) {
        const perRowChance = cheatChance() / ghost.rows;
        for (const r of full) {
            if (Math.random() < perRowChance) {
                ghost.cheatDone = true;
                cheatRow = r;
                break;
            }
        }
    }
    for (const r of full) {
        ghostFlashes.push({ y: ghostCellY(r), t: 14 });
        for (let c = 0; c < BRICK_COLS; c += 2) spawnParticles(ghostCellX(c) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2, TETRIS_COLORS[r % TETRIS_COLORS.length], 3);
        spawnPowerup(ghostCellX(1 + Math.floor(Math.random() * (BRICK_COLS - 2))) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2); // a reward per cleared row
    }
    for (let i = 0; i < n; i++) tone(440 * Math.pow(2, i / 4), 0.14, { type: 'triangle', vol: 0.22, delay: i * 0.08, force: true });
    addShake(4 + 3 * Math.min(n, 4));
    haptic(n >= 3 ? [30, 30, 60] : [20, 20, 30], true);

    // Remove the cleared rows; everything above falls to fill the gap (with a short falling animation)
    for (let c = 0; c < BRICK_COLS; c++) {
        const col = [];
        const dys = [];
        for (let r = 0; r < R; r++) {
            if (full.includes(r)) continue;
            col.push(ghost.cells[c][r]);
            dys.push(full.filter(fr => fr > r).length * BRICK_H); // how far this cell falls
        }
        const top = R - col.length;
        for (let r = 0; r < R; r++) {
            if (r < top) {
                ghost.cells[c][r] = { state: 0, dy: 0 };
            } else {
                const cell = col[r - top];
                cell.dy = dys[r - top];
                ghost.cells[c][r] = cell;
            }
        }
    }
    bricksLeft = ghostCount();
    if (cheatRow !== null) {
        const cx = ghostCellX(1 + Math.floor(Math.random() * (BRICK_COLS - 2))) + BRICK_W / 2;
        const cy = ghostCellY(cheatRow) + BRICK_H / 2;
        // This clear may have just finished the level: the capsule would never get a chance to fall
        // before completeLevel() clears it below, so award the code directly instead (same as a gold
        // brick caught as the level's last brick — see collisionDetection in main.js).
        if (bricksLeft <= 0) revealLevelCode();
        else spawnCheatCapsule(cx, cy);
    }
    // A falling solid cell must not land inside the ball: those cells become "arming" until the ball leaves
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < R; r++) {
            if (ghost.cells[c][r].state === 3 && balls.some(b => ballOverlaps(b, c, r, 1))) ghost.cells[c][r].state = 2;
        }
    }
    fillPockets();
    if (bricksLeft <= 0) completeLevel();
}

// A ball touches a ghost: it starts turning solid (finishes when the ball has left it)

function activateGhost(c, r, b) {
    ghost.cells[c][r].state = 2;
    combo++;
    runStats.maxCombo = Math.max(runStats.maxCombo, combo);
    const mult = Math.min(combo, COMBO_MAX);
    addScore(5 * mult * (doubleTimer > 0 ? 2 : 1));
    beep(420 + 45 * (ghost.rows - r), 'ghost');
    spawnParticles(ghostCellX(c) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2, TETRIS_COLORS[r % TETRIS_COLORS.length], 3);
    if (combo >= 3 && combo <= COMBO_MAX) comboShout(combo, ghostCellX(c) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2);
    if (Math.random() < 0.03) spawnPowerup(ghostCellX(c) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2);
    if (explosiveReady) blastGhost(c, r);
}

// Explosive: instantly solidifies a 3x3 area (and gets used up)

function blastGhost(c, r) {
    explosiveReady = false;
    for (let cc = c - 1; cc <= c + 1; cc++) {
        for (let rr = r - 1; rr <= r + 1; rr++) {
            if (cc >= 0 && cc < BRICK_COLS && rr >= 0 && rr < ghost.rows) {
                const cell = ghost.cells[cc][rr];
                if (cell.state === 1 || cell.state === 2) {
                    // a cell with a ball inside turns solid once the ball has left, like any other
                    cell.state = balls.some(b => ballOverlaps(b, cc, rr, 1)) ? 2 : 3;
                }
            }
        }
    }
    addBlast(ghostCellX(c) + BRICK_W / 2, ghostCellY(r) + BRICK_H / 2);
    boom();
    addShake(8);
    haptic(40, true);
    addPopup(ghostCellX(c) + BRICK_W / 2, ghostCellY(r) - 8, 'SOLID!', '#ff9a2e', { size: 16, life: 0.9 });
    fillPockets();
}


function ghostBallCollision(b) {
    if (!ghost) return;
    let bounced = false;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < ghost.rows; r++) {
            const cell = ghost.cells[c][r];
            if (cell.state === 0 || !ballOverlaps(b, c, r)) continue;
            if (cell.state === 1) {
                activateGhost(c, r, b); // flies straight through
                if (gameState !== 'playing' || !ghost) return; // an Explosive blast can finish the level
            } else if (cell.state === 3 && !bounced && fireTimer <= 0) {
                const x = ghostCellX(c);
                const y = ghostCellY(r);
                const hit = rectContact(b, x, y, BRICK_W, BRICK_H);
                if (hit) bounceOffRect(b, x, y, BRICK_W, BRICK_H, hit);
                beep(240, 'tink');
                bounced = true;
                // A ball bouncing straight up and down between two solid cells (no sideways speed) could be trapped
                // in a one-cell slot forever: give it a little sideways push, keeping its speed
                if (Math.abs(b.vx) < 0.6) {
                    const sp = Math.hypot(b.vx, b.vy);
                    b.vx = (Math.random() < 0.5 ? -1 : 1) * (0.8 + Math.random() * 0.8);
                    b.vy = (b.vy < 0 ? -1 : 1) * Math.sqrt(Math.max(1, sp * sp - b.vx * b.vx));
                }
                if (explosiveReady) {
                    blastGhost(c, r);
                    if (gameState !== 'playing' || !ghost) return;
                }
            }
        }
    }
}


function updateGhostGrid() {
    if (!ghost) return;
    // Watchdog: a ball that has been inside the grid for 5 seconds (cornered in a slot or a sealed pocket) is
    // released below it, so a ghost level can never soft-lock
    const gridTop = ghostCellY(0) - 12;
    const gridBottom = ghostCellY(ghost.rows) + 12;
    for (const b of balls) {
        if (b.y > gridTop && b.y < gridBottom && !b.stuck) {
            if (++b.gridT > 300) {
                b.y = gridBottom + 14;
                b.vy = Math.abs(b.vy) || currentSpeed();
                b.gridT = 0;
                addPopup(b.x, gridBottom + 30, 'FREED', '#aab4c8', { size: 12, life: 0.8 });
            }
        } else {
            b.gridT = 0;
        }
    }
    let changed = false;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < ghost.rows; r++) {
            const cell = ghost.cells[c][r];
            if (cell.dy > 0) cell.dy = Math.max(0, cell.dy - 3);
            if (cell.state === 2 && !balls.some(b => ballOverlaps(b, c, r, 1))) {
                cell.state = 3; // the ball has passed through: now it is solid
                changed = true;
            }
        }
    }
    if (changed) fillPockets();
    for (let i = ghostFlashes.length - 1; i >= 0; i--) {
        if (--ghostFlashes[i].t <= 0) ghostFlashes.splice(i, 1);
    }
    // A finished row waits a moment before it clears: a ball flying up a column finishes several rows in
    // quick succession, and they should clear together (LINE! / DOUBLE! / TRIPLE! / TETRIS!)
    if (completeRows().length) {
        if (!ghost.clearIn) ghost.clearIn = GHOST_CLEAR_DELAY;
        else if (--ghost.clearIn === 0) clearRows(completeRows());
    } else {
        ghost.clearIn = 0;
    }
}

// The guided ball prefers shots that cross ghosts in rows that are nearly complete. Shots are planned with the
// ball's real width (a thin line would happily "thread" gaps the ball actually clips), and it picks at random
// among the near-best shots, so it can never repeat one hopeless shot forever.

function bestAimGhost(x, y) {
    const speed = currentSpeed();
    const rowWeight = r => {
        let n = 0;
        let solid = 0;
        for (let c = 0; c < BRICK_COLS; c++) {
            const st = ghost.cells[c][r].state;
            if (st > 0) n++;
            if (st === 3) solid++;
        }
        return n ? 1 + 4 * (solid / n) * (solid / n) : 0;
    };
    // Would a ball centred here overlap a solid cell?
    const blocked = (px, py) => {
        const c0 = Math.floor((px - BRICK_OFFSET_LEFT) / BRICK_W);
        const r0 = Math.floor((py - BRICK_OFFSET_TOP) / BRICK_H);
        for (let c = c0 - 1; c <= c0 + 1; c++) {
            for (let r = r0 - 1; r <= r0 + 1; r++) {
                if (c < 0 || c >= BRICK_COLS || r < 0 || r >= ghost.rows || ghost.cells[c][r].state !== 3) continue;
                const cx = ghostCellX(c);
                const cy = ghostCellY(r);
                const dx = px - Math.max(cx, Math.min(px, cx + BRICK_W));
                const dy = py - Math.max(cy, Math.min(py, cy + BRICK_H));
                if (dx * dx + dy * dy < (BALL_RADIUS + 1) * (BALL_RADIUS + 1)) return true;
            }
        }
        return false;
    };
    const shots = [];
    for (let deg = -70; deg <= 70; deg += 7) {
        const a = (deg * Math.PI) / 180;
        const dx0 = Math.sin(a);
        const dy0 = -Math.cos(a);
        let dx = dx0;
        let px = x;
        let py = y;
        const seen = new Set();
        let value = 0;
        for (let i = 0; i < 170; i++) {
            px += dx * 5;
            py += dy0 * 5;
            if (px < BALL_RADIUS) {
                px = 2 * BALL_RADIUS - px;
                dx = -dx;
            } else if (px > CANVAS_W - BALL_RADIUS) {
                px = 2 * (CANVAS_W - BALL_RADIUS) - px;
                dx = -dx;
            }
            if (py < 0 || py > CANVAS_H) break;
            if (blocked(px, py)) break; // a solid cell stops the shot
            const c = Math.floor((px - BRICK_OFFSET_LEFT) / BRICK_W);
            const r = Math.floor((py - BRICK_OFFSET_TOP) / BRICK_H);
            if (c < 0 || c >= BRICK_COLS || r < 0 || r >= ghost.rows) continue;
            if (ghost.cells[c][r].state === 1 && !seen.has(c * 100 + r)) {
                seen.add(c * 100 + r);
                value += rowWeight(r);
            }
        }
        value *= 1 - Math.abs(deg) / 400;
        if (value > 0) shots.push({ value, vx: dx0 * speed, vy: dy0 * speed });
    }
    if (!shots.length) return null;
    const top = Math.max(...shots.map(sh => sh.value));
    const good = shots.filter(sh => sh.value >= 0.75 * top);
    const pick = good[Math.floor(Math.random() * good.length)];
    return { vx: pick.vx, vy: pick.vy, ghost: true };
}

// -- drawing --

function drawGhostGrid() {
    if (!ghost) return;
    const now = performance.now();
    // Ghosts: faint, shimmering, with dashed outlines
    ctx.save();
    ctx.strokeStyle = 'rgba(200, 230, 255, 0.4)';
    ctx.lineWidth = 1;
    ctx.setLineDash([3, 3]);
    ctx.beginPath();
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < ghost.rows; r++) {
            const cell = ghost.cells[c][r];
            if (cell.state !== 1) continue;
            const x = ghostCellX(c);
            const y = ghostCellY(r) - cell.dy;
            ctx.globalAlpha = 0.27 + 0.09 * Math.sin(now / 350 + c * 0.7 + r * 0.9);
            ctx.drawImage(brickSprite({ color: TETRIS_COLORS[r % TETRIS_COLORS.length], steel: false, tnt: false }), x, y);
            ctx.rect(x + 0.5, y + 0.5, BRICK_W - 1, BRICK_H - 1);
        }
    }
    ctx.globalAlpha = 0.45;
    ctx.stroke();
    ctx.restore();
    // Arming (the ball is inside) and solid cells
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < ghost.rows; r++) {
            const cell = ghost.cells[c][r];
            if (cell.state < 2) continue;
            const x = ghostCellX(c);
            const y = ghostCellY(r) - cell.dy;
            ctx.drawImage(brickSprite({ color: TETRIS_COLORS[r % TETRIS_COLORS.length], steel: false, tnt: false }), x, y);
            if (cell.state === 2) {
                ctx.fillStyle = 'rgba(255, 255, 255, 0.55)';
                ctx.fillRect(x, y, BRICK_W, BRICK_H);
            }
        }
    }
    // Rows that are finished and about to clear pulse
    if (ghost.clearIn > 0) {
        ctx.fillStyle = 'rgba(255, 255, 255, ' + (0.18 + 0.14 * Math.sin(now / 45)) + ')';
        for (const r of completeRows()) ctx.fillRect(BRICK_OFFSET_LEFT, ghostCellY(r), BRICK_COLS * BRICK_W, BRICK_H);
    }
    // Row-clear flashes
    for (const f of ghostFlashes) {
        ctx.fillStyle = 'rgba(255, 255, 255, ' + (f.t / 14) * 0.85 + ')';
        ctx.fillRect(BRICK_OFFSET_LEFT, f.y, BRICK_COLS * BRICK_W, BRICK_H);
    }
}

// TNT bricks: how many is decided by planLevel(). Placed only where they have neighbours so the blast is
// worth it (never in the top row), seeded per level like the steel clusters. Adjacent TNTs chain.
