// === guided.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function hitValue(c, r) {
    const t = bricks[c][r];
    const worth = q => (q.steel ? (q.hitsLeft > 1 ? 8 : 20) : q.points);
    if (explosiveReady || t.tnt) {
        const { targets, tnt } = collectBlast(c, r, explosiveReady);
        let v = t.tnt ? 20 : 0;
        for (const [tc, tr] of targets) {
            if (bricks[tc][tr].alive) v += worth(bricks[tc][tr]);
        }
        return v + (tnt >= 2 ? 50 * tnt : 0);
    }
    if (fireTimer > 0) {
        // Pierces straight through: everything left in this column counts
        let v = 0;
        for (let rr = 0; rr < BRICK_ROWS; rr++) {
            if (bricks[c][rr].alive) v += worth(bricks[c][rr]);
        }
        return v;
    }
    let v = worth(t);
    for (let cc = c - 1; cc <= c + 1; cc++) {
        for (let rr = r - 1; rr <= r + 1; rr++) {
            if ((cc !== c || rr !== r) && cc >= 0 && cc < BRICK_COLS && rr >= 0 && rr < BRICK_ROWS && bricks[cc][rr].alive) {
                v += 0.25 * worth(bricks[cc][rr]);
            }
        }
    }
    return v;
}

// March a ray from (x, y) along the unit vector (dx, dy), reflecting off the side walls, and return
// the first thing it reaches: an alien ({alien}), a crate, the boss, an alive brick ({c, r}), 'wall' if a
// sliding barrier blocks it, or null.

function castRay(x, y, dx, dy) {
    const step = 5;
    const lo = BALL_RADIUS;
    const hi = CANVAS_W - BALL_RADIUS;
    for (let i = 0; i < 170; i++) {
        x += dx * step;
        y += dy * step;
        if (x < lo) {
            x = 2 * lo - x;
            dx = -dx;
        } else if (x > hi) {
            x = 2 * hi - x;
            dx = -dx;
        }
        if (y < 0 || y > CANVAS_H) return null;
        for (const w of movingWalls) {
            if (x > w.x - 4 && x < w.x + w.w + 4 && y > w.y - 4 && y < w.y + w.h + 4) return 'wall';
        }
        if (bumpers.length && nearBumper(x, y, BALL_RADIUS)) return 'wall'; // it'd glance off somewhere unplanned
        for (const a of aliens) {
            if (a.x > 0 && a.x < CANVAS_W && Math.abs(x - a.x) < a.w / 2 + 4 && Math.abs(y - a.y) < a.h / 2 + 4) return { alien: a, x, y };
        }
        for (const cr of crates) {
            if (cr.alive && x >= cr.x && x <= cr.x + cr.w && y >= cr.y && y <= cr.y + cr.h) return { crate: true };
        }
        if (boss && boss.hp > 0 && boss.intro <= 0 && boss.dying <= 0) {
            for (const [x0, y0, x1, y1] of bossRects()) {
                if (x >= x0 && x <= x1 && y >= y0 && y <= y1) return { boss: true, x, y };
            }
        }
        const c = Math.floor((x - BRICK_OFFSET_LEFT) / BRICK_W);
        const r = Math.floor((y - BRICK_OFFSET_TOP) / BRICK_H);
        if (c >= 0 && c < BRICK_COLS && r >= 0 && r < BRICK_ROWS && bricks[c][r].alive) return { c, r };
    }
    return null;
}

// Sample the upward arc, score what each ray would hit, and return the best shot as
// { vx, vy, c, r } at the current ball speed (null if nothing is hittable).

function bestAim(x, y) {
    if (ghost) return bestAimGhost(x, y);
    const speed = currentSpeed();
    let best = null;
    let bestValue = 0;
    for (let deg = -70; deg <= 70; deg += 7) {
        const a = (deg * Math.PI) / 180;
        const dx = Math.sin(a);
        const dy = -Math.cos(a);
        const hit = castRay(x, y, dx, dy);
        if (!hit || hit === 'wall') continue;
        let value;
        if (hit.alien) {
            value = 120; // the biggest threat on screen: a guided ball goes for the aliens first
        } else if (hit.crate) {
            value = 40; // worth a powerup, but less than hitting the boss
        } else if (hit.boss) {
            value = inBossHatch(hit.x, hit.y) ? 150 : 45; // the hatch is worth triple
        } else {
            value = hitValue(hit.c, hit.r);
        }
        const v = value * (1 - Math.abs(deg) / 400); // slight preference for straighter shots
        if (v > bestValue) {
            bestValue = v;
            best = { vx: dx * speed, vy: dy * speed, c: hit.c, r: hit.r, boss: !!hit.boss, crate: !!hit.crate, alien: hit.alien || null, x: hit.x, y: hit.y };
        }
    }
    return best;
}

// Where a ball leaving the paddle at b goes: the best shot while Guided, else normal paddle steering.
// rect is which paddle half it actually bounced off (see paddleHit in aliens.js) — defaults to the input
// paddle for callers that don't have one (a sticky release always rides that one; see releaseBall below).

function launchVelocity(b, throwVX, rect) {
    if (guidedTimer > 0) {
        const aim = bestAim(b.x, b.y);
        if (aim) return [aim.vx, aim.vy];
    }
    return paddleDeflection(b.x, throwVX, rect);
}

// In flight: every so often re-pick the best shot, and curve toward it at a limited turn rate

function steerGuided(b) {
    if (b.vy >= 0) return; // only while heading up toward the bricks
    if (--b.aimIn <= 0) {
        b.aimIn = 15;
        b.aim = bestAim(b.x, b.y);
    }
    if (!b.aim) return;
    const cur = Math.atan2(b.vy, b.vx);
    const want = Math.atan2(b.aim.vy, b.aim.vx);
    const diff = Math.atan2(Math.sin(want - cur), Math.cos(want - cur)); // shortest signed angle
    const turn = Math.max(-GUIDED_TURN, Math.min(GUIDED_TURN, diff));
    const speed = Math.hypot(b.vx, b.vy);
    b.vx = Math.cos(cur + turn) * speed;
    b.vy = Math.sin(cur + turn) * speed;
}

// Velocity for a ball leaving the paddle at x: steered by where it hits the paddle, plus a little of
// the paddle's own sideways motion (the "throw"). Used by bounces, sticky releases and the aim preview.

function paddleDeflection(x, throwVX, rect) {
    const r = rect || paddle;
    const hitRatio = Math.max(-1, Math.min(1, (x - (r.x + r.w / 2)) / (r.w / 2)));
    const speed = currentSpeed();
    let vx = hitRatio * speed * 0.866;
    let vy = -Math.sqrt(speed * speed - vx * vx);
    if (throwVX !== 0) {
        vx += throwVX * 0.4;
        const mag = Math.hypot(vx, vy);
        const maxSpeed = speed * 1.6;
        if (mag > maxSpeed) {
            vx *= maxSpeed / mag;
            vy *= maxSpeed / mag;
        }
    }
    return [vx, vy];
}

// Sticky paddle: a caught ball rides the paddle (slide the paddle under it to aim) until released

function releaseBall(b) {
    const [vx, vy] = launchVelocity(b, paddleVX);
    b.vx = vx;
    b.vy = vy;
    b.stuck = false;
    b.stuckFor = 0;
    beep(760, 'release');
    haptic(10);
}


function releaseStuckBalls() {
    let released = false;
    for (const b of balls) {
        if (b.stuck) {
            releaseBall(b);
            released = true;
        }
    }
    return released;
}

// Ball speed ramps up each level (capped), plus up to +1.2 within a level as its bricks are cleared
