// === input.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

// Follow mode maps the paddle's whole range onto the thumb pad's width rather than the screen's, so the
// narrower pad brings both walls within reach of one thumb. Touches outside the pad still steer; they just
// clamp at the wall. With no pad on screen (landscape), the full window width is used instead.
function followPaddleTarget(clientX) {
    const pad = document.getElementById('touchpad');
    const r = pad ? pad.getBoundingClientRect() : null;
    const left = r && r.width > 0 ? r.left : 0;
    const width = r && r.width > 0 ? r.width : window.innerWidth;
    const norm = Math.max(0, Math.min(1, ((clientX - left) / width - FOLLOW_INSET) / (1 - 2 * FOLLOW_INSET)));
    let centre = norm * CANVAS_W;
    if (mapMirror()) centre = CANVAS_W - centre;
    return Math.max(0, Math.min(CANVAS_W - paddle.w, centre - paddle.w / 2));
}

// Touches on buttons, the overlay, the codes panel or the how-to-play dialog belong to them: they must
// neither steer the paddle nor count as a "tap anywhere" to launch / resume / restart

function isControlTarget(target) {
    return !!(target && target.closest && target.closest('button, #overlay, a, #found-codes, .modal, #modal-backdrop'));
}

// Displayed pixels -> canvas coordinate space, mirrored when the view is flipped or controls are reversed

function canvasX(clientX) {
    if (!stageEl) stageEl = document.getElementById('stage');
    const rect = stageEl.getBoundingClientRect(); // the stage never gets the flip transform the canvas does
    if (rect.width <= 0) return 0;
    const x = (clientX - rect.left) * (canvas.width / rect.width);
    return mapMirror() ? CANVAS_W - x : x;
}


function requestLock() {
    if (!canvas || !canvas.requestPointerLock) return;
    pointerLockWanted = true;
    try {
        canvas.requestPointerLock();
    } catch (e) {
        // Refused (e.g. no recent gesture); the button/UI just stays unlocked
    }
}


function releaseLock() {
    pointerLockWanted = false;
    try {
        if (document.exitPointerLock) document.exitPointerLock();
    } catch (e) {
        // Ignore
    }
}


// Drops the OS-level lock for an overlay (paused/won/lost/ready) without touching the player's
// pointerLockWanted preference, so the cursor is back to normal for clicking Continue/Resume/etc. and the
// very next click on the canvas re-acquires it automatically. Without this, a locked player who wants to
// click an overlay button has no visible cursor to click with, and their only way out is Esc — which then
// reappears wherever the OS decides to put it, snapping the paddle there the instant they move the mouse.
function suspendLock() {
    if (!pointerLocked) return;
    try {
        if (document.exitPointerLock) document.exitPointerLock();
    } catch (e) {
        // Ignore
    }
}


function toggleLock() {
    if (pointerLocked || pointerLockWanted) releaseLock();
    else requestLock();
}


function setPaddleX(x) {
    if (gameState !== 'ready' && gameState !== 'playing') return;
    followTarget = null; // a direct move (mouse, relative drag) overrides any follow slide
    paddleTargetX = x; // pre-clamp: see the paddle "throw" velocity fixup in fixedStep (main.js)
    paddle.x = Math.max(0, Math.min(x, CANVAS_W - paddle.w));
}


function movePaddleTo(clientX) {
    setPaddleX(canvasX(clientX) - paddle.w / 2);
}

// Pointer-based paddle control.
// Mouse: the paddle follows the cursor. Touch/pen: relative drag. The paddle keeps its offset from
// where the finger landed (no jump, and the finger doesn't cover it), and pointer capture keeps the
// drag alive if the finger slides off the canvas.
// Tap detection: a pointerdown that moves >25px becomes a drag and stops
// counting as a tap. Single tap = launch (restart on game over), double tap = pause.

function handlePointerDown(e) {
    if (e.pointerType === 'mouse') {
        if (e.target !== canvas) return; // a mouse only steers over the game itself
        if (!pointerLocked) movePaddleTo(e.clientX); // once locked, movement is relative (see handlePointerMove)
        if (pointerLockWanted && !pointerLocked) requestLock(); // this click is the gesture the browser requires
    } else {
        if (dragPointerId !== null) return; // ignore extra fingers
        if (isControlTarget(e.target)) return;
        touchDetected = true;
        dragPointerId = e.pointerId;
        lastDragClientX = e.clientX;
        if (touchMode === 'follow') {
            followTarget = followPaddleTarget(e.clientX);
        } else {
            dragOffset = paddle.x - canvasX(e.clientX);
        }
        try {
            e.target.setPointerCapture(e.pointerId);
        } catch (err) {
            // Capture unsupported; touch pointers are captured implicitly anyway
        }
    }
    isTap = true;
    tapStartX = e.clientX;
    tapStartY = e.clientY;
}


function handlePointerMove(e) {
    if (e.pointerType === 'mouse') {
        if (pointerLocked) {
            // Locked: clientX is frozen, so steer from the relative delta instead (reversed controls / a
            // flipped view swap the direction, same as the keyboard)
            const dir = mapMirror() ? -1 : 1;
            const scale = (canvas.width / canvas.getBoundingClientRect().width) * POINTER_LOCK_SENSITIVITY;
            setPaddleX(paddle.x + (e.movementX || 0) * scale * dir);
            return;
        }
        if (e.target !== canvas) return;
        movePaddleTo(e.clientX);
    } else {
        if (e.pointerId !== dragPointerId) return;
        lastDragClientX = e.clientX;
        if (touchMode === 'follow') {
            followTarget = followPaddleTarget(e.clientX);
        } else {
            setPaddleX(canvasX(e.clientX) + dragOffset);
        }
    }
    // Increased tolerance to 25px so natural fingertip touch on mobile doesn't cancel tap
    if (isTap && Math.hypot(e.clientX - tapStartX, e.clientY - tapStartY) > 25) {
        isTap = false; // it's a drag now, not a tap
    }
}


function handlePointerCancel(e) {
    if (e.pointerId === dragPointerId) dragPointerId = null;
    isTap = false;
}


function handlePointerUp(e) {
    if (e && e.pointerType !== 'mouse') {
        if (e.pointerId !== dragPointerId) return;
        dragPointerId = null;
    }
    if (isTap && introHold()) { // a tap skips the level's intro card and starts play
        skipIntroCard();
        isTap = false;
        return;
    }
    // Sticky paddle: a click, a tap, or lifting the finger after a touch drag fires the held ball
    if (gameState === 'playing' && (isTap || (e && e.pointerType !== 'mouse')) && releaseStuckBalls()) {
        lastTapAt = 0;
        isTap = false;
        return;
    }
    if (isTap && !endScreenLocked()) {
        if (gameState === 'lost') {
            resetGame(restartLevel());
            lastTapAt = 0;
        } else if (gameState === 'ready' || gameState === 'won') {
            launchGame();
            lastTapAt = 0;
        } else if (gameState === 'paused') {
            togglePause();
            lastTapAt = 0;
        }
    }
    isTap = false;
}


function handleKeyDown(e) {
    // While a dialog is up, only H, M and Escape work: Space/P/R would act on the game behind it
    if (modalOpen() && !['h', 'H', 'm', 'M', 'Escape'].includes(e.key)) return;
    if (e.key === 'r' || e.key === 'R') {
        // Restart from ready, won, or lost (after a game over, from your furthest unlocked level: see restartLevel)
        if ((gameState === 'ready' || gameState === 'won' || gameState === 'lost') && !endScreenLocked()) {
            resetGame(gameState === 'lost' ? restartLevel() : getStartingLevel());
        }
        return;
    }
    if (e.key === 'p' || e.key === 'P') {
        // Pause / resume
        togglePause();
        return;
    }
    if (e.key === 'm' || e.key === 'M') {
        // Toggle sound / mute
        toggleMute();
        return;
    }
    if (e.key === 'f' || e.key === 'F') {
        // Toggle fullscreen (portrait-locked on phones)
        toggleFullscreen();
        return;
    }
    if (e.key === 'l' || e.key === 'L') {
        // Toggle mouse pointer lock (desktop only; a no-op button is hidden on touch devices)
        toggleLock();
        return;
    }
    if (e.key === 'h' || e.key === 'H') {
        // Toggle the how-to-play / powerup legend dialog
        toggleModal('legend-dialog');
        return;
    }
    if (e.key === 'Escape' && modalOpen()) {
        hideModal();
        return;
    }
    if (e.key === ' ' || e.key === 'Spacebar') {
        // Launch (or continue to next level)
        if ((gameState === 'ready' || gameState === 'won') && !endScreenLocked()) {
            launchGame();
        } else if (introHold()) {
            skipIntroCard();
        } else if (gameState === 'playing') {
            releaseStuckBalls();
        }
        return;
    }
    // Paddle movement (arrows): track held keys; applied each frame in gameLoop
    if (e.key === 'ArrowLeft') {
        keys.left = true;
        followTarget = null;
    } else if (e.key === 'ArrowRight') {
        keys.right = true;
        followTarget = null;
    }
}


function handleKeyUp(e) {
    if (e.key === 'ArrowLeft') {
        keys.left = false;
    } else if (e.key === 'ArrowRight') {
        keys.right = false;
    }
}


// --- Main Execution ---
document.addEventListener('DOMContentLoaded', () => {
    initGame();
    
    // Attach event listeners
    // Window-level so a finger can steer from anywhere on the screen (a mouse still only steers over the canvas)
    window.addEventListener('pointerdown', handlePointerDown);
    window.addEventListener('pointermove', handlePointerMove);
    // Browsers start audio suspended until a gesture; unlock it on the first tap/click/key
    window.addEventListener('pointerdown', ensureAudio);
    window.addEventListener('keydown', ensureAudio);
    window.addEventListener('pointerup', handlePointerUp);
    window.addEventListener('pointercancel', handlePointerCancel);
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp);

    const overlay = document.getElementById('overlay');
    if (overlay) {
        overlay.addEventListener('click', handleOverlayAction);
    }
    const overlayBtn = document.getElementById('overlay-button');
    if (overlayBtn) {
        overlayBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            handleOverlayAction();
        });
    }

    const muteBtn = document.getElementById('mute-btn');
    if (muteBtn) {
        muteBtn.addEventListener('click', () => toggleModal('sound-dialog'));
    }

    const pauseBtn = document.getElementById('pause-btn');
    if (pauseBtn) {
        pauseBtn.addEventListener('click', togglePause);
    }

    const fsBtn = document.getElementById('fullscreen-btn');
    if (fsBtn) {
        fsBtn.addEventListener('click', toggleFullscreen);
    }
    updateFullscreenBtn(); // (hidden when already running installed, fullscreen)
    initRotateHint();
    // Safari can still start a selection from a long press or a double tap despite the CSS; nothing here but
    // the level-code box is text to select
    document.addEventListener('selectstart', e => {
        if (!(e.target instanceof Element) || !e.target.closest('input, textarea')) e.preventDefault();
    });

    // stopPropagation for the same reason as the overlay button: #overlay's own click listener would
    // otherwise treat it as "tap anywhere to play again"
    const shareBtn = document.getElementById('share-btn');
    if (shareBtn) {
        shareBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            shareRun();
        });
    }

    const helpBtn = document.getElementById('help-btn');
    if (helpBtn) {
        helpBtn.addEventListener('click', () => toggleModal('legend-dialog'));
    }
    for (const btn of document.querySelectorAll('.modal-close')) btn.addEventListener('click', hideModal);
    const modalBackdrop = document.getElementById('modal-backdrop');
    if (modalBackdrop) {
        modalBackdrop.addEventListener('click', hideModal);
    }
    initSoundDialog();
    const warpGo = document.getElementById('warp-go');
    if (warpGo) warpGo.addEventListener('click', acceptWarp);
    const warpStay = document.getElementById('warp-stay');
    if (warpStay) warpStay.addEventListener('click', hideModal);

    // Cheat code: toggle/go both need stopPropagation, same reason the overlay-button does — otherwise
    // the click bubbles up to #overlay's own "tap anywhere to launch/continue/restart" listener.
    const codeToggleBtn = document.getElementById('cheat-code-toggle');
    if (codeToggleBtn) {
        codeToggleBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            toggleCheatCodeEntry();
        });
    }
    const codeGoBtn = document.getElementById('level-code-go');
    if (codeGoBtn) {
        codeGoBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            startAtLevelCode();
        });
    }
    const codeInput = document.getElementById('level-code-input');
    if (codeInput) {
        codeInput.addEventListener('click', (e) => e.stopPropagation());
        codeInput.addEventListener('pointerdown', (e) => e.stopPropagation());
        codeInput.addEventListener('input', () => codeInput.classList.remove('shake'));
        codeInput.addEventListener('keydown', (e) => {
            e.stopPropagation(); // don't let R/P/M/F/L/Space/arrows reach the game while typing a code
            if (e.key === 'Enter') startAtLevelCode();
        });
    }

    document.addEventListener('fullscreenchange', () => {
        updateFullscreenBtn();
        if (document.fullscreenElement) {
            lockPortrait();
        } else {
            unlockOrientation();
        }
    });
    document.addEventListener('webkitfullscreenchange', () => {
        updateFullscreenBtn();
        if (document.webkitFullscreenElement) {
            lockPortrait();
        } else {
            unlockOrientation();
        }
    });

    window.addEventListener('touchstart', () => {
        touchDetected = true;
        updateTouchUi();
        const msg = document.getElementById('overlay-message');
        if (gameState === 'ready' && msg && msg.textContent.includes('SPACE')) {
            setOverlayMessage(getLaunchMessage(false));
        }
    }, { once: true, passive: true });
    
    initTouchUi();
    initPointerLock();

    // Start the always-running render loop
    requestAnimationFrame(gameLoop);
});


// A phone turned sideways gets the "turn it back" card (CSS, #rotate-hint in index.html) and the game pauses,
// so the ball doesn't fall through while it's behind the card. Resuming is left to the player.
function initRotateHint() {
    if (!window.matchMedia) return;
    const sideways = window.matchMedia('(orientation: landscape) and (max-height: 500px)');
    const check = () => {
        if (sideways.matches && gameState === 'playing') togglePause();
    };
    if (sideways.addEventListener) sideways.addEventListener('change', check);
    else if (sideways.addListener) sideways.addListener(check); // (older Safari)
    check();
}

function initPointerLock() {
    const btn = document.getElementById('lock-btn');
    if (btn) btn.addEventListener('click', toggleLock);
    document.addEventListener('pointerlockchange', () => {
        pointerLocked = document.pointerLockElement === canvas;
        updateLockUi();
    });
    document.addEventListener('pointerlockerror', () => {
        pointerLocked = false;
        pointerLockWanted = false;
        updateLockUi();
    });
    updateLockUi();
}
