// === level.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function getStartingLevel() {
    try {
        const params = new URLSearchParams(window.location.search);
        const lvl = parseInt(params.get('level'), 10);
        if (!isNaN(lvl) && lvl > 0) {
            return lvl;
        }
    } catch (e) {
        // Fallback to level 1
    }
    return 1;
}

// --- Level codes ---
// The code a player sees and shares is deliberately NOT the level number itself (that would just be
// "type 6 to get level 6" — trivially guessable, and consecutive levels would look obviously related).
// Instead it's a fixed, reversible scramble: multiply the level by a constant that shares no common
// factor with the code space, XOR the result, then show it in base 36. Same level -> same code, always,
// but neighbouring levels produce codes with nothing visibly in common, so nobody can guess their way to
// a level they haven't reached. (The plain ?level=N URL param still works exactly as before, undocumented
// in the UI — that one's for debugging, this is the thing meant to be shared.)
const LEVEL_CODE_CHARS = 4;
const LEVEL_CODE_BASE = 36;
const LEVEL_CODE_SPACE = Math.pow(LEVEL_CODE_BASE, LEVEL_CODE_CHARS); // 1,679,616 - every 4-char code decodes to something
const LEVEL_CODE_CAP = 999; // codes fold into this many playable levels, same ceiling startAtLevelCode used to clamp to
const LEVEL_CODE_MULT = 1048573;  // odd, and its digits don't sum to a multiple of 3 -> coprime with 36^4 = 2^8 x 3^8
const LEVEL_CODE_XOR = 0x5A5A5;   // extra mixing so no residual multiplicative pattern shows through

// Extended Euclidean algorithm: the modular inverse of a, mod m (exists because they're coprime by construction above)
function modInverse(a, m) {
    let oldR = a, r = m;
    let oldS = 1, s = 0;
    while (r !== 0) {
        const q = Math.floor(oldR / r);
        [oldR, r] = [r, oldR - q * r];
        [oldS, s] = [s, oldS - q * s];
    }
    return ((oldS % m) + m) % m;
}
const LEVEL_CODE_MULT_INV = modInverse(LEVEL_CODE_MULT, LEVEL_CODE_SPACE);

function levelToCode(lvl) {
    const x = (((lvl - 1) * LEVEL_CODE_MULT) % LEVEL_CODE_SPACE) ^ LEVEL_CODE_XOR;
    return (x >>> 0).toString(LEVEL_CODE_BASE).toUpperCase().padStart(LEVEL_CODE_CHARS, '0');
}

// Returns a level number for ANY well-formed code (never throws, never out of range) so a mistyped guess
// just lands on some other playable level instead of erroring out; returns null only for junk input.
function codeToLevel(code) {
    const clean = String(code).trim().toUpperCase();
    if (!/^[0-9A-Z]{1,6}$/.test(clean)) return null;
    const parsed = parseInt(clean, LEVEL_CODE_BASE);
    if (isNaN(parsed)) return null;
    const x = (parsed ^ LEVEL_CODE_XOR) >>> 0;
    const raw = (x * LEVEL_CODE_MULT_INV) % LEVEL_CODE_SPACE;
    return (raw % LEVEL_CODE_CAP) + 1;
}


function initGame() {
    // FIX: Correctly target the canvas element ID 'canvas' as per index.html
    canvas = document.getElementById('canvas');
    if (!canvas) {
        console.error("Canvas element with ID 'canvas' not found in the DOM.");
        return;
    }
    canvas.width = CANVAS_W;
    canvas.height = CANVAS_H;
    ctx = canvas.getContext('2d');

    try {
        bestScore = parseInt(localStorage.getItem('breakout-best'), 10) || 0;
    } catch (e) {
        bestScore = 0; // Storage unavailable; best is session-only
    }

    try {
        const saved = JSON.parse(localStorage.getItem('breakout-found-codes'));
        foundCodes = (saved && typeof saved === 'object') ? saved : {};
    } catch (e) {
        foundCodes = {}; // Storage unavailable or corrupt; codes found this session just won't persist
    }
    renderFoundCodesPanel(); // show whatever was already found in earlier sessions right away

    // Initialize game state with optional URL level parameter
    resetGame(getStartingLevel());
}


function resetGame(startLevel = 1) {
    score = 0;
    lives = 3;
    level = startLevel;
    gameState = 'ready';
    runStats = { maxCombo: 0, bricks: 0, aliens: 0, bosses: 0, warps: 0 };
    bestAtStart = bestScore;
    newBestShown = false;

    // Paddle setup
    paddle = {
        x: CANVAS_W / 2 - PADDLE_W / 2,
        y: CANVAS_H - 30,
        w: PADDLE_W,
        h: PADDLE_H
    };

    // Ball setup (multi-ball: starts with a single ball, can split up to 4)
    balls = [makeBall(CANVAS_W / 2, paddle.y - BALL_RADIUS, 5, -5)];

    // Brick setup
    bricks = [];
    for (let c = 0; c < BRICK_COLS; c++) {
        bricks[c] = [];
        for (let r = 0; r < BRICK_ROWS; r++) {
            bricks[c][r] = {
                x: 0,
                y: 0,
                w: BRICK_W,
                h: BRICK_H,
                color: '#0095DD',
                alive: true,
                points: 0,
                steel: false,
                maxHits: 1,
                hitsLeft: 1
            };
        }
    }
    spawnLevel();

    // Clear leftover particles
    particles.length = 0;
    powerups.length = 0;
    clearTimedEffects();
    shield = 0;
    shake = 0;
    combo = 0;
    popups.length = 0;
    blasts.length = 0;
    warpRift = null;
    warpTimer = warpInterval() + 60 * 20; // a fresh run gets ~20s of grace before the first rift can appear

    // Show the launch prompt
    showOverlay(getLaunchMessage(), 'Launch');
}

// --- Level Generation ---
// A level = a layout (which cells hold bricks) + a steel style (which bricks take two hits).
// Layouts repeat every 8 levels and steel styles every 3, so combinations don't repeat for 24 levels.
// Levels 1-5 keep the original layout order.

function currentLayout() {
    return LAYOUTS[(level - 1) % LAYOUTS.length];
}

// --- Steel brick cracks ---
// Procedural and random per hit: 3-4 jagged fissures radiate from where the ball actually struck,
// each with a chance of short offshoots, and every fissure stops when it reaches the brick's edge.
// Stored on the brick as polylines in brick-local coordinates and baked into a sprite by bakeCrack().

function seededRandom(seed) {
    let s = seed >>> 0;
    return function () {
        s = (s + 0x6D2B79F5) >>> 0;
        let t = s;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

// Returns (c, r) => whether that cell is a two-hit steel brick

function buildSteelMask(layout, style) {
    if (style === 'top row') return (c, r) => r === 0;
    if (style === 'diagonal') return (c, r) => (c + r) % 5 === 0;

    // 'clusters': 2x2 steel blocks scattered over cells that actually hold bricks, more of them on later levels
    const rand = seededRandom(level * 7919);
    const marked = new Set();
    const count = Math.min(2 + Math.floor((level - 1) / 3), 5);
    for (let i = 0; i < count; i++) {
        for (let attempt = 0; attempt < 20; attempt++) {
            const c0 = Math.floor(rand() * (BRICK_COLS - 1));
            const r0 = Math.floor(rand() * (BRICK_ROWS - 1));
            const cells = [[c0, r0], [c0 + 1, r0], [c0, r0 + 1], [c0 + 1, r0 + 1]]
                .filter(([c, r]) => layout.alive(c, r));
            if (cells.length >= 2) {
                cells.forEach(([c, r]) => marked.add(c * BRICK_ROWS + r));
                break;
            }
        }
    }
    return (c, r) => marked.has(c * BRICK_ROWS + r);
}

// --- What appears when ---
// Mechanics are introduced gradually, and once unlocked they show up on some levels rather than every
// one. What a level contains is decided per level from a seeded PRNG (so a level always plays the same,
// and ?level=N works); *when* things happen inside a level (alien arrivals, weird events) is random at
// runtime. Tune the whole curve here.

function isBossLevel(l = level) {
    return l % UNLOCK.boss === 0;
}

// Ghost rows: introduced on level 7, then on about 3 levels in 10, never two in a row and never on a boss level.
// (Its own random stream, so it doesn't change what the other features do on any level.)

// Cheat-code bricks get rarer with level: CHEAT_CHANCE_START right when they unlock, decaying toward
// CHEAT_CHANCE_FLOOR (never below it, however high the level climbs) so there's always at least some chance.
function cheatChance(l) {
    const decay = Math.pow(0.97, l - UNLOCK.cheat);
    return CHEAT_CHANCE_FLOOR + (CHEAT_CHANCE_START - CHEAT_CHANCE_FLOOR) * decay;
}

function planLevel(l) {
    const rand = seededRandom(l * 15485863 + 7);
    const p = { boss: isBossLevel(l), tetris: false, tnt: 0, walls: 0, aliens: null, chaos: null, cheat: false };
    if (p.boss) return p; // a boss arena has no bricks, walls or random visitors: the boss brings its own

    if (l >= UNLOCK.tnt) {
        // Introduced with a couple; after that 0 to a few (never many on early levels)
        p.tnt = l === UNLOCK.tnt ? 2 : (rand() < 0.2 ? 0 : 1 + Math.floor(rand() * Math.min(1 + Math.floor(l / 2), 5)));
    }
    if (l >= UNLOCK.walls) {
        p.walls = (l === UNLOCK.walls || rand() < 0.65) ? 1 : 0;
        if (p.walls && l >= 8 && rand() < 0.5) p.walls = 2;
    }
    if (l >= UNLOCK.aliens && (l === UNLOCK.aliens || rand() < Math.min(0.7, 0.4 + 0.04 * (l - UNLOCK.aliens)))) {
        p.aliens = { max: alienMax(l), grace: 10 };
    }
    if (l >= UNLOCK.chaos && (l === UNLOCK.chaos || rand() < Math.min(0.55, 0.3 + 0.04 * (l - UNLOCK.chaos)))) {
        p.chaos = { events: 1 + (l >= 9 && rand() < 0.5 ? 1 : 0) };
    }
    // Whether this level COULD have a cheat-code brick at all — a pure function of the level number, like
    // everything else here. Whether one is actually PLACED also depends on whether you've already found
    // this level's code, which is runtime state, not level-shape: see placeCheatBrick() in spawnLevel().
    p.cheat = l >= UNLOCK.cheat && rand() < cheatChance(l);
    // Ghost rows replace the bricks, so no TNT, sliding walls, or cheat brick on those levels
    if (isGhostLevel(l)) {
        p.tetris = true;
        p.tnt = 0;
        p.walls = 0;
        p.cheat = false;
    }
    return p;
}


function showLevelIntro() {
    if (!introPending) return;
    introPending = false;
    let lines = LEVEL_INTROS[level];
    if (plan.tetris) {
        lines = ghostIntroSeen
            ? ['GHOST ROWS', 'Fill whole rows to clear them']
            : ['GHOST ROWS', 'Fly the ball THROUGH the ghost bricks to make them solid', 'Fill a whole row and it clears, like Tetris'];
        ghostIntroSeen = true;
    }
    if (!lines) return;
    lines.forEach((text, i) => {
        addPopup(CANVAS_W / 2, CANVAS_H * 0.42 + i * 30, text, i === 0 ? '#ffe58a' : '#d8e2ff',
            { size: i === 0 ? 22 : 17, life: 3, rise: 0.15, pop: i === 0 });
    });
}

// Clearing a level (bricks gone, or the boss beaten): on to the next one with a fresh ball

function completeLevel() {
    level++;
    gameState = 'won';
    powerups.length = 0;
    clearTimedEffects();
    combo = 0;
    spawnLevel();
    playWinJingle();
    addShake(6);
    haptic([30, 60, 30, 60, 80], true);
    const sp = currentSpeed();
    balls = [makeBall(paddle.x + paddle.w / 2, paddle.y - BALL_RADIUS, sp, -sp)];
    inputLockUntil = performance.now() + 700;
    showOverlay(getLaunchMessage(true), 'Continue', buildSummary(true));
}

// --- Weird events ---
// Now and then the game does something odd for ~10 seconds, with a 2 second warning first:
//   UPSIDE DOWN (view flips vertically), REVERSED CONTROLS (drag right, paddle goes left),
//   FULL FLIP (view rotates 180 degrees; controls follow what you see) and TIME WARP (turbo or slow-mo).
// Each unlocks at its own level, and a level either has them or not (see planLevel).

function placeTnt() {
    const rand = seededRandom(level * 104729);
    const target = plan.tnt;
    let placed = 0;
    for (let attempt = 0; attempt < 80 && placed < target; attempt++) {
        const c = Math.floor(rand() * BRICK_COLS);
        const r = 1 + Math.floor(rand() * (BRICK_ROWS - 1));
        const cell = bricks[c][r];
        if (!cell.alive || cell.steel || cell.tnt) continue;
        let neighbours = 0;
        for (let cc = c - 1; cc <= c + 1; cc++) {
            for (let rr = r - 1; rr <= r + 1; rr++) {
                if ((cc !== c || rr !== r) && cc >= 0 && cc < BRICK_COLS && rr >= 0 && rr < BRICK_ROWS && bricks[cc][rr].alive) {
                    neighbours++;
                }
            }
        }
        if (neighbours < 3) continue;
        cell.tnt = true;
        cell.points = 25;
        cell.color = TNT_COLOR;
        placed++;
    }
}

// A cheat-code brick: at most one per level, and only if this level's code isn't already found (no point
// placing a second one). No neighbour requirement like TNT has — it doesn't chain, so any live cell works.
function placeCheatBrick() {
    if (!plan.cheat || foundCodes[level]) return;
    const rand = seededRandom(level * 293503 + 11);
    for (let attempt = 0; attempt < 40; attempt++) {
        const c = Math.floor(rand() * BRICK_COLS);
        const r = Math.floor(rand() * BRICK_ROWS);
        const cell = bricks[c][r];
        if (!cell.alive || cell.steel || cell.tnt) continue;
        cell.cheat = true;
        cell.color = CHEAT_COLOR;
        break;
    }
}

// Sliding barriers: one from level 3, a counter-moving second from level 8; speed ramps and is capped

function buildWalls() {
    const walls = [];
    if (plan.walls >= 1) {
        const y = BRICK_OFFSET_TOP + BRICK_ROWS * BRICK_H + 35; // floats below the brick grid
        const speed = Math.min(2.2 + (level - 3) * 0.5, 6.5);
        walls.push({ x: CANVAS_W / 2 - 60, y: y, w: 120, h: 14, vx: speed, hits: 0 });
        if (plan.walls >= 2) {
            walls.push({ x: 60, y: y + 50, w: 90, h: 14, vx: -speed, hits: 0 });
        }
    }
    return walls;
}


function spawnLevel() {
    plan = planLevel(level);
    boss = null;
    crates = [];
    crateTimer = 0;
    warpRift = null; // any rift belonged to the level just left
    const layout = currentLayout();
    const isSteel = buildSteelMask(layout, STEEL_STYLES[(level - 1) % STEEL_STYLES.length]);

    bricksLeft = 0;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < BRICK_ROWS; r++) {
            const brick = bricks[c][r];
            brick.x = (c * BRICK_W) + BRICK_OFFSET_LEFT;
            brick.y = (r * BRICK_H) + BRICK_OFFSET_TOP;
            brick.alive = !plan.boss && !plan.tetris && layout.alive(c, r); // boss arenas and ghost rows have no ordinary bricks
            brick.tnt = false;
            brick.cheat = false;
            brick.crack = null;
            brick.sprite = null;
            brick.flash = 0;
            if (brick.alive) bricksLeft++;

            if (brick.alive && isSteel(c, r)) {
                // Two-hit steel: first hit cracks it, awards no points
                brick.steel = true;
                brick.maxHits = 2;
                brick.hitsLeft = 2;
                brick.points = 0;
                brick.color = '#71797E'; // Steel gray
            } else {
                brick.steel = false;
                brick.maxHits = 1;
                brick.hitsLeft = 1;
                brick.points = ROW_STYLES[r].points;
                brick.color = ROW_STYLES[r].color;
            }
        }
    }
    placeTnt();
    placeCheatBrick();
    ghost = plan.tetris ? buildGhostGrid(level) : null;
    ghostFlashes = [];
    if (ghost) bricksLeft = ghostCount();
    levelBricksTotal = bricksLeft;
    resetAliens(plan.aliens ? plan.aliens.grace : 999, 8); // no aliens carry over; a grace period before the first
    initChaos();
    if (plan.boss) spawnBoss();
    introPending = true;

    movingWalls = buildWalls();
    buildBackground();
}


function makeBall(x, y, vx, vy) {
    return {
        x, y, r: BALL_RADIUS, vx, vy, trail: [], stuck: false, stuckFor: 0, aim: null, aimIn: 0, gridT: 0,
        onWallRef: null, // which moving wall (if any) the ball is currently resting against
        rallyLast: null, rallyStreak: 0, rallyDistinct: null, rallyT: 0, rallyAllShown: false // ping-pong rally
    };
}

// --- Ping-pong rallies ---
// Bouncing the ball off DIFFERENT solid surfaces (the paddle and any moving walls) back and forth in quick
// succession is a real rally: alternate fast enough and it's called out, with a growing score bonus. Using
// every surface currently in play in one streak (only possible from level 8, with two moving walls) is the
// big version.

function currentSpeed() {
    const base = Math.min(5 + (level - 1) * 0.4, 8);
    const progress = levelBricksTotal > 0 ? 1 - bricksLeft / levelBricksTotal : (boss ? 1 - boss.hp / boss.maxHp : 0);
    const cleared = Math.max(0, Math.min(1, progress));
    return base + 1.2 * cleared;
}

// --- Ambience: level-tinted gradient backdrop with slow parallax stars ---

function buildBackground() {
    const hue = plan.boss ? 350 : (235 + (level - 1) * 28) % 360;
    bgGradient = ctx.createLinearGradient(0, 0, 0, CANVAS_H);
    bgGradient.addColorStop(0, 'hsl(' + hue + ', 55%, 5%)');
    bgGradient.addColorStop(1, 'hsl(' + ((hue + 30) % 360) + ', 60%, 17%)');
}


function drawBackground() {
    ctx.fillStyle = bgGradient;
    ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
    const parallax = paddle ? (paddle.x + paddle.w / 2 - CANVAS_W / 2) * 0.04 : 0;
    // Stars in three depth layers: one path and one fill per layer (was one state change + fill per star),
    // with a shared twinkle per layer
    ctx.fillStyle = '#cfd8ff';
    const twinkle = performance.now() / 700;
    for (let layer = 0; layer < STAR_LAYERS; layer++) {
        ctx.globalAlpha = (0.25 + 0.55 * (layer + 0.5) / STAR_LAYERS) * (0.7 + 0.3 * Math.sin(twinkle + layer * 2.1));
        ctx.beginPath();
        for (const s of stars) {
            if (s.layer !== layer) continue;
            s.y += (0.06 + s.z * 0.3) * timeScale; // the stars are a speedometer
            if (s.y > CANVAS_H) {
                s.y = 0;
                s.x = Math.random() * CANVAS_W;
            }
            const x =(((s.x - parallax * s.z) % CANVAS_W) + CANVAS_W) % CANVAS_W;
            const size = 0.7 + s.z * 1.5;
            ctx.rect(x, s.y, size, size);
        }
        ctx.fill();
    }
    ctx.globalAlpha = 1;
}

