// === level.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

// A cheat code shared as a link (?code=XXXX — see shareCheatCode in share.js), decoded to its level
function sharedCodeLevel() {
    try {
        const code = new URLSearchParams(window.location.search).get('code');
        return code ? codeToLevel(code) : null;
    } catch (e) {
        return null;
    }
}

function getStartingLevel() {
    const shared = sharedCodeLevel();
    if (shared !== null) return shared;
    try {
        const params = new URLSearchParams(window.location.search);
        const lvl = parseInt(params.get('level'), 10);
        if (!isNaN(lvl) && lvl > 0) {
            return lvl;
        }
    } catch (e) {
        // Fallback to level 1
    }
    return 1;
}

// Where a new run starts after a game over: the level you died on if you've found its cheat code, else the
// nearest earlier level you have one for, else the usual start (level 1, or what the URL asks for)
function restartLevel() {
    const unlocked = Object.keys(foundCodes).map(Number).filter(l => l <= level);
    return unlocked.length ? Math.max(...unlocked) : getStartingLevel();
}

// --- Level codes ---
// The code a player sees and shares is deliberately NOT the level number itself (that would just be
// "type 6 to get level 6" — trivially guessable, and consecutive levels would look obviously related).
// Instead it's a fixed, reversible scramble: multiply the level by a constant that shares no common
// factor with the code space, XOR the result, then show it in base 36. Same level -> same code, always,
// but neighbouring levels produce codes with nothing visibly in common, so nobody can guess their way to
// a level they haven't reached. (The plain ?level=N URL param still works exactly as before, undocumented
// in the UI — that one's for debugging, this is the thing meant to be shared.)
const LEVEL_CODE_CHARS = 4;
const LEVEL_CODE_BASE = 36;
const LEVEL_CODE_SPACE = Math.pow(LEVEL_CODE_BASE, LEVEL_CODE_CHARS); // 1,679,616 - every 4-char code decodes to something
const LEVEL_CODE_CAP = 999; // codes fold into this many playable levels, same ceiling startAtLevelCode used to clamp to
const LEVEL_CODE_MULT = 1048573;  // odd, and its digits don't sum to a multiple of 3 -> coprime with 36^4 = 2^8 x 3^8
const LEVEL_CODE_XOR = 0x5A5A5;   // extra mixing so no residual multiplicative pattern shows through

// Extended Euclidean algorithm: the modular inverse of a, mod m (exists because they're coprime by construction above)
function modInverse(a, m) {
    let oldR = a, r = m;
    let oldS = 1, s = 0;
    while (r !== 0) {
        const q = Math.floor(oldR / r);
        [oldR, r] = [r, oldR - q * r];
        [oldS, s] = [s, oldS - q * s];
    }
    return ((oldS % m) + m) % m;
}
const LEVEL_CODE_MULT_INV = modInverse(LEVEL_CODE_MULT, LEVEL_CODE_SPACE);

function levelToCode(lvl) {
    const x = (((lvl - 1) * LEVEL_CODE_MULT) % LEVEL_CODE_SPACE) ^ LEVEL_CODE_XOR;
    return (x >>> 0).toString(LEVEL_CODE_BASE).toUpperCase().padStart(LEVEL_CODE_CHARS, '0');
}

// Returns a level number for ANY well-formed code (never throws, never out of range) so a mistyped guess
// just lands on some other playable level instead of erroring out; returns null only for junk input.
function codeToLevel(code) {
    const clean = String(code).trim().toUpperCase();
    if (!/^[0-9A-Z]{1,6}$/.test(clean)) return null;
    const parsed = parseInt(clean, LEVEL_CODE_BASE);
    if (isNaN(parsed)) return null;
    const x = (parsed ^ LEVEL_CODE_XOR) >>> 0;
    const raw = (x * LEVEL_CODE_MULT_INV) % LEVEL_CODE_SPACE;
    return (raw % LEVEL_CODE_CAP) + 1;
}


function initGame() {
    // FIX: Correctly target the canvas element ID 'canvas' as per index.html
    canvas = document.getElementById('canvas');
    if (!canvas) {
        console.error("Canvas element with ID 'canvas' not found in the DOM.");
        return;
    }
    canvas.width = CANVAS_W;
    canvas.height = CANVAS_H;
    ctx = canvas.getContext('2d');

    try {
        bestScore = parseInt(localStorage.getItem('breakout-best'), 10) || 0;
    } catch (e) {
        bestScore = 0; // Storage unavailable; best is session-only
    }

    try {
        const saved = JSON.parse(localStorage.getItem('breakout-found-codes'));
        foundCodes = (saved && typeof saved === 'object') ? saved : {};
    } catch (e) {
        foundCodes = {}; // Storage unavailable or corrupt; codes found this session just won't persist
    }
    // Levels 1-5 became the tutorial, moving every earlier level 5 up: codes found before that move with
    // their levels (a code is derived from its level number, so each one is re-derived)
    try {
        if (!localStorage.getItem('breakout-levels-v2')) {
            const moved = {};
            for (const l of Object.keys(foundCodes)) moved[+l + TUTORIAL_LEVELS] = levelToCode(+l + TUTORIAL_LEVELS);
            foundCodes = moved;
            saveFoundCodes();
            localStorage.setItem('breakout-levels-v2', '1');
        }
    } catch (e) {
        // Storage unavailable: nothing saved to move
    }
    // Arrived through a friend's shared code link: it joins your own collection, like typing it in would
    const shared = sharedCodeLevel();
    const sharedIsNew = shared !== null && !foundCodes[shared];
    if (sharedIsNew) {
        foundCodes[shared] = levelToCode(shared);
        saveFoundCodes();
    }
    renderFoundCodesPanel(sharedIsNew ? foundCodes[shared] : undefined); // show earlier sessions' finds right away

    // Initialize game state with optional URL level parameter
    resetGame(getStartingLevel());
}


function resetGame(startLevel = 1) {
    score = 0;
    lives = 3;
    level = startLevel;
    gameState = 'ready';
    runStats = { maxCombo: 0, bricks: 0, aliens: 0, bosses: 0, warps: 0 };
    bestAtStart = bestScore;
    newBestShown = false;
    resetMoments();
    introCard = null;

    // Paddle setup
    paddle = {
        x: CANVAS_W / 2 - PADDLE_W / 2,
        y: CANVAS_H - 30,
        w: PADDLE_W,
        h: PADDLE_H
    };

    // Ball setup (multi-ball: starts with a single ball, can split up to 4)
    balls = [makeBall(CANVAS_W / 2, paddle.y - BALL_RADIUS, 5, -5)];

    // Brick setup
    bricks = [];
    for (let c = 0; c < BRICK_COLS; c++) {
        bricks[c] = [];
        for (let r = 0; r < BRICK_ROWS; r++) {
            bricks[c][r] = {
                x: 0,
                y: 0,
                w: BRICK_W,
                h: BRICK_H,
                color: '#0095DD',
                alive: true,
                points: 0,
                steel: false,
                maxHits: 1,
                hitsLeft: 1
            };
        }
    }
    spawnLevel();

    // Clear leftover particles
    particles.length = 0;
    powerups.length = 0;
    clearTimedEffects();
    shield = 0;
    shake = 0;
    combo = 0;
    popups.length = 0;
    blasts.length = 0;
    warpRift = null;
    warpTimer = warpInterval() + 60 * 20; // a fresh run gets ~20s of grace before the first rift can appear

    // Show the launch prompt
    showOverlay(getLaunchMessage(), 'Launch');
}

// --- Level Generation ---
// A level = a layout (which cells hold bricks) + a steel style (which bricks take two hits).
// The first LAYOUT_FIXED levels after the tutorial play the original eight layouts in order; after that every
// block of LAYOUTS.length levels deals each layout once, shuffled (see currentLayout). Steel styles cycle every 3.
const LAYOUT_FIXED = 8;

function currentLayout() {
    if (isTutorial()) return TUTORIAL[level - 1];
    const s = curveLevel();
    if (s <= LAYOUT_FIXED) return LAYOUTS[s - 1];
    // After the fixed opening run, the brick levels (boss and ghost levels have no layout) are dealt the
    // layouts from a seeded, shuffled deck: every layout once per LAYOUTS.length brick levels. A plain cycle
    // by level number kept boss and ghost levels landing on the same layouts' turns, so some layouts could
    // go 50+ levels without ever showing up.
    const n = brickLevelsBefore(level);
    const block = Math.floor(n / LAYOUTS.length);
    const deck = LAYOUTS.map((_, i) => i);
    const rand = seededRandom(block * 2654435761 + 97);
    for (let i = deck.length - 1; i > 0; i--) {
        const j = Math.floor(rand() * (i + 1));
        [deck[i], deck[j]] = [deck[j], deck[i]];
    }
    return LAYOUTS[deck[n % LAYOUTS.length]];
}

// How many brick levels (not a boss, ghost rows or a maze) come after the fixed opening run and before level l
const brickLevelCounts = {};
function brickLevelsBefore(l) {
    const first = TUTORIAL_LEVELS + LAYOUT_FIXED + 1;
    if (l <= first) return 0;
    // Counted up in a loop from the highest level already known (recursing down from ?level=200000 blew the stack)
    let known = l;
    while (known > first && brickLevelCounts[known] === undefined) known--;
    let count = known > first ? brickLevelCounts[known] : 0;
    for (let n = known + 1; n <= l; n++) {
        const prev = n - 1;
        count += isBossLevel(prev) || isGhostLevel(prev) || isMazeLevel(prev) ? 0 : 1;
        brickLevelCounts[n] = count;
    }
    return count;
}

// Small seeded PRNG (mulberry32) so a given level always generates the same layout, also for ?level=N

function seededRandom(seed) {
    let s = seed >>> 0;
    return function () {
        s = (s + 0x6D2B79F5) >>> 0;
        let t = s;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

// Returns (c, r) => whether that cell is a two-hit steel brick

function buildSteelMask(layout, style) {
    if (style === 'top row') return (c, r) => r === 0;
    if (style === 'diagonal') return (c, r) => (c + r) % 5 === 0;

    // 'clusters': 2x2 steel blocks scattered over cells that actually hold bricks, more of them on later levels
    const rand = seededRandom(level * 7919);
    const marked = new Set();
    const count = Math.min(2 + Math.floor((curveLevel() - 1) / 3), 5);
    for (let i = 0; i < count; i++) {
        for (let attempt = 0; attempt < 20; attempt++) {
            const c0 = Math.floor(rand() * (BRICK_COLS - 1));
            const r0 = Math.floor(rand() * (BRICK_ROWS - 1));
            const cells = [[c0, r0], [c0 + 1, r0], [c0, r0 + 1], [c0 + 1, r0 + 1]]
                .filter(([c, r]) => layout.alive(c, r));
            if (cells.length >= 2) {
                cells.forEach(([c, r]) => marked.add(c * BRICK_ROWS + r));
                break;
            }
        }
    }
    return (c, r) => marked.has(c * BRICK_ROWS + r);
}

// --- What appears when ---
// Mechanics are introduced gradually, and once unlocked they show up on some levels rather than every
// one. What a level contains is decided per level from a seeded PRNG (so a level always plays the same,
// and ?level=N works); *when* things happen inside a level (alien arrivals, weird events) is random at
// runtime. Tune the whole curve here.

// Levels 1..TUTORIAL_LEVELS are the tutorial (see TUTORIAL in constants.js); the main game's curve is
// written in its own numbers, and level N after the tutorial plays curve level N - TUTORIAL_LEVELS.
function isTutorial(l = level) {
    return l <= TUTORIAL_LEVELS;
}

// How hard things are (ball speed, alien strength, boss toughness...): the tutorial is the easiest
function curveLevel(l = level) {
    return Math.max(1, l - TUTORIAL_LEVELS);
}

// What's unlocked (drops, weird events, ghost rows...): in the tutorial, what it has shown so far; after it,
// everything it showed, and the main game's later unlocks at their usual curve levels
function unlockLevel(l = level) {
    return isTutorial(l) ? TUTORIAL[l - 1].unlock : Math.max(TUTORIAL[TUTORIAL_LEVELS - 1].unlock, curveLevel(l));
}

function isBossLevel(l = level) {
    return !isTutorial(l) && curveLevel(l) % UNLOCK.boss === 0;
}

// Ghost rows: introduced on level 7, then on about 3 levels in 10, never two in a row and never on a boss level.
// (Its own random stream, so it doesn't change what the other features do on any level.)

// Cheat-code bricks get rarer with level: CHEAT_CHANCE_START right when they unlock, decaying toward
// CHEAT_CHANCE_FLOOR (never below it, however high the level climbs) so there's always at least some chance.
function cheatChance(l = curveLevel()) {
    const decay = Math.pow(0.97, Math.max(0, l - UNLOCK.cheat));
    return CHEAT_CHANCE_FLOOR + (CHEAT_CHANCE_START - CHEAT_CHANCE_FLOOR) * decay;
}

// Beating a boss always earns its level code, handed over with the victory (see winBossLevel in boss.js):
// a boss fight is hard enough to deserve it, and a chance-based capsule could be missed or never drop.

function planLevel(l) {
    const rand = seededRandom(l * 15485863 + 7);
    // Whether this level is old enough to ever have a cheat-code drop at all. The roll itself (and how
    // it's delivered: a gold brick, a ghost row clearing, or a boss nearing defeat) happens at runtime,
    // deliberately NOT seeded like the rest of this plan, so replaying — or reloading the same ?level=N —
    // can go either way each time; see placeCheatBrick, clearRows and maybeDropMazeCheatCapsule. (Beating a boss
    // always earns its code: see winBossLevel.)
    const p = { boss: isBossLevel(l), tetris: false, chain: false, maze: false, tnt: 0, walls: 0, bumpers: 0, aliens: null, chaos: null, cheatEligible: unlockLevel(l) >= UNLOCK.cheat, tutorial: null };
    if (isTutorial(l)) { // exactly what that tutorial level shows, quickly: aliens and events come early
        const t = TUTORIAL[l - 1];
        p.tutorial = t;
        p.tnt = t.tnt || 0;
        p.walls = t.walls || 0;
        p.aliens = t.aliens ? { max: 1, grace: 3 } : null;
        p.chaos = t.chaos ? { events: 1 } : null;
        p.cheatEligible = !!t.code;
        return p;
    }
    if (p.boss) return p; // a boss arena has no bricks, walls or random visitors: the boss brings its own

    // The tutorial has shown TNT, walls, aliens and weird events: from here each is on some levels, more often later
    const s = curveLevel(l);
    p.tnt = rand() < 0.2 ? 0 : 1 + Math.floor(rand() * Math.min(1 + Math.floor(s / 2), 5));
    p.walls = rand() < 0.65 ? 1 : 0;
    if (p.walls && s >= 8 && rand() < 0.5) p.walls = 2;
    if (rand() < Math.min(0.7, 0.4 + 0.04 * Math.max(0, s - UNLOCK.aliens))) {
        p.aliens = { max: alienMax(s), grace: 10 };
    }
    if (rand() < Math.min(0.55, 0.3 + 0.04 * Math.max(0, s - UNLOCK.chaos))) {
        p.chaos = { events: 1 + (s >= 9 && rand() < 0.5 ? 1 : 0) };
    }
    // Pinball bumpers: a sure thing on the level they debut, then on about a third of levels, three of them
    // from curve level 10. (Their own random stream, so adding them didn't change anything else about a level.)
    if (s >= UNLOCK.bumpers && (s === UNLOCK.bumpers || seededRandom(l * 49979687 + 13)() < 0.35)) {
        p.bumpers = s >= 10 ? 3 : 2;
    }
    // Ghost rows replace the bricks, so no TNT, sliding walls or bumpers — but cheatEligible stays: see clearRows()
    // in ghostRows.js for how a ghost level delivers one instead of a gold brick (a roll per row cleared).
    if (isGhostLevel(l)) {
        p.tetris = true;
        p.tnt = 0;
        p.walls = 0;
        p.bumpers = 0;
    }
    // Colour Chain: the colours are the puzzle, so no TNT (sliding walls, bumpers and visitors stay)
    if (isChainLevel(l)) {
        p.chain = true;
        p.tnt = 0;
    }
    // Space Chomp: the maze is the whole level, and its ghosts are the only visitors. No weird events
    // either: against the clock, a speed-up or a flipped screen is just annoying.
    if (isMazeLevel(l)) {
        p.maze = true;
        p.tnt = 0;
        p.walls = 0;
        p.bumpers = 0;
        p.aliens = null;
        p.chaos = null;
    }
    return p;
}


function showLevelIntro() {
    if (!introPending) return;
    introPending = false;
    const intro = LEVEL_INTROS[level];
    let title = intro && intro.title;
    let lines = intro ? intro.lines.slice() : [];
    if (plan.tetris) {
        title = 'GHOST ROWS';
        lines = ghostIntroSeen
            ? ['Fill whole rows to clear them']
            : ['Fly the ball THROUGH ghost bricks to make them solid', 'Fill a whole row and it clears'];
        ghostIntroSeen = true;
    }
    if (plan.maze) {
        title = 'SPACE CHOMP';
        lines = mazeIntroSeen
            ? ['Eat ' + maze.goal + ' dots in time. Hit chompers to ZOOM!']
            : ['The chompers must eat ' + maze.goal + ' dots before time runs out', 'Hit a chomper with the ball and it ZOOMS', 'Bop the ghosts away from them'];
        mazeIntroSeen = true;
    }
    if (plan.chain) {
        title = 'COLOUR CHAIN';
        lines = chainIntroSeen
            ? ['Match your ball\'s colour. Let falling bricks chain']
            : ['Your ball pops bricks of its OWN colour, and every one touching them', 'Other colours repaint the ball. Falling bricks can CHAIN'];
        chainIntroSeen = true;
    }
    if (boss && !bossIntroSeen[boss.kind]) {
        bossIntroSeen[boss.kind] = true;
        title = BOSS_INTROS[boss.kind].title;
        lines = BOSS_INTROS[boss.kind].lines.concat(lines);
    }
    if (!title || !lines.length) return;
    // On a boss level the card sits below the boss's own "A WILD SNAKE APPEARS!" / "BOSS INCOMING!" call-out
    showIntroCard(title, lines, boss ? 370 : 290);
}

// Clearing a level (bricks gone, or the boss beaten): on to the next one with a fresh ball

function completeLevel() {
    const bossBeaten = plan.boss; // read before spawnLevel replaces the plan
    level++;
    gameState = 'won';
    powerups.length = 0;
    clearTimedEffects();
    combo = 0;
    spawnLevel();
    if (bossBeaten) sfxVictory();
    else playWinJingle();
    addShake(6);
    haptic([30, 60, 30, 60, 80], true);
    const sp = currentSpeed();
    balls = [makeBall(paddle.x + paddle.w / 2, paddle.y - BALL_RADIUS, sp, -sp)];
    inputLockUntil = performance.now() + 700;
    showOverlay(getLaunchMessage(true), 'Continue', buildSummary(true));
}

// --- Weird events ---
// Now and then the game does something odd for ~10 seconds, with a 2 second warning first:
//   UPSIDE DOWN (view flips vertically), REVERSED CONTROLS (drag right, paddle goes left),
//   FULL FLIP (view rotates 180 degrees; controls follow what you see) and TIME WARP (turbo or slow-mo).
// Each unlocks at its own level, and a level either has them or not (see planLevel).

function placeTnt() {
    const rand = seededRandom(level * 104729);
    const target = plan.tnt;
    let placed = 0;
    for (let attempt = 0; attempt < 80 && placed < target; attempt++) {
        const c = Math.floor(rand() * BRICK_COLS);
        const r = 1 + Math.floor(rand() * (BRICK_ROWS - 1));
        const cell = bricks[c][r];
        if (!cell.alive || cell.steel || cell.tnt) continue;
        let neighbours = 0;
        for (let cc = c - 1; cc <= c + 1; cc++) {
            for (let rr = r - 1; rr <= r + 1; rr++) {
                if ((cc !== c || rr !== r) && cc >= 0 && cc < BRICK_COLS && rr >= 0 && rr < BRICK_ROWS && bricks[cc][rr].alive) {
                    neighbours++;
                }
            }
        }
        if (neighbours < 3) continue;
        cell.tnt = true;
        cell.points = 25;
        cell.color = TNT_COLOR;
        placed++;
    }
}

// A cheat-code brick: at most one per level. Eligibility (boss/ghost-row levels never get one) comes from
// the level's shape, but the chance itself is rolled fresh right here, every time the level is entered —
// not baked into the deterministic plan — so reloading the same ?level=N can go either way, same as a
// natural replay. It's also NOT gated on whether you've already found this level's code: the game restarts
// from level 1 every run, so that would permanently sterilize any level you'd ever cracked before —
// catching an already-known one just pays out in score instead (see revealLevelCode). No neighbour
// requirement like TNT has — it doesn't chain, so any live cell works.
function placeCheatBrick() {
    if (!plan.cheatEligible) return;
    if (!plan.tutorial && Math.random() >= cheatChance()) return; // the tutorial's code level always has one
    const rand = seededRandom(level * 293503 + 11);
    for (let attempt = 0; attempt < 40; attempt++) {
        const c = Math.floor(rand() * BRICK_COLS);
        const r = Math.floor(rand() * BRICK_ROWS);
        const cell = bricks[c][r];
        if (!cell.alive || cell.steel || cell.tnt) continue;
        cell.cheat = true;
        cell.color = CHEAT_COLOR;
        break;
    }
}

// Sliding barriers: one from level 3, a counter-moving second from level 8; speed ramps and is capped

function buildWalls() {
    const walls = [];
    if (plan.walls >= 1) {
        const y = BRICK_OFFSET_TOP + BRICK_ROWS * BRICK_H + 35; // floats below the brick grid
        const speed = Math.min(2.2 + Math.max(0, curveLevel() - 3) * 0.5, 6.5);
        walls.push({ x: CANVAS_W / 2 - 60, y: y, w: 120, h: 14, vx: speed, hits: 0 });
        if (plan.walls >= 2) {
            walls.push({ x: 60, y: y + 50, w: 90, h: 14, vx: -speed, hits: 0 });
        }
    }
    return walls;
}


function spawnLevel() {
    plan = planLevel(level);
    boss = null;
    crates = [];
    crateTimer = 0;
    warpRift = null; // any rift belonged to the level just left
    portals = null;
    portalTimer = 60 * (12 + Math.random() * 10); // the first pair of a level opens 12-22s in
    movingWalls = buildWalls(); // built before spawnBoss() so the snake boss can add its own wall to it
    bumpers = buildBumpers();
    const layout = currentLayout();
    const isSteel = plan.chain ? () => false : plan.tutorial
        ? (c, r) => !!(plan.tutorial.steel && plan.tutorial.steel(c, r))
        : buildSteelMask(layout, STEEL_STYLES[(curveLevel() - 1) % STEEL_STYLES.length]);

    bricksLeft = 0;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < BRICK_ROWS; r++) {
            const brick = bricks[c][r];
            brick.x = (c * BRICK_W) + BRICK_OFFSET_LEFT;
            brick.y = (r * BRICK_H) + BRICK_OFFSET_TOP;
            brick.alive = !plan.boss && !plan.tetris && !plan.maze && layout.alive(c, r); // boss arenas and ghost rows have no ordinary bricks
            brick.tnt = false;
            brick.cheat = false;
            brick.crack = null;
            brick.sprite = null;
            brick.flash = 0;
            brick.dy = 0;
            brick.chainColor = undefined;
            if (brick.alive) bricksLeft++;

            if (brick.alive && isSteel(c, r)) {
                // Two-hit steel: first hit cracks it, awards no points
                brick.steel = true;
                brick.maxHits = 2;
                brick.hitsLeft = 2;
                brick.points = 0;
                brick.color = '#71797E'; // Steel gray
            } else {
                brick.steel = false;
                brick.maxHits = 1;
                brick.hitsLeft = 1;
                brick.points = ROW_STYLES[r].points;
                brick.color = ROW_STYLES[r].color;
            }
        }
    }
    placeTnt();
    placeCheatBrick();
    if (plan.chain) paintChainBricks();
    ghost = plan.tetris ? buildGhostGrid(level) : null;
    ghostFlashes = [];
    if (ghost) bricksLeft = ghostCount();
    maze = null;
    if (plan.maze) bricksLeft = buildMaze(); // (its dots are the level's "bricks")
    levelBricksTotal = bricksLeft;
    resetAliens(plan.aliens ? plan.aliens.grace : 999, 8); // no aliens carry over; a grace period before the first
    initChaos();
    if (plan.boss) spawnBoss();
    introPending = true;

    buildBackground();
}


function makeBall(x, y, vx, vy) {
    return {
        x, y, r: BALL_RADIUS, vx, vy, trail: [], stuck: false, stuckFor: 0, aim: null, aimIn: 0, gridT: 0,
        onWallRef: null, // which moving wall (if any) the ball is currently resting against
        rallyLast: null, rallyStreak: 0, rallyDistinct: null, rallyT: 0, rallyAllShown: false // ping-pong rally
    };
}

// --- Ping-pong rallies ---
// Bouncing the ball off DIFFERENT solid surfaces (the paddle and any moving walls) back and forth in quick
// succession is a real rally: alternate fast enough and it's called out, with a growing score bonus. Using
// every surface currently in play in one streak (only possible from level 8, with two moving walls) is the
// big version.

function currentSpeed() {
    const base = Math.min(5 + (curveLevel() - 1) * 0.4, 8);
    let progress = 0;
    if (levelBricksTotal > 0) progress = 1 - bricksLeft / levelBricksTotal;
    else if (boss && boss.kind === 'snake') progress = 1 - boss.segments.length / boss.startLength;
    else if (boss) progress = 1 - boss.hp / boss.maxHp;
    const cleared = Math.max(0, Math.min(1, progress));
    return base + 1.2 * cleared;
}

// --- Ambience: level-tinted gradient backdrop with slow parallax stars ---

function buildBackground() {
    const hue = plan.boss ? 350 : (235 + (level - 1) * 28) % 360;
    bgGradient = ctx.createLinearGradient(0, 0, 0, CANVAS_H);
    bgGradient.addColorStop(0, 'hsl(' + hue + ', 55%, 5%)');
    bgGradient.addColorStop(1, 'hsl(' + ((hue + 30) % 360) + ', 60%, 17%)');
}


function updateStars() {
    for (const s of stars) {
        s.y += (0.06 + s.z * 0.3) * timeScale; // the stars are a speedometer
        if (s.y > CANVAS_H) {
            s.y = 0;
            s.x = Math.random() * CANVAS_W;
        }
    }
}

function drawBackground() {
    ctx.fillStyle = bgGradient;
    ctx.fillRect(0, 0, CANVAS_W, CANVAS_H);
    const parallax = paddle ? (paddle.x + paddle.w / 2 - CANVAS_W / 2) * 0.04 : 0;
    // Stars in three depth layers: one path and one fill per layer (was one state change + fill per star),
    // with a shared twinkle per layer
    ctx.fillStyle = '#cfd8ff';
    const twinkle = performance.now() / 700;
    for (let layer = 0; layer < STAR_LAYERS; layer++) {
        ctx.globalAlpha = (0.25 + 0.55 * (layer + 0.5) / STAR_LAYERS) * (0.7 + 0.3 * Math.sin(twinkle + layer * 2.1));
        ctx.beginPath();
        for (const s of stars) {
            if (s.layer !== layer) continue;
            const x =(((s.x - parallax * s.z) % CANVAS_W) + CANVAS_W) % CANVAS_W;
            const size = 0.7 + s.z * 1.5;
            ctx.rect(x, s.y, size, size);
        }
        ctx.fill();
    }
    ctx.globalAlpha = 1;
}

