// === main.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function drawStuckAim(b) {
    const [vx, vy] = launchVelocity(b, 0);
    const speed = Math.hypot(vx, vy);
    ctx.save();
    ctx.fillStyle = '#c6ff6a';
    for (let d = 26; d <= 190; d += 18) {
        ctx.globalAlpha = 0.85 - d / 260;
        ctx.beginPath();
        ctx.arc(b.x + (vx / speed) * d, b.y + (vy / speed) * d, 2.5, 0, Math.PI * 2);
        ctx.fill();
    }
    ctx.globalAlpha = 0.9;
    ctx.strokeStyle = '#c6ff6a';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(b.x, b.y, b.r + 5, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * (1 - b.stuckFor / STICKY_MAX_FRAMES));
    ctx.stroke();
    ctx.restore();
}

// Ball look by state: a fire ball burns orange, a guided ball glows violet, otherwise hot pink

function drawReticleAt(cx, cy) {
    const spin = performance.now() / 500;
    const pulse = 13 + Math.sin(performance.now() / 120) * 2;
    ctx.save();
    ctx.strokeStyle = '#c9a0ff';
    ctx.lineWidth = 2;
    ctx.globalAlpha = 0.9;
    ctx.beginPath();
    ctx.arc(cx, cy, pulse, 0, Math.PI * 2);
    ctx.stroke();
    ctx.beginPath();
    for (let i = 0; i < 4; i++) {
        const a = spin + (i * Math.PI) / 2;
        ctx.moveTo(cx + Math.cos(a) * (pulse - 4), cy + Math.sin(a) * (pulse - 4));
        ctx.lineTo(cx + Math.cos(a) * (pulse + 6), cy + Math.sin(a) * (pulse + 6));
    }
    ctx.stroke();
    ctx.restore();
}

// Ball glow sprites per look (trail blob, halo, body), built once on first use. Nothing here creates a
// gradient per frame: a 4-ball fire scene used to build ~70 gradients every frame, which is a lot of
// garbage for a phone to collect.

function drawBall() {
    const name = fireTimer > 0 ? 'fire' : guidedTimer > 0 ? 'guided' : 'normal';
    const look = BALL_LOOKS[name];
    const sp = ballSpriteSet(name);
    const hooks = boss && bossHooks();
    for (const b of balls) {
        if (b.stuck) drawStuckAim(b);
        if (hooks && hooks.drawBall && hooks.drawBall(b)) continue; // a boss can dress the ball up (Kong's hammer)
        if (guidedTimer > 0 && b.aim) {
            if (b.aim.alien) {
                if (aliens.includes(b.aim.alien)) drawReticleAt(b.aim.alien.x, b.aim.alien.y);
            } else if (b.aim.boss) {
                if (boss && boss.hp > 0) {
                    const core = boss.kind === 'mothership' ? bossCore() : b.aim; // the hatch, or wherever it's aiming
                    drawReticleAt(core.x, core.y);
                }
            } else if (b.aim.c !== undefined && bricks[b.aim.c][b.aim.r].alive) {
                const t = bricks[b.aim.c][b.aim.r];
                drawReticleAt(t.x + t.w / 2, t.y + t.h / 2);
            }
        }
        // Glowing trail: additive blending so overlapping ghosts brighten into a comet tail
        if (b.trail && b.trail.length) {
            ctx.save();
            ctx.globalCompositeOperation = 'lighter';
            for (let t = 0; t < b.trail.length; t++) {
                const tr = b.trail[t];
                const ratio = (t + 1) / b.trail.length;
                const rad = b.r * (0.4 + look.trailGrow * ratio);
                ctx.globalAlpha = look.trailA * ratio;
                ctx.drawImage(sp.blob, tr.x - rad, tr.y - rad, rad * 2, rad * 2);
            }
            ctx.restore();
        }
        ctx.drawImage(sp.halo, b.x - sp.haloSize / 2, b.y - sp.haloSize / 2);
        ctx.drawImage(sp.body, b.x - sp.bodySize / 2, b.y - sp.bodySize / 2);
    }
}


function drawMovingWalls() {
    for (const wall of movingWalls) {
        ctx.save();
        ctx.fillStyle = "rgba(0, 229, 255, 0.25)"; // glow underlay
        ctx.fillRect(wall.x - 3, wall.y - 3, wall.w + 6, wall.h + 6);
        ctx.fillStyle = "#00ffff";
        ctx.fillRect(wall.x, wall.y, wall.w, wall.h);

        // Subtle hazard striped pattern overlay
        ctx.fillStyle = "rgba(0, 0, 0, 0.25)";
        for (let x = wall.x; x < wall.x + wall.w; x += 16) {
            ctx.fillRect(x, wall.y, 8, wall.h);
        }
        ctx.restore();
    }
}

// The shield is a glowing line along the bottom edge that saves one missed ball

function drawShield() {
    if (shield <= 0) return;
    // Shields compound: the line reads thicker and brighter the more misses are banked
    const stacks = Math.min(shield, SHIELD_MAX);
    ctx.save();
    ctx.strokeStyle = '#33ddff';
    ctx.globalAlpha = 0.7 + 0.3 * Math.sin(performance.now() / 150);
    ctx.beginPath();
    ctx.moveTo(0, CANVAS_H - 2);
    ctx.lineTo(CANVAS_W, CANVAS_H - 2);
    ctx.lineWidth = 3 + (stacks - 1);
    ctx.stroke();
    ctx.globalAlpha *= 0.3; // wide faint stroke as the glow
    ctx.lineWidth = 9 + (stacks - 1) * 2;
    ctx.stroke();
    ctx.restore();
    if (shield > 1) {
        ctx.save();
        ctx.font = termFont(18);
        ctx.textAlign = 'center';
        // A cyan outline for the glow: a canvas shadowBlur costs a blur pass on every frame
        ctx.strokeStyle = 'rgba(51, 221, 255, 0.55)';
        ctx.lineWidth = 3;
        ctx.lineJoin = 'round';
        ctx.strokeText('×' + shield, CANVAS_W / 2, CANVAS_H - 8);
        ctx.fillStyle = '#dffcff';
        ctx.fillText('×' + shield, CANVAS_W / 2, CANVAS_H - 8);
        ctx.restore();
    }
}

// --- Brick sprites ---
// A brick's beveled look (fill, four bevel polygons, sheen, outline, steel border, TNT stripes and
// label) is drawn once into a small offscreen canvas per look and reused with drawImage. Drawing ~10
// paths per brick per frame added up on phones. A crack is baked into its own sprite when it happens.
// Only the genuinely animated bits (TNT pulse, impact flash) are drawn live.

function drawBricks() {
    const pulse = 'rgba(255, 90, 0, ' + (0.15 + 0.15 * Math.sin(performance.now() / 180)) + ')';
    const cheatPulse = 'rgba(255, 220, 120, ' + (0.2 + 0.2 * Math.sin(performance.now() / 260)) + ')';
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < BRICK_ROWS; r++) {
            const brick = bricks[c][r];
            if (!brick.alive) continue;
            const { x, w, h } = brick;
            const y = brick.dy ? brick.y - brick.dy : brick.y; // (a Colour Chain brick sliding down into place)
            ctx.drawImage(brick.sprite || brickSprite(brick), x, y);

            if (brick.tnt) {
                // Pulsing glow so TNT reads as live
                ctx.fillStyle = pulse;
                ctx.fillRect(x + 3, y + 3, w - 6, h - 6);
            }
            if (brick.cheat) {
                // A slower, gentler golden shimmer — inviting rather than hazardous
                ctx.fillStyle = cheatPulse;
                ctx.fillRect(x + 3, y + 3, w - 6, h - 6);
            }
            // Brief white flash on impact (a steel brick cracking; counted down in tickFx)
            if (brick.flash > 0) {
                ctx.fillStyle = 'rgba(255, 255, 255, ' + (brick.flash / 6) * 0.6 + ')';
                ctx.fillRect(x, y, w, h);
            }
        }
    }
}

// Active effects as small chips in the empty strip above the bricks

function drawStatusChips() {
    const chips = [];
    if (slowTimer > 0) chips.push({ text: 'SLOW ' + Math.ceil(slowTimer), color: '#cc33cc' });
    if (wideTimer > 0) chips.push({ text: 'WIDE ' + Math.ceil(wideTimer), color: '#ff9900' });
    if (narrowTimer > 0) chips.push({ text: 'SHRUNK ' + Math.ceil(narrowTimer), color: SNAKE_POISON_COLOR });
    if (splitTimer > 0) chips.push({ text: 'SPLIT ' + Math.ceil(splitTimer), color: '#14e6b4' });
    if (doubleTimer > 0) chips.push({ text: '2× SCORE ' + Math.ceil(doubleTimer), color: '#e6b800' });
    if (fireTimer > 0) chips.push({ text: 'FIRE ' + Math.ceil(fireTimer), color: '#ff6a00' });
    if (guidedTimer > 0) chips.push({ text: 'GUIDED ' + Math.ceil(guidedTimer), color: '#a06cff' });
    if (stickyCatches > 0) chips.push({ text: 'STICKY ×' + stickyCatches, color: '#7cb518' });
    if (shield > 0) chips.push({ text: 'SHIELD ×' + shield, color: '#33ddff' });
    if (explosiveReady) chips.push({ text: 'BOOM READY', color: '#ff3366' });
    if (multiReady) chips.push({ text: 'MULTI READY', color: '#3399ff' });
    if (boss && bossHooks().chips) chips.push(...bossHooks().chips()); // a boss's own timers (Kong's HAMMER)
    if (!chips.length) return;

    ctx.save();
    ctx.font = termFont(18);
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    let x = 10;
    for (const chip of chips) {
        const w = ctx.measureText(chip.text).width + 16;
        ctx.beginPath();
        ctx.rect(x + 0.5, 10.5, w, 20); // square-cornered, like the page's HUD readouts
        ctx.globalAlpha = 0.25;
        ctx.fillStyle = chip.color;
        ctx.fill();
        ctx.globalAlpha = 1;
        ctx.strokeStyle = chip.color;
        ctx.lineWidth = 1;
        ctx.stroke();
        ctx.fillStyle = '#ffffff';
        ctx.fillText(chip.text, x + 8, 21);
        x += w + 6;
    }
    ctx.restore();
}

// Losing a life: the last ball dropping, or (in the asteroid field) a key falling past the paddle. Any
// balls still in play go with it: it's either a fresh ball on the paddle, or game over.
function loseLife() {
    balls.length = 0;
    lives = Math.max(0, lives - 1);
    combo = 0;
    // Drops go with the ball, except a level-code capsule: those are rare enough that losing one to an
    // unrelated miss would sting. It hangs where it is while the ball waits, and falls on after the relaunch.
    keepWhere(powerups, p => p.type === 'cheatcode');
    clearTimedEffects();
    // Aliens and an active weird event (mirrored view, reversed controls, ...) survive a lost ball: a
    // surprise event is often what causes the ball to be lost in the first place, and cutting it short
    // right then would mean never really getting to react to it
    bossBreather();
    mazeBreather(); // the ghosts go back to their pen
    addShake(7);
    haptic(70, true);
    if (lives === 0) {
        gameState = 'lost';
        playLoseJingle();
        haptic(250, true);
        inputLockUntil = performance.now() + 700;
        const summary = buildSummary(false);
        const from = restartLevel();
        showOverlay('Game over\nTap or press R to play again' + (from > 1 ? ' from level ' + from : ''), 'Play again', summary);
        prepareShareCard(summary);
    } else {
        balls.push(makeBall(paddle.x + paddle.w / 2, paddle.y - BALL_RADIUS, currentSpeed(), -currentSpeed()));
        gameState = 'ready';
        showOverlay(getLaunchMessage(false), 'Launch');
    }
}

// --- HUD (DOM) ---
// Only touch the DOM when a value changes; this runs every frame.

// An arcade "ship" in the page's synthwave palette: a chrome body with a cyan neon strip down the middle
// and magenta end caps, square-cornered like the rest of the retro UI. Every segment gets caps, so a
// paddle split by alien-shot holes reads as separate broken pieces.
function drawPaddleSlab(x, y, w, h) {
    ctx.globalAlpha = 0.22; // glow underlay
    ctx.fillStyle = '#2de2e6';
    ctx.fillRect(x - 3, y - 3, w + 6, h + 6);
    ctx.globalAlpha = 1;
    if (!paddleGradient) { // the paddle's y never changes, so one pair of gradients serves every frame
        paddleGradient = ctx.createLinearGradient(0, paddle.y, 0, paddle.y + paddle.h);
        paddleGradient.addColorStop(0, '#f4fbff');
        paddleGradient.addColorStop(0.35, '#a9d8ee');
        paddleGradient.addColorStop(0.65, '#4a86a8');
        paddleGradient.addColorStop(1, '#1d3550');
        paddleCapGradient = ctx.createLinearGradient(0, paddle.y, 0, paddle.y + paddle.h);
        paddleCapGradient.addColorStop(0, '#ffc2ea');
        paddleCapGradient.addColorStop(0.4, '#ff2fb4');
        paddleCapGradient.addColorStop(1, '#8a0d5f');
    }
    ctx.fillStyle = paddleGradient;
    ctx.fillRect(x, y, w, h);
    const cap = Math.min(10, Math.floor(w / 4));
    ctx.fillStyle = paddleCapGradient;
    ctx.fillRect(x, y, cap, h);
    ctx.fillRect(x + w - cap, y, cap, h);
    ctx.fillStyle = 'rgba(0, 0, 0, 0.4)'; // seams between the caps and the body
    ctx.fillRect(x + cap, y, 1, h);
    ctx.fillRect(x + w - cap - 1, y, 1, h);
    const strip = w - 2 * cap - 8;
    if (strip > 4) {
        ctx.fillStyle = '#2de2e6';
        ctx.fillRect(x + cap + 4, y + Math.floor(h / 2) - 1, strip, 2);
    }
}

function drawPaddle() {
    ctx.save();
    for (const [a, b] of paddleSegments()) {
        drawPaddleSlab(a, paddle.y, b - a, paddle.h);
    }
    // Molten notches on the torn edges of each hole; they blink cyan just before the hole repairs
    for (const h of paddleHoles) {
        const repairing = h.life < 1.2 && Math.floor(h.life * 8) % 2 === 0;
        ctx.fillStyle = repairing ? '#7fe9ff' : '#ff8a2a';
        const x0 = paddle.x + h.x - h.w / 2;
        const x1 = paddle.x + h.x + h.w / 2;
        for (let i = 0; i < 3; i++) {
            const len = 2 + ((i * 7 + Math.floor(h.x)) % 3);
            ctx.fillRect(x0 - len, paddle.y + 1 + i * 4, len, 2);
            ctx.fillRect(x1, paddle.y + 1 + i * 4, len, 2);
        }
    }
    // Split Paddle's mirrored half — a plain reflection, so it's always whole (no holes of its own)
    const m = mirrorPaddleRect();
    if (m) drawPaddleSlab(m.x, m.y, m.w, m.h);
    ctx.restore();
}

// Every brick caught by one hit: the brick itself, its 3x3 neighbours if the Explosive powerup is
// armed, and, recursively, the 3x3 around any TNT brick caught in the blast (chain reaction).
// Returns the targets plus the ring centres (armed hit + each TNT) for the shockwave effect.

function collectBlast(c, r, armed) {
    const targets = [[c, r]];
    const seen = new Set([c * BRICK_ROWS + r]);
    const centers = [];
    const addAround = (bc, br) => {
        for (let cc = bc - 1; cc <= bc + 1; cc++) {
            for (let rr = br - 1; rr <= br + 1; rr++) {
                if (cc < 0 || cc >= BRICK_COLS || rr < 0 || rr >= BRICK_ROWS) continue;
                const key = cc * BRICK_ROWS + rr;
                if (!seen.has(key)) {
                    seen.add(key);
                    targets.push([cc, rr]);
                }
            }
        }
    };
    if (armed) {
        addAround(c, r);
        centers.push(bricks[c][r]);
    }
    let tnt = 0;
    for (let i = 0; i < targets.length; i++) { // targets grows as TNT bricks are found
        const t = bricks[targets[i][0]][targets[i][1]];
        if (t.alive && t.tnt) {
            tnt++;
            centers.push(t);
            addAround(targets[i][0], targets[i][1]);
        }
    }
    return { targets, tnt, centers };
}


// Ball vs the brick grid. Only the few cells under the ball can touch it, so only those are tested (the
// bricks never leave their grid cells). A normal ball hits ONE brick per step, the one it is deepest into:
// it used to take every brick it touched and flip its direction once for each, so a ball striking the seam
// between two bricks flipped twice (i.e. not at all) and ploughed on into the next row. A fire ball
// pierces, so it takes all of them.
function collisionDetection(b) {
    const onFire = fireTimer > 0;
    const c0 = Math.max(0, Math.floor((b.x - b.r - BRICK_OFFSET_LEFT) / BRICK_W));
    const c1 = Math.min(BRICK_COLS - 1, Math.floor((b.x + b.r - BRICK_OFFSET_LEFT) / BRICK_W));
    const r0 = Math.max(0, Math.floor((b.y - b.r - BRICK_OFFSET_TOP) / BRICK_H));
    const r1 = Math.min(BRICK_ROWS - 1, Math.floor((b.y + b.r - BRICK_OFFSET_TOP) / BRICK_H));
    let best = null;
    for (let c = c0; c <= c1; c++) {
        for (let r = r0; r <= r1; r++) {
            const brick = bricks[c][r];
            if (!brick.alive) continue;
            const hit = rectContact(b, brick.x, brick.y, brick.w, brick.h);
            if (!hit) continue;
            if (onFire) {
                hitBrick(b, c, r, hit, true);
                if (gameState !== 'playing') return;
            } else if (!best || hit.d2 < best.hit.d2) {
                best = { c, r, hit };
            }
        }
    }
    if (best) hitBrick(b, best.c, best.r, best.hit, false);
}

function hitBrick(b, c, r, hit, onFire) {
    if (plan.chain && chainBallHit(b, c, r, hit)) return; // Colour Chain's own rules (see colourChain.js)
    const brick = bricks[c][r];
    // Check if hit brick is a two-hit steel brick with hits left
    const wasExplosive = explosiveReady;
    explosiveReady = false;

    // If it's a steel brick with 2 hits left and NOT hit by explosive burst or a fire ball:
    // First hit cracks it, does not destroy it, awards 0 points
    if (brick.steel && brick.hitsLeft > 1 && !wasExplosive && !onFire) {
        brick.hitsLeft--;
        brick.crack = makeCrack(brick, b.x, b.y);
        bakeCrack(brick);
        brick.flash = 6;
        clink();
        addShake(2);
        haptic(12);
        spawnParticles(b.x, b.y, '#B0C4DE');
        addPopup(brick.x + brick.w / 2, brick.y + brick.h / 2, 'CRACK!', '#E0E0E0', { life: 0.8 });
        // Rebound, pushed clear: left overlapping, a fast ball was still inside on the next step and
        // broke the brick it had only just cracked
        bounceOffRect(b, brick.x, brick.y, brick.w, brick.h, hit);
        return;
    }

    // Brick destruction (1-hit brick, cracked steel second hit, fire ball, explosive, or TNT)
    const { targets, tnt, centers } = collectBlast(c, r, wasExplosive);
    const wasBlast = wasExplosive || tnt > 0;
    for (const center of centers) {
        addBlast(center.x + center.w / 2, center.y + center.h / 2);
    }

    // Combo: bricks broken in a row since the last paddle bounce,
    // multiplier capped at x5 (applied to every brick in the burst)
    combo++;
    runStats.maxCombo = Math.max(runStats.maxCombo, combo);
    const mult = Math.min(combo, COMBO_MAX);
    const scoreMult = doubleTimer > 0 ? 2 : 1;
    let totalEarned = 0;
    let destroyed = 0;
    let cheatBrickAt = null; // centre of a cheat-code brick caught in this hit, if any
    for (const [tc, tr] of targets) {
        const t = bricks[tc][tr];
        if (!t.alive) continue;
        if (t.cheat) cheatBrickAt = { x: t.x + t.w / 2, y: t.y + t.h / 2 };
        t.alive = false;
        destroyed++;
        totalEarned += t.points * mult * scoreMult;
        spawnParticles(t.x + t.w / 2, t.y + t.h / 2, t.color);
    }
    // Chain bonus: 2+ TNT bricks going off together
    const chainBonus = tnt >= 2 ? 50 * tnt * scoreMult : 0;
    totalEarned += chainBonus;
    bricksLeft -= destroyed;
    runStats.bricks += destroyed;
    if (destroyed >= 8) noteMoment(25 + Math.min(destroyed, 30), 'MEGA BLAST!');
    addScore(totalEarned);

    // Floating score popup at the break point
    const tags = [];
    if (wasBlast) tags.push('boom');
    if (mult > 1) tags.push('x' + mult);
    if (scoreMult > 1) tags.push('2x');
    const popupText = brick.steel
        ? 'BROKEN!'
        : '+' + totalEarned + (tags.length ? ' (' + tags.join(' · ') + ')' : '');
    const popupX = brick.x + brick.w / 2;
    const popupY = brick.y + brick.h / 2;
    addPopup(popupX, popupY, popupText,
        brick.steel ? '#B0C4DE' : (mult > 1 ? '#FFD700' : '#FFFFFF'));

    // Combo call-out when the multiplier climbs to x3, x4, x5
    if (combo >= 3 && combo <= COMBO_MAX) comboShout(combo, popupX, popupY);

    // TNT chain call-out
    if (tnt >= 2) {
        addPopup(Math.max(80, Math.min(popupX, CANVAS_W - 80)), popupY - 44,
            'CHAIN x' + tnt + '!  +' + chainBonus, '#FF8C1A', { size: 26, life: 1.4, rise: 0.7, pop: true });
    }

    // Screen shake: light per brick (heavier deeper in a combo), big for explosions
    addShake(wasBlast ? Math.min(12 + 2 * (tnt - 1), 16) : brick.steel ? 3 : 1.5 + mult * 0.4);
    if (wasBlast) haptic(tnt >= 2 ? [40, 30, 60] : 45, true);
    else haptic(brick.steel ? 15 : 8);

    // A fire ball pierces straight through: no speed-up, no bounce
    if (!onFire) {
        // Slightly speed up, then re-normalize to keep magnitude sane
        const speed = Math.hypot(b.vx, b.vy);
        const newSpeed = Math.min(speed * 1.02, 10);
        const factor = newSpeed / speed;
        b.vx *= factor;
        b.vy *= factor;
        bounceOffRect(b, brick.x, brick.y, brick.w, brick.h, hit);
    }

    if (wasBlast) {
        boom(tnt >= 2); // a TNT chain gets the big, rumbling version
    } else if (brick.steel) {
        clink();
    } else {
        beep();
    }

    // A cheat-code brick guarantees its own capsule instead of the normal powerup roll —
    // one special, unmistakable drop rather than competing with the ordinary ones
    if (cheatBrickAt) {
        if (bricksLeft <= 0) {
            // This was the level's last brick: the capsule would never get a chance to fall
            // before completeLevel() clears it, so award the code directly instead
            revealLevelCode();
        } else {
            spawnCheatCapsule(cheatBrickAt.x, cheatBrickAt.y);
        }
    } else if (Math.random() < POWERUP_CHANCE) {
        spawnPowerup(brick.x + brick.w / 2, brick.y + brick.h / 2);
    }

    if (plan.chain && bricksLeft > 0) settleChain(); // Fire and Explosive leave gaps for the wall to fall into

    // Check for win condition
    if (bricksLeft <= 0) completeLevel();
}


function restorePaddleWidth() {
    paddle.w = PADDLE_W;
    paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
}

// --- Game Logic Update ---

function update() {
    // 0. Update sliding barrier / moving wall (level 3+)
    for (const wall of movingWalls) {
        wall.x += wall.vx * timeScale;
        if (wall.x <= 0) {
            wall.x = 0;
            wall.vx *= -1;
        } else if (wall.x + wall.w >= CANVAS_W) {
            wall.x = CANVAS_W - wall.w;
            wall.vx *= -1;
        }
    }

    // 1. Move each ball
    for (let i = balls.length - 1; i >= 0; i--) {
        const b = balls[i];

        // Sticky: a caught ball keeps its x (slide the paddle under it to aim), clamped onto the paddle
        if (b.stuck) {
            b.x = Math.max(paddle.x + b.r, Math.min(b.x, paddle.x + paddle.w - b.r));
            b.y = paddle.y - b.r;
            b.trail.length = 0;
            if (++b.stuckFor >= STICKY_MAX_FRAMES) releaseBall(b);
            continue;
        }

        if (b.rallyT <= RALLY_WINDOW_FRAMES) b.rallyT++; // a rally that's timed out just stays timed out

        // Update ball trail (store previous positions)
        if (!b.trail) b.trail = [];
        b.trail.push({ x: b.x, y: b.y });
        if (b.trail.length > 12) {
            b.trail.shift();
        }

        if (guidedTimer > 0) steerGuided(b);
        b.x += b.vx * timeScale; // Time Warp: the world moves faster/slower, your paddle does not
        b.y += b.vy * timeScale;

        // 2. Wall collisions
        if (b.x + b.r > CANVAS_W) {
            b.x = CANVAS_W - b.r;
            b.vx *= -1;
        } else if (b.x - b.r < 0) {
            b.x = b.r;
            b.vx *= -1;
        }
        if (b.y - b.r < 0) {
            // Top wall bounce
            b.y = b.r;
            b.vy *= -1;
        }

        // 2a. Moving wall collision (circle vs AABB)
        let touchingWall = null;
        for (const wall of movingWalls) {
            const hit = rectContact(b, wall.x, wall.y, wall.w, wall.h);
            if (hit) {
                // Rebound off the wall and push the ball out of it. Without the push-out, a wall
                // sweeping into the ball (or a slow ball riding it) stays overlapped and re-triggers
                // the sound and particles every frame.
                bounceOffRect(b, wall.x, wall.y, wall.w, wall.h, hit);
                // Effects only on new contact; a wall carrying the ball, or already-touched-this-frame,
                // stays "in contact" (tracks WHICH wall so two walls close together are told apart)
                if (b.onWallRef !== wall) {
                    beep(580, 'wall');
                    spawnParticles(b.x, b.y, '#00ffff', 5);
                    registerRallyTouch(b, wall);
                    wall.hits++;
                    // The first hit just bounces; from the second hit on, a wall can drop a powerup too
                    if (wall.hits > 1 && Math.random() < POWERUP_CHANCE) {
                        spawnPowerup(b.x, b.y);
                    }
                }
                touchingWall = wall;
            }
        }
        b.onWallRef = touchingWall;

        // 2b. Paddle bounce: circle vs AABB test, only while moving down
        if (b.vy > 0) {
            // Solid parts only: a ball over an alien-shot hole falls straight through. While Split Paddle
            // is active this also checks the mirrored half, and steers off whichever one was actually hit.
            const hit = paddleHit(b.x, b.y, b.r);
            if (hit) {
                // Snap the ball to the top of the paddle (both halves share the same y)
                b.y = paddle.y - b.r;
                // Classic paddle bounce logic (steer)
                [b.vx, b.vy] = launchVelocity(b, hit.vx, hit);
                b.aim = null;
                b.aimIn = 0;
                beep(660, 'paddle');
                combo = 0;
                // The mirror counts as its own rally surface — bouncing between your two Split Paddle
                // halves builds a ping-pong streak just like bouncing off a wall does.
                registerRallyTouch(b, hit.mirror ? 'paddleMirror' : 'paddle');
                if (stickyCatches > 0) {
                    // Sticky paddle: catch the ball instead of bouncing it
                    stickyCatches--;
                    b.stuck = true;
                    b.stuckFor = 0;
                    b.vx = 0;
                    b.vy = 0;
                    addPopup(paddle.x + paddle.w / 2, paddle.y - 34,
                        isTouchDevice() ? 'Tap to release' : 'Click or Space to release',
                        '#c6ff6a', { life: 1.6, size: 14, rise: 0.2 });
                    haptic(10);
                } else if (multiReady) {
                    // Multi-ball split: the "multi" powerup causes this ball to split on the next paddle bounce
                    multiReady = false;
                    if (balls.length < 4) {
                        const mag = Math.hypot(b.vx, b.vy);
                        const f = 0.7 * mag;
                        const twin = makeBall(b.x, b.y, b.vx + f, b.vy);
                        twin.chain = b.chain; // (Colour Chain: the split ball carries the same colour)
                        balls.push(twin);
                    }
                }
            } else if (b.y + b.r > CANVAS_H && (shield > 0 || (boss && boss.dying > 0))) {
                // Shield: shields compound, so this consumes just one banked miss and any others carry over.
                // (While a boss is blowing up you can't lose a life to it: the edge bounces for free.)
                const free = !!(boss && boss.dying > 0);
                if (!free) shield--;
                b.y = CANVAS_H - b.r;
                b.vy = -Math.abs(b.vy);
                for (let x = 0; x < CANVAS_W; x += 60) spawnParticles(x, CANVAS_H - 2, '#33ddff', 3);
                if (!free) addPopup(b.x, CANVAS_H - 40, shield > 0 ? 'Shield saved you! (' + shield + ' left)' : 'Shield saved you! No more shields!', shield > 0 ? '#33ddff' : '#ff9a2e', { life: shield > 0 ? 1.2 : 1.8 });
                addShake(6);
                haptic([20, 40, 20], true);
                tone(300, 0.25, { type: 'sawtooth', vol: 0.2, slideTo: 900 });
            } else if (b.y + b.r > CANVAS_H) {
                // Ball fell past the paddle
                balls.splice(i, 1);
                if (gameState === 'lost') continue; // a second ball falling on the same frame as the last life
                if (balls.length > 0) { // other balls are still in play: just lose this one (a life goes with the LAST ball)
                    addShake(3);
                    haptic(25);
                    continue;
                }
                loseLife();
            }
        }
    }

    // 2c. Active powerup timers (slow affects all balls)
    if (slowTimer > 0) {
        for (const b of balls) {
            const target = currentSpeed() * 0.6;
            const mag = Math.hypot(b.vx, b.vy);
            if (mag > 0) {
                const f = target / mag;
                b.vx *= f;
                b.vy *= f;
            }
        }
        slowTimer -= 1 / 60;
        if (slowTimer <= 0) slowRecover = SLOW_RECOVER_FRAMES;
    } else if (slowRecover > 0) {
        // Slow has run out: bring every ball back up to speed over half a second, wherever it is. Only a
        // paddle bounce used to, and a shallow ball rallying between the walls could stay slow for half a minute.
        slowRecover--;
        const target = currentSpeed();
        for (const b of balls) {
            const mag = Math.hypot(b.vx, b.vy);
            if (b.stuck || mag === 0 || mag >= target) continue; // a faster ball (a smash, say) is left alone
            const f = (mag + (target - mag) / (slowRecover + 1)) / mag;
            b.vx *= f;
            b.vy *= f;
        }
    }
    // Wide, shrunk and split all resize the paddle (only one runs at a time): back to normal when it ends
    if (wideTimer > 0 && (wideTimer -= 1 / 60) <= 0) restorePaddleWidth();
    if (narrowTimer > 0 && (narrowTimer -= 1 / 60) <= 0) restorePaddleWidth();
    if (splitTimer > 0 && (splitTimer -= 1 / 60) <= 0) restorePaddleWidth();
    if (doubleTimer > 0) {
        doubleTimer -= 1 / 60;
    }
    if (guidedTimer > 0) {
        guidedTimer -= 1 / 60;
    }
    if (fireTimer > 0) {
        fireTimer -= 1 / 60;
        // Flames shed off each moving ball
        for (const b of balls) {
            if (!b.stuck && Math.random() < 0.6) {
                spawnParticles(b.x, b.y, Math.random() < 0.5 ? '#ff9a1f' : '#ffd23f', 1);
            }
        }
    }

    // 2d. Falling powerups
    updatePowerups();

    // 2e. Alien invaders, their bolts, and paddle-hole repair
    updateAliens();

    // 2f. Weird events and the boss
    updateChaos();
    updateBoss();
    updateCrates();
    updateWarpRift();
    updatePortals();
    updateMaze();

    // 3. Brick collisions for each ball
    for (const b of balls) {
        if (gameState !== 'playing') break; // a level clear / game over mid-loop ends this frame's collisions
        if (b.stuck) continue;
        collisionDetection(b);
        if (gameState === 'playing') alienBallCollision(b);
        if (gameState === 'playing') bossBallCollision(b);
        if (gameState === 'playing') crateBallCollision(b);
        if (gameState === 'playing') ghostBallCollision(b);
        if (gameState === 'playing') warpRiftBallCollision(b);
        if (gameState === 'playing') portalBallCollision(b);
        if (gameState === 'playing') bumperBallCollision(b);
        if (gameState === 'playing') mazeBallCollision(b);
    }
    if (gameState === 'playing') updateGhostGrid();
}

// Floating popups: drift upward and fade out; "pop" popups punch in from a larger scale

function render() {
    // Defensive: guarantee an identity transform at the start of every frame, so a canvas-state leak
    // anywhere (a stray translate/scale, an unbalanced save/restore) can never carry over and leave the
    // background — or anything after it — painted off to one side on a later frame.
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    // Backdrop stays put while the playfield shakes
    drawBackground();

    ctx.save();
    if (shake > 0) ctx.translate((Math.random() * 2 - 1) * shake, (Math.random() * 2 - 1) * shake); // decays in tickFx
    drawBricks();
    drawGhostGrid();
    drawMaze();
    drawCrates();
    drawWarpRift();
    drawPortals();
    drawMovingWalls();
    drawBumpers();
    drawShield();
    drawBoss();
    drawAliens();
    drawAlienBullets();
    drawIntroCard(); // over the bricks and boss, but under the ball, drops and popups so play stays visible
    drawBall();
    if (plan.chain) drawChainRings();
    drawPaddle();
    drawPowerups();
    drawBlasts();
    drawParticles();
    drawPopups();
    ctx.restore();

    drawTimeWarpFx();
    drawStatusChips();
    drawBossBar();
    drawMazeBar();
    captureMomentIfDue(); // before the perf readout, so it never ends up in a shared screenshot
    if (PERF) drawPerf();
    updateHUD();
    updateTouchpad();
}

// --- Rendering Loop (always runs; physics only while playing) ---

// A mouse/touch-drag paddle snaps straight to the cursor, so it's never rate-limited by anything here —
// but the keyboard's per-step move IS a fixed distance, and the ball's own speed climbs with level and
// with Time Warp's Turbo. Scaling the keyboard step the same way keeps it able to out-run the ball at
// level 20 (or during Turbo) the way it comfortably could at level 1, instead of the ball quietly becoming
// faster than the paddle can ever move and turning the level uncatchable no matter how well you play.
function keyboardStepSpeed() {
    return 10 * (currentSpeed() / 5) * timeScale;
}

// Everything that animates frame by frame (particles, popups, blasts, shake, stars, the intro card, brick
// flashes) advances here, once per simulation step, so it runs at the same speed however often the
// screen is redrawn.
function tickFx() {
    updateStars();
    updateParticles();
    updateBlasts();
    updatePopups();
    updateIntroCard();
    tickBumpers();
    if (plan.chain) tickChainFall();
    shake = shake > 0.3 ? shake * 0.86 : 0;
    for (const col of bricks) for (const brick of col) if (brick.flash > 0) brick.flash--;
    if (boss && bossHooks().tick) bossHooks().tick();
    if (pendingMoment && pendingMoment.delay > 0) pendingMoment.delay--;
}

// --- Smooth motion on any display ---
// The simulation runs at exactly 60 steps a second, but PC monitors refresh at 75, 100, 144, 165 Hz...
// Drawing only after a step left each picture on screen for an uneven time (at 144 Hz alternately 14
// and 21 ms, at 75 Hz every 4th one twice as long): a steady judder. So the game draws on every
// refresh, with moving things placed part-way between where the last step started and ended them.
// Just before each step, snapshotMovers() notes where they are; around a draw, lerpMovers() moves
// them to the in-between position and unlerpMovers() puts them back, so no game code ever sees it.
const interpMovers = [];
const INTERP_MAX_JUMP = 60; // further than this in one step is a teleport (portal, wrap-around): no blend
let paddleStepX = 0;

function snapshotMovers() {
    interpMovers.length = 0;
    const add = o => {
        o._ix = o.x;
        o._iy = o.y;
        interpMovers.push(o);
    };
    if (gameState === 'playing' && !introHold()) for (const b of balls) if (!b.stuck) add(b); // a ball on the paddle rides it exactly
    for (const p of powerups) add(p);
    for (const a of aliens) add(a);
    for (const s of alienBullets) add(s);
    for (const w of movingWalls) add(w);
    if (boss && bossHooks().movers) bossHooks().movers().forEach(add);
    if (maze) {
        maze.ghosts.forEach(add);
        maze.chompers.forEach(add);
    }
    paddleStepX = paddle.x;
}

function lerpAxis(from, to, t) {
    return typeof to === 'number' && Math.abs(to - from) < INTERP_MAX_JUMP ? from + (to - from) * t : to;
}

function lerpMovers(t) {
    for (const o of interpMovers) {
        o._sx = o.x;
        o._sy = o.y;
        o.x = lerpAxis(o._ix, o.x, t);
        if (o._sy !== undefined) o.y = lerpAxis(o._iy, o.y, t); // (the Rival's paddles have no y)
    }
    // The paddle only when the step moves it (keys, touch follow); a mouse or drag sets it directly, and
    // drawing that anywhere but where it is would just add lag
    paddle._sx = paddle.x;
    if (keys.left || keys.right || followTarget !== null) paddle.x = lerpAxis(paddleStepX, paddle.x, t);
}

function unlerpMovers() {
    for (const o of interpMovers) {
        o.x = o._sx;
        if (o._sy !== undefined) o.y = o._sy;
    }
    paddle.x = paddle._sx;
}

function fixedStep() {
    // Track the paddle "throw" velocity per step. Normally this is just paddle.x's own delta, but a fast
    // swipe pushed further into a screen edge than the paddle can follow leaves paddle.x unable to move
    // any further even though the swipe itself hasn't stopped — paddleTargetX (the pre-clamp target; see
    // setPaddleX in input.js) still reflects that real motion, so use its delta instead in that case, or
    // the "slingshot" throw effect quietly dies the instant it's pinned at an edge.
    paddleVX = (paddleTargetX !== paddle.x) ? paddleTargetX - paddleTargetPrevX : paddle.x - paddlePrevX;
    paddlePrevX = paddle.x;
    paddleTargetPrevX = paddleTargetX;
    // Continuous paddle keyboard control (works before launch too)
    if (gameState === 'ready' || gameState === 'playing') {
        if (followTarget !== null) { // touch follow mode: slide toward the finger at a capped speed
            const d = followTarget - paddle.x;
            paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x + Math.max(-FOLLOW_MAX_STEP, Math.min(FOLLOW_MAX_STEP, d))));
            paddleTargetX = paddle.x;
        }
        const dir = mapMirror() ? -1 : 1; // reversed controls / a flipped view swap left and right
        const step = keyboardStepSpeed();
        if (keys.left) paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x - step * dir));
        if (keys.right) paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x + step * dir));
        if (keys.left || keys.right) paddleTargetX = paddle.x;
    }
    // Before launch, and while a level's intro card is up, the ball rides on the paddle
    if (gameState === 'ready' || introHold()) {
        for (const b of balls) {
            b.x = paddle.x + paddle.w / 2;
            b.y = paddle.y - b.r;
            b.trail.length = 0;
        }
    }
    if (gameState === 'playing' && !introHold()) {
        update();
    }
}

// Fixed timestep. All game speeds are per-step, so the simulation must advance at exactly 60 steps
// per second no matter what the display does. Running one step per screen refresh made the game run
// at double speed on 120 Hz screens and in slow motion whenever the refresh rate (variable-refresh
// phones) or the frame rate (a busy device) dropped.

function gameLoop(now) {
    requestAnimationFrame(gameLoop);
    now = now || performance.now();
    if (PERF) perfFrame(now);
    if (!lastFrameTime) lastFrameTime = now;
    let dt = Math.min(now - lastFrameTime, 100); // a long gap (tab switch) is not a backlog
    lastFrameTime = now;
    // Frame times jitter around 16.7 ms on a 60 Hz display: snap those to exactly one step
    if (Math.abs(dt - STEP_MS) < 2) dt = STEP_MS;
    stepAccumulator += dt; // (Time Warp scales movement per step instead, so it is smooth and the paddle stays responsive)

    let steps = 0;
    while (stepAccumulator >= STEP_MS && steps < MAX_STEPS_PER_FRAME) {
        snapshotMovers();
        fixedStep();
        tickFx();
        stepAccumulator -= STEP_MS;
        steps++;
    }
    if (steps === MAX_STEPS_PER_FRAME) stepAccumulator = 0;
    // Draw on every refresh (see snapshotMovers): the leftover time decides how far between the last two
    // steps everything is shown
    const t0 = PERF ? performance.now() : 0;
    lerpMovers(stepAccumulator / STEP_MS);
    render();
    unlerpMovers();
    if (PERF) perfRender(steps, performance.now() - t0);
}

// --- ?perf readout ---

function perfFrame(now) {
    if (perf.last) {
        perf.intervals.push(now - perf.last);
        if (perf.intervals.length > 120) perf.intervals.shift();
    }
    perf.last = now;
}

function perfRender(steps, ms) {
    perf.renderMs = perf.renderMs ? perf.renderMs * 0.9 + ms * 0.1 : ms;
    perf.worstRender = Math.max(ms, perf.worstRender * 0.99);
    perf.maxSteps = Math.max(steps, perf.maxSteps * 0.995);
    if (steps >= MAX_STEPS_PER_FRAME) perf.dropped++;
}

function drawPerf() {
    const iv = perf.intervals;
    if (!iv.length) return;
    const sorted = [...iv].sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    const worst = sorted[sorted.length - 1];
    const lines = [
        'display ' + Math.round(1000 / median) + ' Hz   worst frame ' + Math.round(worst) + ' ms   render ' + perf.renderMs.toFixed(1) + ' ms (max ' + perf.worstRender.toFixed(1) + ')',
        'catch-up steps ' + perf.maxSteps.toFixed(1) + '   dropped ' + perf.dropped + '   balls ' + balls.length + '  particles ' + particles.length +
            '  popups ' + popups.length + '  aliens ' + aliens.length + '  bolts ' + alienBullets.length + '  voices ' + activeVoices
    ];
    ctx.save();
    ctx.font = '11px monospace';
    ctx.textAlign = 'right';
    ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
    ctx.fillRect(CANVAS_W - 560, 4, 556, 36);
    ctx.fillStyle = '#9dffb0';
    ctx.fillText(lines[0], CANVAS_W - 10, 19);
    ctx.fillText(lines[1], CANVAS_W - 10, 34);
    ctx.restore();
}

// --- Event Handlers ---
