// === main.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function drawStuckAim(b) {
    const [vx, vy] = launchVelocity(b, 0);
    const speed = Math.hypot(vx, vy);
    ctx.save();
    ctx.fillStyle = '#c6ff6a';
    for (let d = 26; d <= 190; d += 18) {
        ctx.globalAlpha = 0.85 - d / 260;
        ctx.beginPath();
        ctx.arc(b.x + (vx / speed) * d, b.y + (vy / speed) * d, 2.5, 0, Math.PI * 2);
        ctx.fill();
    }
    ctx.globalAlpha = 0.9;
    ctx.strokeStyle = '#c6ff6a';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(b.x, b.y, b.r + 5, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * (1 - b.stuckFor / STICKY_MAX_FRAMES));
    ctx.stroke();
    ctx.restore();
}

// Ball look by state: a fire ball burns orange, a guided ball glows violet, otherwise red

function drawReticleAt(cx, cy) {
    const spin = performance.now() / 500;
    const pulse = 13 + Math.sin(performance.now() / 120) * 2;
    ctx.save();
    ctx.strokeStyle = '#c9a0ff';
    ctx.lineWidth = 2;
    ctx.globalAlpha = 0.9;
    ctx.beginPath();
    ctx.arc(cx, cy, pulse, 0, Math.PI * 2);
    ctx.stroke();
    ctx.beginPath();
    for (let i = 0; i < 4; i++) {
        const a = spin + (i * Math.PI) / 2;
        ctx.moveTo(cx + Math.cos(a) * (pulse - 4), cy + Math.sin(a) * (pulse - 4));
        ctx.lineTo(cx + Math.cos(a) * (pulse + 6), cy + Math.sin(a) * (pulse + 6));
    }
    ctx.stroke();
    ctx.restore();
}

// Ball glow sprites per look (trail blob, halo, body), built once on first use. Nothing here creates a
// gradient per frame: a 4-ball fire scene used to build ~70 gradients every frame, which is a lot of
// garbage for a phone to collect.

function drawBall() {
    const name = fireTimer > 0 ? 'fire' : guidedTimer > 0 ? 'guided' : 'normal';
    const look = BALL_LOOKS[name];
    const sp = ballSpriteSet(name);
    for (const b of balls) {
        if (b.stuck) drawStuckAim(b);
        if (guidedTimer > 0 && b.aim) {
            if (b.aim.boss) {
                if (boss && boss.hp > 0) {
                    const core = bossCore();
                    drawReticleAt(core.x, core.y);
                }
            } else if (b.aim.c !== undefined && bricks[b.aim.c][b.aim.r].alive) {
                const t = bricks[b.aim.c][b.aim.r];
                drawReticleAt(t.x + t.w / 2, t.y + t.h / 2);
            }
        }
        // Glowing trail: additive blending so overlapping ghosts brighten into a comet tail
        if (b.trail && b.trail.length) {
            ctx.save();
            ctx.globalCompositeOperation = 'lighter';
            for (let t = 0; t < b.trail.length; t++) {
                const tr = b.trail[t];
                const ratio = (t + 1) / b.trail.length;
                const rad = b.r * (0.4 + look.trailGrow * ratio);
                ctx.globalAlpha = look.trailA * ratio;
                ctx.drawImage(sp.blob, tr.x - rad, tr.y - rad, rad * 2, rad * 2);
            }
            ctx.restore();
        }
        ctx.drawImage(sp.halo, b.x - sp.haloSize / 2, b.y - sp.haloSize / 2);
        ctx.drawImage(sp.body, b.x - sp.bodySize / 2, b.y - sp.bodySize / 2);
    }
}


function drawMovingWalls() {
    for (const wall of movingWalls) {
        ctx.save();
        ctx.fillStyle = "rgba(0, 229, 255, 0.25)"; // glow underlay
        ctx.fillRect(wall.x - 3, wall.y - 3, wall.w + 6, wall.h + 6);
        ctx.fillStyle = "#00ffff";
        ctx.fillRect(wall.x, wall.y, wall.w, wall.h);

        // Subtle hazard striped pattern overlay
        ctx.fillStyle = "rgba(0, 0, 0, 0.25)";
        for (let x = wall.x; x < wall.x + wall.w; x += 16) {
            ctx.fillRect(x, wall.y, 8, wall.h);
        }
        ctx.restore();
    }
}

// The shield is a glowing line along the bottom edge that saves one missed ball

function drawShield() {
    if (shield <= 0) return;
    // Shields compound: the line reads thicker and brighter the more misses are banked
    const stacks = Math.min(shield, SHIELD_MAX);
    ctx.save();
    ctx.strokeStyle = '#33ddff';
    ctx.globalAlpha = 0.7 + 0.3 * Math.sin(performance.now() / 150);
    ctx.beginPath();
    ctx.moveTo(0, CANVAS_H - 2);
    ctx.lineTo(CANVAS_W, CANVAS_H - 2);
    ctx.lineWidth = 3 + (stacks - 1);
    ctx.stroke();
    ctx.globalAlpha *= 0.3; // wide faint stroke as the glow
    ctx.lineWidth = 9 + (stacks - 1) * 2;
    ctx.stroke();
    ctx.restore();
    if (shield > 1) {
        ctx.save();
        ctx.font = 'bold 12px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillStyle = '#dffcff';
        ctx.shadowColor = '#33ddff';
        ctx.shadowBlur = 4;
        ctx.fillText('×' + shield, CANVAS_W / 2, CANVAS_H - 8);
        ctx.restore();
    }
}

// --- Brick sprites ---
// A brick's beveled look (fill, four bevel polygons, sheen, outline, steel border, TNT stripes and
// label) is drawn once into a small offscreen canvas per look and reused with drawImage. Drawing ~10
// paths per brick per frame added up on phones. A crack is baked into its own sprite when it happens.
// Only the genuinely animated bits (TNT pulse, impact flash) are drawn live.

function drawBricks() {
    const pulse = 'rgba(255, 90, 0, ' + (0.15 + 0.15 * Math.sin(performance.now() / 180)) + ')';
    const cheatPulse = 'rgba(255, 220, 120, ' + (0.2 + 0.2 * Math.sin(performance.now() / 260)) + ')';
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < BRICK_ROWS; r++) {
            const brick = bricks[c][r];
            if (!brick.alive) continue;
            const { x, y, w, h } = brick;
            ctx.drawImage(brick.sprite || brickSprite(brick), x, y);

            if (brick.tnt) {
                // Pulsing glow so TNT reads as live
                ctx.fillStyle = pulse;
                ctx.fillRect(x + 3, y + 3, w - 6, h - 6);
            }
            if (brick.cheat) {
                // A slower, gentler golden shimmer — inviting rather than hazardous
                ctx.fillStyle = cheatPulse;
                ctx.fillRect(x + 3, y + 3, w - 6, h - 6);
            }
            // Brief white flash on impact (a steel brick cracking)
            if (brick.flash > 0) {
                ctx.fillStyle = 'rgba(255, 255, 255, ' + (brick.flash / 6) * 0.6 + ')';
                ctx.fillRect(x, y, w, h);
                brick.flash--;
            }
        }
    }
}

// Active effects as small chips in the empty strip above the bricks

function drawStatusChips() {
    const chips = [];
    if (slowTimer > 0) chips.push({ text: 'SLOW ' + Math.ceil(slowTimer), color: '#cc33cc' });
    if (wideTimer > 0) chips.push({ text: 'WIDE ' + Math.ceil(wideTimer), color: '#ff9900' });
    if (narrowTimer > 0) chips.push({ text: 'SHRUNK ' + Math.ceil(narrowTimer), color: SNAKE_POISON_COLOR });
    if (doubleTimer > 0) chips.push({ text: '2× SCORE ' + Math.ceil(doubleTimer), color: '#e6b800' });
    if (fireTimer > 0) chips.push({ text: 'FIRE ' + Math.ceil(fireTimer), color: '#ff6a00' });
    if (guidedTimer > 0) chips.push({ text: 'GUIDED ' + Math.ceil(guidedTimer), color: '#a06cff' });
    if (stickyCatches > 0) chips.push({ text: 'STICKY ×' + stickyCatches, color: '#7cb518' });
    if (shield > 0) chips.push({ text: 'SHIELD ×' + shield, color: '#33ddff' });
    if (explosiveReady) chips.push({ text: 'BOOM READY', color: '#ff3366' });
    if (multiReady) chips.push({ text: 'MULTI READY', color: '#3399ff' });
    if (!chips.length) return;

    ctx.save();
    ctx.font = 'bold 12px sans-serif';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'middle';
    let x = 10;
    for (const chip of chips) {
        const w = ctx.measureText(chip.text).width + 16;
        roundRectPath(x, 10, w, 20, 10);
        ctx.globalAlpha = 0.25;
        ctx.fillStyle = chip.color;
        ctx.fill();
        ctx.globalAlpha = 1;
        ctx.strokeStyle = chip.color;
        ctx.lineWidth = 1.5;
        ctx.stroke();
        ctx.fillStyle = '#ffffff';
        ctx.fillText(chip.text, x + 8, 20.5);
        x += w + 6;
    }
    ctx.restore();
}

// --- HUD (DOM) ---
// Only touch the DOM when a value changes; this runs every frame.

function drawPaddle() {
    ctx.save();
    for (const [a, b] of paddleSegments()) {
        ctx.globalAlpha = 0.25; // glow underlay
        ctx.fillStyle = '#0095DD';
        roundRectPath(a - 3, paddle.y - 3, b - a + 6, paddle.h + 6, 8);
        ctx.fill();
        ctx.globalAlpha = 1;
        if (!paddleGradient) { // the paddle's y never changes, so one gradient serves every frame
            paddleGradient = ctx.createLinearGradient(0, paddle.y, 0, paddle.y + paddle.h);
            paddleGradient.addColorStop(0, '#6fd6ff');
            paddleGradient.addColorStop(1, '#0070b0');
        }
        ctx.fillStyle = paddleGradient;
        roundRectPath(a, paddle.y, b - a, paddle.h, 4);
        ctx.fill();
    }
    // Molten notches on the torn edges of each hole; they blink cyan just before the hole repairs
    for (const h of paddleHoles) {
        const repairing = h.life < 1.2 && Math.floor(h.life * 8) % 2 === 0;
        ctx.fillStyle = repairing ? '#7fe9ff' : '#ff8a2a';
        const x0 = paddle.x + h.x - h.w / 2;
        const x1 = paddle.x + h.x + h.w / 2;
        for (let i = 0; i < 3; i++) {
            const len = 2 + ((i * 7 + Math.floor(h.x)) % 3);
            ctx.fillRect(x0 - len, paddle.y + 1 + i * 4, len, 2);
            ctx.fillRect(x1, paddle.y + 1 + i * 4, len, 2);
        }
    }
    ctx.restore();
}

// Every brick caught by one hit: the brick itself, its 3x3 neighbours if the Explosive powerup is
// armed, and, recursively, the 3x3 around any TNT brick caught in the blast (chain reaction).
// Returns the targets plus the ring centres (armed hit + each TNT) for the shockwave effect.

function collectBlast(c, r, armed) {
    const targets = [[c, r]];
    const seen = new Set([c * BRICK_ROWS + r]);
    const centers = [];
    const addAround = (bc, br) => {
        for (let cc = bc - 1; cc <= bc + 1; cc++) {
            for (let rr = br - 1; rr <= br + 1; rr++) {
                if (cc < 0 || cc >= BRICK_COLS || rr < 0 || rr >= BRICK_ROWS) continue;
                const key = cc * BRICK_ROWS + rr;
                if (!seen.has(key)) {
                    seen.add(key);
                    targets.push([cc, rr]);
                }
            }
        }
    };
    if (armed) {
        addAround(c, r);
        centers.push(bricks[c][r]);
    }
    let tnt = 0;
    for (let i = 0; i < targets.length; i++) { // targets grows as TNT bricks are found
        const t = bricks[targets[i][0]][targets[i][1]];
        if (t.alive && t.tnt) {
            tnt++;
            centers.push(t);
            addAround(targets[i][0], targets[i][1]);
        }
    }
    return { targets, tnt, centers };
}


function collisionDetection(b) {
    const onFire = fireTimer > 0;
    for (let c = 0; c < BRICK_COLS; c++) {
        for (let r = 0; r < BRICK_ROWS; r++) {
            const brick = bricks[c][r];
            if (brick.alive) {
                // Circle-AABB test: closest point on the brick's AABB to the ball center
                const cx = Math.max(brick.x, Math.min(b.x, brick.x + brick.w));
                const cy = Math.max(brick.y, Math.min(b.y, brick.y + brick.h));
                const dx = b.x - cx;
                const dy = b.y - cy;
                if (dx * dx + dy * dy < b.r * b.r) {
                    // Check if hit brick is a two-hit steel brick with hits left
                    const wasExplosive = explosiveReady;
                    explosiveReady = false;

                    // If it's a steel brick with 2 hits left and NOT hit by explosive burst or a fire ball:
                    // First hit cracks it, does not destroy it, awards 0 points
                    if (brick.steel && brick.hitsLeft > 1 && !wasExplosive && !onFire) {
                        brick.hitsLeft--;
                        brick.crack = makeCrack(brick, b.x, b.y);
                        bakeCrack(brick);
                        brick.flash = 6;
                        clink();
                        addShake(2);
                        haptic(12);
                        spawnParticles(b.x, b.y, '#B0C4DE');
                        addPopup(brick.x + brick.w / 2, brick.y + brick.h / 2, 'CRACK!', '#E0E0E0', { life: 0.8 });

                        // Rebound ball
                        if (Math.abs(dx) > Math.abs(dy)) {
                            b.vx *= -1;
                        } else {
                            b.vy *= -1;
                        }
                        return;
                    }

                    // Brick destruction (1-hit brick, cracked steel second hit, fire ball, explosive, or TNT)
                    const { targets, tnt, centers } = collectBlast(c, r, wasExplosive);
                    const wasBlast = wasExplosive || tnt > 0;
                    for (const center of centers) {
                        addBlast(center.x + center.w / 2, center.y + center.h / 2);
                    }

                    // Combo: bricks broken in a row since the last paddle bounce,
                    // multiplier capped at x5 (applied to every brick in the burst)
                    combo++;
                    runStats.maxCombo = Math.max(runStats.maxCombo, combo);
                    const mult = Math.min(combo, COMBO_MAX);
                    const scoreMult = doubleTimer > 0 ? 2 : 1;
                    let totalEarned = 0;
                    let destroyed = 0;
                    let cheatBrickAt = null; // centre of a cheat-code brick caught in this hit, if any
                    for (const [tc, tr] of targets) {
                        const t = bricks[tc][tr];
                        if (!t.alive) continue;
                        if (t.cheat) cheatBrickAt = { x: t.x + t.w / 2, y: t.y + t.h / 2 };
                        t.alive = false;
                        destroyed++;
                        totalEarned += t.points * mult * scoreMult;
                        spawnParticles(t.x + t.w / 2, t.y + t.h / 2, t.color);
                    }
                    // Chain bonus: 2+ TNT bricks going off together
                    const chainBonus = tnt >= 2 ? 50 * tnt * scoreMult : 0;
                    totalEarned += chainBonus;
                    bricksLeft -= destroyed;
                    runStats.bricks += destroyed;
                    addScore(totalEarned);

                    // Floating score popup at the break point
                    const tags = [];
                    if (wasBlast) tags.push('boom');
                    if (mult > 1) tags.push('x' + mult);
                    if (scoreMult > 1) tags.push('2x');
                    const popupText = brick.steel
                        ? 'BROKEN!'
                        : '+' + totalEarned + (tags.length ? ' (' + tags.join(' · ') + ')' : '');
                    const popupX = brick.x + brick.w / 2;
                    const popupY = brick.y + brick.h / 2;
                    addPopup(popupX, popupY, popupText,
                        brick.steel ? '#B0C4DE' : (mult > 1 ? '#FFD700' : '#FFFFFF'));

                    // Combo call-out when the multiplier climbs to x3, x4, x5
                    if (combo >= 3 && combo <= COMBO_MAX) comboShout(combo, popupX, popupY);

                    // TNT chain call-out
                    if (tnt >= 2) {
                        addPopup(Math.max(80, Math.min(popupX, CANVAS_W - 80)), popupY - 44,
                            'CHAIN x' + tnt + '!  +' + chainBonus, '#FF8C1A', { size: 26, life: 1.4, rise: 0.7, pop: true });
                    }

                    // Screen shake: light per brick (heavier deeper in a combo), big for explosions
                    addShake(wasBlast ? Math.min(12 + 2 * (tnt - 1), 16) : brick.steel ? 3 : 1.5 + mult * 0.4);
                    if (wasBlast) haptic(tnt >= 2 ? [40, 30, 60] : 45, true);
                    else haptic(brick.steel ? 15 : 8);

                    // A fire ball pierces straight through: no speed-up, no bounce
                    if (!onFire) {
                        // Slightly speed up, then re-normalize to keep magnitude sane
                        const speed = Math.hypot(b.vx, b.vy);
                        const newSpeed = Math.min(speed * 1.02, 10);
                        const factor = newSpeed / speed;
                        b.vx *= factor;
                        b.vy *= factor;

                        if (Math.abs(dx) > Math.abs(dy)) {
                            // ball entered from the side -> flip vx
                            b.vx *= -1;
                        } else {
                            // ball entered from top/bottom -> flip vy
                            b.vy *= -1;
                        }
                    }

                    if (wasBlast) {
                        boom();
                    } else if (brick.steel) {
                        clink();
                    } else {
                        beep();
                    }
                    
                    // A cheat-code brick guarantees its own capsule instead of the normal powerup roll —
                    // one special, unmistakable drop rather than competing with the ordinary ones
                    if (cheatBrickAt) {
                        if (bricksLeft <= 0) {
                            // This was the level's last brick: the capsule would never get a chance to fall
                            // before completeLevel() clears it, so award the code directly instead
                            revealLevelCode();
                        } else {
                            spawnCheatCapsule(cheatBrickAt.x, cheatBrickAt.y);
                        }
                    } else if (Math.random() < POWERUP_CHANCE) {
                        spawnPowerup(brick.x + brick.w / 2, brick.y + brick.h / 2);
                    }

                    // Check for win condition
                    if (bricksLeft <= 0) {
                        completeLevel();
                        return;
                    }
                }
            }
        }
    }
}


// --- Game Logic Update ---

function update() {
    // 0. Update sliding barrier / moving wall (level 3+)
    for (const wall of movingWalls) {
        wall.x += wall.vx * timeScale;
        if (wall.x <= 0) {
            wall.x = 0;
            wall.vx *= -1;
        } else if (wall.x + wall.w >= CANVAS_W) {
            wall.x = CANVAS_W - wall.w;
            wall.vx *= -1;
        }
    }

    // 1. Move each ball
    for (let i = balls.length - 1; i >= 0; i--) {
        const b = balls[i];

        // Sticky: a caught ball keeps its x (slide the paddle under it to aim), clamped onto the paddle
        if (b.stuck) {
            b.x = Math.max(paddle.x + b.r, Math.min(b.x, paddle.x + paddle.w - b.r));
            b.y = paddle.y - b.r;
            b.trail.length = 0;
            if (++b.stuckFor >= STICKY_MAX_FRAMES) releaseBall(b);
            continue;
        }

        if (b.rallyT <= RALLY_WINDOW_FRAMES) b.rallyT++; // a rally that's timed out just stays timed out

        // Update ball trail (store previous positions)
        if (!b.trail) b.trail = [];
        b.trail.push({ x: b.x, y: b.y });
        if (b.trail.length > 12) {
            b.trail.shift();
        }

        if (guidedTimer > 0) steerGuided(b);
        b.x += b.vx * timeScale; // Time Warp: the world moves faster/slower, your paddle does not
        b.y += b.vy * timeScale;

        // 2. Wall collisions
        if (b.x + b.r > CANVAS_W) {
            b.x = CANVAS_W - b.r;
            b.vx *= -1;
        } else if (b.x - b.r < 0) {
            b.x = b.r;
            b.vx *= -1;
        }
        if (b.y - b.r < 0) {
            // Top wall bounce
            b.y = b.r;
            b.vy *= -1;
        }

        // 2a. Moving wall collision (circle vs AABB)
        let touchingWall = null;
        for (const wall of movingWalls) {
            const cx = Math.max(wall.x, Math.min(b.x, wall.x + wall.w));
            const cy = Math.max(wall.y, Math.min(b.y, wall.y + wall.h));
            const dx = b.x - cx;
            const dy = b.y - cy;
            if (dx * dx + dy * dy < b.r * b.r) {
                // Rebound off the wall and push the ball out of it. Without the push-out, a wall
                // sweeping into the ball (or a slow ball riding it) stays overlapped and re-triggers
                // the sound and particles every frame.
                if (Math.abs(dx) > Math.abs(dy)) {
                    const dir = dx > 0 ? 1 : -1;
                    b.vx = dir * Math.abs(b.vx);
                    b.x = dir > 0 ? wall.x + wall.w + b.r : wall.x - b.r;
                } else {
                    const dir = dy > 0 ? 1 : -1;
                    b.vy = dir * Math.abs(b.vy);
                    b.y = dir > 0 ? wall.y + wall.h + b.r : wall.y - b.r;
                }
                // Effects only on new contact; a wall carrying the ball, or already-touched-this-frame,
                // stays "in contact" (tracks WHICH wall so two walls close together are told apart)
                if (b.onWallRef !== wall) {
                    beep(580, 'wall');
                    spawnParticles(b.x, b.y, '#00ffff', 5);
                    registerRallyTouch(b, wall);
                    wall.hits++;
                    // The first hit just bounces; from the second hit on, a wall can drop a powerup too
                    if (wall.hits > 1 && Math.random() < POWERUP_CHANCE) {
                        spawnPowerup(b.x, b.y);
                    }
                }
                touchingWall = wall;
            }
        }
        b.onWallRef = touchingWall;

        // 2b. Paddle bounce: circle vs AABB test, only while moving down
        if (b.vy > 0) {
            // Solid parts only: a ball over an alien-shot hole falls straight through
            if (paddleOverlap(b.x, b.y, b.r)) {
                // Snap the ball to the top of the paddle
                b.y = paddle.y - b.r;
                // Classic paddle bounce logic (steer)
                [b.vx, b.vy] = launchVelocity(b, paddleVX);
                b.aim = null;
                b.aimIn = 0;
                beep(660, 'paddle');
                combo = 0;
                registerRallyTouch(b, 'paddle');
                if (stickyCatches > 0) {
                    // Sticky paddle: catch the ball instead of bouncing it
                    stickyCatches--;
                    b.stuck = true;
                    b.stuckFor = 0;
                    b.vx = 0;
                    b.vy = 0;
                    addPopup(paddle.x + paddle.w / 2, paddle.y - 34,
                        isTouchDevice() ? 'Tap to release' : 'Click or Space to release',
                        '#c6ff6a', { life: 1.6, size: 14, rise: 0.2 });
                    haptic(10);
                } else if (multiReady) {
                    // Multi-ball split: the "multi" powerup causes this ball to split on the next paddle bounce
                    multiReady = false;
                    if (balls.length < 4) {
                        const mag = Math.hypot(b.vx, b.vy);
                        const f = 0.7 * mag;
                        balls.push(makeBall(b.x, b.y, b.vx + f, b.vy));
                    }
                }
            } else if (b.y + b.r > CANVAS_H && (shield > 0 || (boss && boss.dying > 0))) {
                // Shield: shields compound, so this consumes just one banked miss and any others carry over.
                // (While a boss is blowing up you can't lose a life to it: the edge bounces for free.)
                const free = !!(boss && boss.dying > 0);
                if (!free) shield--;
                b.y = CANVAS_H - b.r;
                b.vy = -Math.abs(b.vy);
                for (let x = 0; x < CANVAS_W; x += 60) spawnParticles(x, CANVAS_H - 2, '#33ddff', 3);
                if (!free) addPopup(b.x, CANVAS_H - 40, shield > 0 ? 'Shield saved you! (' + shield + ' left)' : 'Shield saved you!', '#33ddff', { life: 1.2 });
                addShake(6);
                haptic([20, 40, 20], true);
                tone(300, 0.25, { type: 'sawtooth', vol: 0.2, slideTo: 900 });
            } else if (b.y + b.r > CANVAS_H) {
                // Ball fell past the paddle
                balls.splice(i, 1);
                if (gameState === 'lost') continue; // a second ball falling on the same frame as the last life
                if (balls.length > 0) { // other balls are still in play: just lose this one (a life goes with the LAST ball)
                    addShake(3);
                    haptic(25);
                    continue;
                }
                lives = Math.max(0, lives - 1);
                combo = 0;
                powerups.length = 0;
                clearTimedEffects();
                // Aliens and an active weird event (mirrored view, reversed controls, ...) survive a lost
                // ball: a surprise event is often what causes the ball to be lost in the first place, and
                // cutting it short right then would mean never really getting to react to it
                bossBreather();
                addShake(7);
                haptic(70, true);
                if (lives === 0) {
                    gameState = 'lost';
                    playLoseJingle();
                    haptic(250, true);
                    inputLockUntil = performance.now() + 700;
                    showOverlay('Game over\nTap or press R to play again', 'Play again', buildSummary(false));
                } else if (balls.length === 0) {
                    // All balls lost: reset one ball on the paddle
                    balls.push(makeBall(paddle.x + paddle.w / 2, paddle.y - BALL_RADIUS, currentSpeed(), -currentSpeed()));
                    gameState = 'ready';
                    showOverlay(getLaunchMessage(false), 'Launch');
                }
            }
        }
    }

    // 2c. Active powerup timers (slow affects all balls)
    if (slowTimer > 0) {
        for (const b of balls) {
            const target = currentSpeed() * 0.6;
            const mag = Math.hypot(b.vx, b.vy);
            if (mag > 0) {
                const f = target / mag;
                b.vx *= f;
                b.vy *= f;
            }
        }
        slowTimer -= 1 / 60;
    }
    if (wideTimer > 0) {
        wideTimer -= 1 / 60;
        if (wideTimer <= 0) {
            paddle.w = PADDLE_W;
            paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
        }
    }
    if (narrowTimer > 0) {
        narrowTimer -= 1 / 60;
        if (narrowTimer <= 0) {
            paddle.w = PADDLE_W;
            paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
        }
    }
    if (doubleTimer > 0) {
        doubleTimer -= 1 / 60;
    }
    if (guidedTimer > 0) {
        guidedTimer -= 1 / 60;
    }
    if (fireTimer > 0) {
        fireTimer -= 1 / 60;
        // Flames shed off each moving ball
        for (const b of balls) {
            if (!b.stuck && Math.random() < 0.6) {
                spawnParticles(b.x, b.y, Math.random() < 0.5 ? '#ff9a1f' : '#ffd23f', 1);
            }
        }
    }

    // 2d. Falling powerups
    updatePowerups();

    // 2e. Alien invaders, their bolts, and paddle-hole repair
    updateAliens();

    // 2f. Weird events and the boss
    updateChaos();
    updateBoss();
    updateCrates();
    updateWarpRift();

    // 3. Brick collisions for each ball
    for (const b of balls) {
        if (gameState !== 'playing') break; // a level clear / game over mid-loop ends this frame's collisions
        if (b.stuck) continue;
        collisionDetection(b);
        if (gameState === 'playing') alienBallCollision(b);
        if (gameState === 'playing') bossBallCollision(b);
        if (gameState === 'playing') crateBallCollision(b);
        if (gameState === 'playing') ghostBallCollision(b);
        if (gameState === 'playing') warpRiftBallCollision(b);
    }
    if (gameState === 'playing') updateGhostGrid();
}

// Floating popups: drift upward and fade out; "pop" popups punch in from a larger scale

function render() {
    // Defensive: guarantee an identity transform at the start of every frame, so a canvas-state leak
    // anywhere (a stray translate/scale, an unbalanced save/restore) can never carry over and leave the
    // background — or anything after it — painted off to one side on a later frame.
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    // Backdrop stays put while the playfield shakes
    drawBackground();

    ctx.save();
    if (shake > 0.3) {
        ctx.translate((Math.random() * 2 - 1) * shake, (Math.random() * 2 - 1) * shake);
        shake *= 0.86;
    } else {
        shake = 0;
    }
    drawBricks();
    drawGhostGrid();
    drawCrates();
    drawWarpRift();
    drawMovingWalls();
    drawShield();
    drawBoss();
    drawAliens();
    drawAlienBullets();
    drawBall();
    drawPaddle();
    drawPowerups();
    drawBlasts();
    drawParticles();
    drawPopups();
    ctx.restore();

    drawTimeWarpFx();
    drawStatusChips();
    drawBossBar();
    if (PERF) drawPerf();
    updateHUD();
    updateTouchpad();
}

// --- Rendering Loop (always runs; physics only while playing) ---

function fixedStep() {
    // Track paddle velocity per step (used for the paddle "throw")
    paddleVX = paddle.x - paddlePrevX;
    paddlePrevX = paddle.x;
    // Continuous paddle keyboard control (works before launch too)
    if (gameState === 'ready' || gameState === 'playing') {
        if (followTarget !== null) { // touch follow mode: slide toward the finger at a capped speed
            const d = followTarget - paddle.x;
            paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x + Math.max(-FOLLOW_MAX_STEP, Math.min(FOLLOW_MAX_STEP, d))));
        }
        const dir = mapMirror() ? -1 : 1; // reversed controls / a flipped view swap left and right
        if (keys.left) paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x - 10 * dir));
        if (keys.right) paddle.x = Math.max(0, Math.min(CANVAS_W - paddle.w, paddle.x + 10 * dir));
    }
    // Before launch the ball rides on the paddle
    if (gameState === 'ready') {
        for (const b of balls) {
            b.x = paddle.x + paddle.w / 2;
            b.y = paddle.y - b.r;
            b.trail.length = 0;
        }
    }
    if (gameState === 'playing') {
        update();
    }
}

// Fixed timestep. All game speeds are per-step, so the simulation must advance at exactly 60 steps
// per second no matter what the display does. Running one step per screen refresh made the game run
// at double speed on 120 Hz screens and in slow motion whenever the refresh rate (variable-refresh
// phones) or the frame rate (a busy device) dropped.

function gameLoop(now) {
    requestAnimationFrame(gameLoop);
    now = now || performance.now();
    if (PERF) perfFrame(now);
    if (!lastFrameTime) lastFrameTime = now;
    let dt = Math.min(now - lastFrameTime, 100); // a long gap (tab switch) is not a backlog
    lastFrameTime = now;
    // Frame times jitter around 16.7 ms on a 60 Hz display: snap those to exactly one step
    if (Math.abs(dt - STEP_MS) < 2) dt = STEP_MS;
    stepAccumulator += dt; // (Time Warp scales movement per step instead, so it is smooth and the paddle stays responsive)

    let steps = 0;
    while (stepAccumulator >= STEP_MS && steps < MAX_STEPS_PER_FRAME) {
        fixedStep();
        stepAccumulator -= STEP_MS;
        steps++;
    }
    if (steps === MAX_STEPS_PER_FRAME) stepAccumulator = 0;
    // Render once per 60 Hz tick too: on a 90/120 Hz screen the in-between refreshes are skipped, which
    // keeps the particle/popup/shake animations (advanced in render) at the same speed as the simulation
    if (steps > 0) {
        const t0 = PERF ? performance.now() : 0;
        render();
        if (PERF) perfRender(steps, performance.now() - t0);
    }
}

// --- ?perf readout ---

function perfFrame(now) {
    if (perf.last) {
        perf.intervals.push(now - perf.last);
        if (perf.intervals.length > 120) perf.intervals.shift();
    }
    perf.last = now;
}

function perfRender(steps, ms) {
    perf.renderMs = perf.renderMs ? perf.renderMs * 0.9 + ms * 0.1 : ms;
    perf.worstRender = Math.max(ms, perf.worstRender * 0.99);
    perf.maxSteps = Math.max(steps, perf.maxSteps * 0.995);
    if (steps >= MAX_STEPS_PER_FRAME) perf.dropped++;
}

function drawPerf() {
    const iv = perf.intervals;
    if (!iv.length) return;
    const sorted = [...iv].sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    const worst = sorted[sorted.length - 1];
    const lines = [
        'display ' + Math.round(1000 / median) + ' Hz   worst frame ' + Math.round(worst) + ' ms   render ' + perf.renderMs.toFixed(1) + ' ms (max ' + perf.worstRender.toFixed(1) + ')',
        'catch-up steps ' + perf.maxSteps.toFixed(1) + '   dropped ' + perf.dropped + '   balls ' + balls.length + '  particles ' + particles.length +
            '  popups ' + popups.length + '  aliens ' + aliens.length + '  bolts ' + alienBullets.length + '  voices ' + activeVoices
    ];
    ctx.save();
    ctx.font = '11px monospace';
    ctx.textAlign = 'right';
    ctx.fillStyle = 'rgba(0, 0, 0, 0.6)';
    ctx.fillRect(CANVAS_W - 560, 4, 556, 36);
    ctx.fillStyle = '#9dffb0';
    ctx.fillText(lines[0], CANVAS_W - 10, 19);
    ctx.fillText(lines[1], CANVAS_W - 10, 34);
    ctx.restore();
}

// --- Event Handlers ---
