// === powerups.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

// The powerups this level can drop, weighted for the player's situation (see helpWeight in assist.js)
function unlockedPowerups() {
    const unlocked = unlockLevel();
    return POWERUP_TYPES.filter(p => unlocked >= (POWERUP_UNLOCK[p.type] || 1)).map(p => ({ ...p, weight: helpWeight(p) }));
}

// A falling capsule of one particular powerup (bricks, crates, rocks and row clears all drop the same kind)
function dropPowerup(type, x, y) {
    const t = POWERUP_TYPES.find(p => p.type === type);
    powerups.push({ x: x, y: y, type: t.type, label: t.label, color: t.color, vy: 2.5 });
}

// A random drop: weighted pick among the powerups unlocked by this level
function spawnPowerup(x, y) {
    dropPowerup(weightedPick(unlockedPowerups()).type, x, y);
}


// The first catch of each drop type says what it does: in the tutorial, and for the drops that only turn up
// after it (the player's first chance to meet those). Once per session each.
function explainDrop(def) {
    if (explainedDrops.has(def.type)) return;
    if (!isTutorial() && (POWERUP_UNLOCK[def.type] || 1) <= TUTORIAL[TUTORIAL_LEVELS - 1].unlock) return;
    explainedDrops.add(def.type);
    addPopup(CANVAS_W / 2, 330, def.tip, def.color, { size: 17, life: 2.6, rise: 0.1 });
}

function applyPowerup(type) {
    const def = POWERUP_TYPES.find(p => p.type === type);
    // Stack the name above any still-visible catch popups so back-to-back catches stay readable
    const stacked = popups.filter(p => p.tag === 'powerup').length;
    addPopup(paddle.x + paddle.w / 2, paddle.y - 10 - stacked * 22, def.text, def.color, { life: 1.2, tag: 'powerup' });
    explainDrop(def);

    if (type === 'life') {
        lives = Math.min(lives + 1, MAX_LIVES);
        sfxOneUp();
    } else if (type === 'slow') {
        slowTimer = 6;
    } else if (type === 'wide') {
        narrowTimer = 0; // wide, narrow and split all fight over paddle.w; whichever was just caught wins
        splitTimer = 0;
        wideTimer = 8;
        // W stacks: each W widens the paddle further (1.4x -> 1.7x -> 2.0x, capped)
        const ratio = paddle.w / paddleBaseW();
        const steps = [1.4, 1.7, 2.0];
        const next = steps.find(s => s > ratio);
        if (next) paddle.w = Math.round(paddleBaseW() * next);
        paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
        paddleHoles.length = 0; // the new, wider paddle is welded whole
    } else if (type === 'split') {
        wideTimer = 0;
        narrowTimer = 0;
        splitTimer = SPLIT_SECONDS;
        paddle.w = Math.round(paddleBaseW() * SPLIT_HALF_RATIO);
        paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
        paddleHoles.length = 0;
    } else if (type === 'explosive') {
        // Next brick hit detonates a 3x3 area around that brick
        explosiveReady = true;
    } else if (type === 'multi') {
        // Next paddle bounce splits that ball into two (cap 4 balls)
        multiReady = true;
    } else if (type === 'double') {
        doubleTimer = 10; // catching another refreshes the timer
    } else if (type === 'shield') {
        shield = Math.min(shield + 1, SHIELD_MAX); // shields compound: catching another banks one more
    } else if (type === 'fire') {
        fireTimer = FIRE_SECONDS; // catching another refreshes the timer
    } else if (type === 'sticky') {
        stickyCatches = Math.min(stickyCatches + STICKY_CATCHES, 5);
    } else if (type === 'guided') {
        guidedTimer = GUIDED_SECONDS;
        if (maze) addPopup(CANVAS_W / 2, 470, 'AIM! THE BALL HOMES IN ON A CHOMPER', '#c9a0ff', { size: 16, life: 2, rise: 0.15 });
    }
}


// The cheat-code capsule: dropped only by a cheat-code brick (see collisionDetection in main.js), not part
// of the normal random powerup pool. Falls a little slower than a normal powerup, since missing it means
// losing the code for good — it deserves a fair shot at being caught.
function spawnCheatCapsule(x, y) {
    powerups.push({ x, y, type: 'cheatcode', label: null, color: CHEAT_COLOR, vy: 1.7 });
}

function updatePowerups() {
    for (let i = powerups.length - 1; i >= 0; i--) {
        const p = powerups[i];
        if (p.type === 'poison') {
            // The snake's venom spit weaves side to side as it falls — the curve alone marks it as an
            // attack, not a drop, before the toxic color even registers.
            p.age += timeScale;
            p.x = p.baseX + Math.sin(p.age * SNAKE_SPIT_CURVE_FREQ) * SNAKE_SPIT_CURVE_AMPLITUDE;
        }
        p.y += p.vy * timeScale;
        // Catch test against the solid parts of the paddle (the capsule gets a slightly bigger catch
        // radius than normal powerups — missing it is a real loss, so it isn't pixel-perfect to grab)
        if (paddleOverlap(p.x, p.y, p.type === 'cheatcode' ? 18 : 12)) {
            if (p.type === 'cheatcode') {
                revealLevelCode();
            } else if (p.type === 'poison') {
                applyPoison(p.debuff);
            } else {
                applyPowerup(p.type);
            }
            spawnParticles(p.x, p.y, p.color);
            if (p.type === 'poison') {
                tone(200, 0.3, { type: 'sawtooth', vol: 0.2, slideTo: 70, key: 'poisonCatch', force: true });
            } else if (p.type !== 'cheatcode' && p.type !== 'life') { // those two have their own fanfares
                sfxPowerup();
            }
            haptic(15);
            powerups.splice(i, 1);
            continue;
        }
        if (p.y > CANVAS_H) {
            if (p.type === 'cheatcode') {
                addPopup(p.x, CANVAS_H - 30, 'Code missed!', '#ff8a8a', { life: 1.2 });
                tone(220, 0.3, { type: 'sawtooth', vol: 0.18, slideTo: 80, key: 'codeMiss' });
            }
            powerups.splice(i, 1);
        }
    }
}


function drawPowerups() {
    ctx.save();
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    for (const p of powerups) {
        if (p.type === 'cheatcode') {
            // Bigger, golden, and pulsing — unmistakably not an ordinary powerup
            const pulse = 1 + 0.12 * Math.sin(performance.now() / 130);
            ctx.fillStyle = p.color;
            ctx.globalAlpha = 0.35;
            ctx.beginPath();
            ctx.arc(p.x, p.y, 22 * pulse, 0, Math.PI * 2);
            ctx.fill();
            ctx.globalAlpha = 1;
            ctx.beginPath();
            ctx.arc(p.x, p.y, 15, 0, Math.PI * 2);
            ctx.fill();
            ctx.strokeStyle = '#fff3c4';
            ctx.lineWidth = 1.5;
            ctx.stroke();
            ctx.fillStyle = '#fff3c4';
            ctx.font = pixelFont(12);
            ctx.fillText('?', p.x, p.y);
            continue;
        }
        if (p.type === 'poison') {
            // Toxic and dripping, pulsing faster and uglier than any real powerup's halo — unmistakably
            // not a catch you want.
            const pulse = 1 + 0.18 * Math.sin(performance.now() / 90);
            ctx.fillStyle = SNAKE_POISON_GLOW;
            ctx.globalAlpha = 0.28;
            ctx.beginPath();
            ctx.arc(p.x, p.y, 16 * pulse, 0, Math.PI * 2);
            ctx.fill();
            ctx.globalAlpha = 1;
            ctx.fillStyle = p.color;
            ctx.beginPath();
            ctx.arc(p.x, p.y, 10, 0, Math.PI * 2);
            ctx.fill();
            ctx.strokeStyle = SNAKE_POISON_GLOW;
            ctx.lineWidth = 1.5;
            ctx.stroke();
            ctx.fillStyle = '#1a0a2e';
            ctx.font = 'bold 12px sans-serif';
            ctx.fillText('☠', p.x, p.y);
            continue;
        }
        ctx.fillStyle = p.color;
        ctx.globalAlpha = 0.3; // halo
        ctx.beginPath();
        ctx.arc(p.x, p.y, 14, 0, Math.PI * 2);
        ctx.fill();
        ctx.globalAlpha = 1;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 10, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = '#ffffff';
        if (p.label) {
            const wide = p.label.length > 1;
            ctx.font = wide ? termFont(16) : pixelFont(9); // a two-glyph label like ×2 is too cramped in the pixel font at this size
            ctx.fillText(p.label, p.x, p.y);
        } else {
            // Shield icon
            ctx.beginPath();
            ctx.moveTo(p.x, p.y - 6);
            ctx.lineTo(p.x + 5, p.y - 4);
            ctx.lineTo(p.x + 5, p.y + 1);
            ctx.quadraticCurveTo(p.x + 4, p.y + 5, p.x, p.y + 7);
            ctx.quadraticCurveTo(p.x - 4, p.y + 5, p.x - 5, p.y + 1);
            ctx.lineTo(p.x - 5, p.y - 4);
            ctx.closePath();
            ctx.fill();
        }
    }
    ctx.restore();
}

// --- Collision Detection ---
// --- Alien invaders ---
// Aliens warp in at random times, hover in the open middle of the screen and shoot at the paddle.
// A bolt that hits solid paddle punches a hole the ball falls through; holes repair by themselves.
// The ball can shoot aliens down (a bonus and a guaranteed powerup) and destroys their bolts.
