// === powerups.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function spawnPowerup(x, y) {
    // Weighted pick among the powerups unlocked by this level
    const pool = POWERUP_TYPES.filter(p => level >= (POWERUP_UNLOCK[p.type] || 1));
    let roll = Math.random() * pool.reduce((sum, p) => sum + p.weight, 0);
    let t = pool[pool.length - 1];
    for (const p of pool) {
        roll -= p.weight;
        if (roll < 0) {
            t = p;
            break;
        }
    }
    powerups.push({ x: x, y: y, type: t.type, label: t.label, color: t.color, vy: 2.5 });
}


function applyPowerup(type) {
    const def = POWERUP_TYPES.find(p => p.type === type);
    // Stack the name above any still-visible catch popups so back-to-back catches stay readable
    const stacked = popups.filter(p => p.tag === 'powerup').length;
    addPopup(paddle.x + paddle.w / 2, paddle.y - 10 - stacked * 22, def.text, def.color, { life: 1.2, tag: 'powerup' });

    if (type === 'life') {
        lives = Math.min(lives + 1, 5);
    } else if (type === 'slow') {
        slowTimer = 6;
    } else if (type === 'wide') {
        wideTimer = 8;
        // W stacks: each W widens the paddle further (1.4x -> 1.7x -> 2.0x, capped)
        const ratio = paddle.w / PADDLE_W;
        const steps = [1.4, 1.7, 2.0];
        const next = steps.find(s => s > ratio);
        if (next) paddle.w = Math.round(PADDLE_W * next);
        paddle.x = Math.max(0, Math.min(paddle.x, CANVAS_W - paddle.w));
        paddleHoles.length = 0; // the new, wider paddle is welded whole
    } else if (type === 'explosive') {
        // Next brick hit detonates a 3x3 area around that brick
        explosiveReady = true;
    } else if (type === 'multi') {
        // Next paddle bounce splits that ball into two (cap 4 balls)
        multiReady = true;
    } else if (type === 'double') {
        doubleTimer = 10; // catching another refreshes the timer
    } else if (type === 'shield') {
        shield = Math.min(shield + 1, SHIELD_MAX); // shields compound: catching another banks one more
    } else if (type === 'fire') {
        fireTimer = FIRE_SECONDS; // catching another refreshes the timer
    } else if (type === 'sticky') {
        stickyCatches = Math.min(stickyCatches + STICKY_CATCHES, 5);
    } else if (type === 'guided') {
        guidedTimer = GUIDED_SECONDS;
    }
}


function updatePowerups() {
    for (let i = powerups.length - 1; i >= 0; i--) {
        const p = powerups[i];
        p.y += p.vy * timeScale;
        // Catch test against the solid parts of the paddle
        if (paddleOverlap(p.x, p.y, 12)) {
            applyPowerup(p.type);
            spawnParticles(p.x, p.y, p.color);
            beep();
            haptic(15);
            powerups.splice(i, 1);
            continue;
        }
        if (p.y > CANVAS_H) {
            powerups.splice(i, 1);
        }
    }
}


function drawPowerups() {
    ctx.save();
    ctx.textAlign = 'center';
    for (const p of powerups) {
        ctx.fillStyle = p.color;
        ctx.globalAlpha = 0.3; // halo
        ctx.beginPath();
        ctx.arc(p.x, p.y, 14, 0, Math.PI * 2);
        ctx.fill();
        ctx.globalAlpha = 1;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 10, 0, Math.PI * 2);
        ctx.fill();
        ctx.fillStyle = '#ffffff';
        if (p.label) {
            const wide = p.label.length > 1;
            ctx.font = wide ? 'bold 11px sans-serif' : 'bold 14px sans-serif';
            ctx.fillText(p.label, p.x, p.y + (wide ? 4 : 5));
        } else {
            // Shield icon
            ctx.beginPath();
            ctx.moveTo(p.x, p.y - 6);
            ctx.lineTo(p.x + 5, p.y - 4);
            ctx.lineTo(p.x + 5, p.y + 1);
            ctx.quadraticCurveTo(p.x + 4, p.y + 5, p.x, p.y + 7);
            ctx.quadraticCurveTo(p.x - 4, p.y + 5, p.x - 5, p.y + 1);
            ctx.lineTo(p.x - 5, p.y - 4);
            ctx.closePath();
            ctx.fill();
        }
    }
    ctx.restore();
}

// --- Collision Detection ---
// --- Alien invaders ---
// Aliens warp in at random times, hover in the open middle of the screen and shoot at the paddle.
// A bolt that hits solid paddle punches a hole the ball falls through; holes repair by themselves.
// The ball can shoot aliens down (a bonus and a guaranteed powerup) and destroys their bolts.
