// === rally.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function registerRallyTouch(b, surface) {
    const continuing = b.rallyLast !== null && b.rallyLast !== surface && b.rallyT <= RALLY_WINDOW_FRAMES;
    if (continuing) {
        b.rallyStreak++;
        b.rallyDistinct.add(surface);
    } else {
        b.rallyStreak = 1;
        b.rallyDistinct = new Set([surface]);
        b.rallyAllShown = false;
    }
    b.rallyLast = surface;
    b.rallyT = 0;
    if (b.rallyStreak < RALLY_THRESHOLD) return;

    const surfaceCount = (splitTimer > 0 ? 2 : 1) + movingWalls.length; // the paddle (or both Split halves) plus every wall currently in play
    const allSurfaces = surfaceCount > 1 && b.rallyDistinct.size >= surfaceCount;
    const scoreMult = doubleTimer > 0 ? 2 : 1;
    const shoutStreak = Math.min(b.rallyStreak, RALLY_MAX_SHOUT);
    const bonus = 30 * shoutStreak * scoreMult;

    if (allSurfaces && !b.rallyAllShown) {
        // First time this particular rally has touched every surface in play: the big version
        b.rallyAllShown = true;
        const allBonus = 250 * scoreMult;
        addScore(bonus + allBonus);
        addPopup(b.x, b.y - 24, 'ALL SURFACES! PING PONG!! +' + (bonus + allBonus), '#ffd23f',
            { size: 26, life: 1.6, rise: 0.6, pop: true });
        addShake(11);
        haptic([25, 25, 25, 25, 70], true);
        tone(700, 0.12, { type: 'triangle', vol: 0.25, key: 'pingpong', force: true });
        tone(1050, 0.16, { type: 'triangle', vol: 0.25, delay: 0.1, force: true });
    } else {
        addScore(bonus);
        const word = b.rallyStreak === RALLY_THRESHOLD ? 'PING PONG!' : (b.rallyStreak % 2 === 0 ? 'PONG!' : 'PING!');
        addPopup(b.x, b.y - 20, word + ' +' + bonus, '#7be8ff',
            { size: 16 + Math.min(shoutStreak - RALLY_THRESHOLD, 4) * 2, life: 1.1, rise: 0.5, pop: true });
        addShake(3 + shoutStreak * 0.6);
        haptic([14, 14, 18], true);
        tone(b.rallyStreak % 2 === 0 ? 520 : 700, 0.09, { type: 'triangle', vol: 0.2, key: 'pingpong' });
    }
}

// --- Guided ball: aim for maximum damage ---
// How much a shot is worth if its first hit is brick (c, r): the points it (and anything it sets off)
// would clear. Mirrors the game's real damage rules: TNT chains, the armed Explosive blast, fire-ball
// pierce lines, and otherwise the brick plus a bonus for the cluster around it (good follow-up bounces).
