// === sprites.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function crackPath(x, y, angle, length, brick, out, branchChance) {
    const pts = [[x, y]];
    const steps = 3 + Math.floor(Math.random() * 3);
    let a = angle;
    for (let s = 0; s < steps; s++) {
        a += (Math.random() - 0.5) * 1.1; // jagged
        const seg = (length / steps) * (0.6 + Math.random() * 0.8);
        const nx = x + Math.cos(a) * seg;
        const ny = y + Math.sin(a) * seg;
        if (nx < 1 || nx > brick.w - 1 || ny < 1 || ny > brick.h - 1) {
            // Ran into the brick's edge: end exactly on it
            pts.push([Math.max(1, Math.min(brick.w - 1, nx)), Math.max(1, Math.min(brick.h - 1, ny))]);
            break;
        }
        x = nx;
        y = ny;
        pts.push([x, y]);
        if (branchChance && Math.random() < branchChance) {
            const side = Math.random() < 0.5 ? -1 : 1;
            out.push(crackPath(x, y, a + side * (0.6 + Math.random() * 0.8), length * 0.35, brick, out, 0));
        }
    }
    return pts;
}


function makeCrack(brick, hitX, hitY) {
    const ox = Math.max(3, Math.min(brick.w - 3, hitX - brick.x));
    const oy = Math.max(3, Math.min(brick.h - 3, hitY - brick.y));
    const lines = [];
    const arms = 3 + Math.floor(Math.random() * 2);
    const base = Math.random() * Math.PI * 2;
    for (let i = 0; i < arms; i++) {
        const angle = base + (i / arms) * Math.PI * 2 + (Math.random() - 0.5) * 0.9;
        lines.push(crackPath(ox, oy, angle, 16 + Math.random() * 30, brick, lines, 0.4));
    }
    return { ox, oy, lines };
}

// Small seeded PRNG (mulberry32) so a given level always generates the same layout, also for ?level=N

function crateSprite(cr) {
    if (!crateSprites[cr.type]) {
        crateSprites[cr.type] = makeSprite(BRICK_W, BRICK_H, g => {
            g.drawImage(brickSprite({ color: '#c9971c', steel: false, tnt: false }), 0, 0); // a gold brick...
            g.strokeStyle = 'rgba(255, 240, 170, 0.8)'; // ...with a crate frame
            g.lineWidth = 1.5;
            g.strokeRect(2, 2, BRICK_W - 4, BRICK_H - 4);
            // The powerup's badge, so you can see what's inside
            const cx = BRICK_W / 2;
            const cy = BRICK_H / 2;
            g.fillStyle = cr.color;
            g.beginPath();
            g.arc(cx, cy, 8, 0, Math.PI * 2);
            g.fill();
            g.strokeStyle = '#ffffff';
            g.lineWidth = 1;
            g.stroke();
            g.fillStyle = '#ffffff';
            if (cr.label) {
                g.font = cr.label.length > 1 ? 'bold 9px sans-serif' : 'bold 11px sans-serif';
                g.textAlign = 'center';
                g.textBaseline = 'middle';
                g.fillText(cr.label, cx, cy + 1);
            } else { // shield icon
                g.beginPath();
                g.moveTo(cx, cy - 5);
                g.lineTo(cx + 4, cy - 3);
                g.lineTo(cx + 4, cy + 1);
                g.quadraticCurveTo(cx + 3, cy + 4, cx, cy + 5.5);
                g.quadraticCurveTo(cx - 3, cy + 4, cx - 4, cy + 1);
                g.lineTo(cx - 4, cy - 3);
                g.closePath();
                g.fill();
            }
        });
    }
    return crateSprites[cr.type];
}


function paintBossSprite(g) {
    // Hull
    let gr = g.createLinearGradient(0, 38, 0, 98);
    gr.addColorStop(0, '#9a9ab8');
    gr.addColorStop(0.5, '#565673');
    gr.addColorStop(1, '#25253a');
    g.fillStyle = gr;
    g.beginPath();
    g.ellipse(120, 68, 108, 30, 0, 0, Math.PI * 2);
    g.fill();
    g.strokeStyle = 'rgba(255, 255, 255, 0.25)';
    g.lineWidth = 2;
    g.beginPath();
    g.ellipse(120, 66, 106, 28, 0, Math.PI * 1.05, Math.PI * 1.95);
    g.stroke();
    g.strokeStyle = 'rgba(0, 0, 0, 0.3)';
    g.lineWidth = 1;
    for (let i = -3; i <= 3; i++) {
        g.beginPath();
        g.moveTo(120 + i * 28, 42);
        g.lineTo(120 + i * 34, 96);
        g.stroke();
    }
    // Glass dome with the pilot inside
    gr = g.createRadialGradient(120, 44, 4, 120, 50, 46);
    gr.addColorStop(0, 'rgba(200, 255, 255, 0.95)');
    gr.addColorStop(1, 'rgba(60, 140, 210, 0.85)');
    g.fillStyle = gr;
    g.beginPath();
    g.ellipse(120, 52, 46, 40, 0, Math.PI, Math.PI * 2);
    g.closePath();
    g.fill();
    g.strokeStyle = 'rgba(255, 255, 255, 0.5)';
    g.lineWidth = 1.5;
    g.beginPath();
    g.ellipse(120, 52, 46, 40, 0, Math.PI, Math.PI * 2);
    g.stroke();
    g.drawImage(alienSprite(0, '#1f6b34'), 96, 28, 48, 36);

    // Weak-point hatch on the belly (sprite centre is the boss origin + (120, 55)): an amber panel marked x3
    gr = g.createLinearGradient(0, 74, 0, 96);
    gr.addColorStop(0, '#ffe58a');
    gr.addColorStop(1, '#e08a00');
    g.fillStyle = gr;
    roundRectOn(g, 88, 74, 64, 22, 6);
    g.fill();
    g.strokeStyle = '#3a2a00';
    g.lineWidth = 2;
    g.stroke();
    g.fillStyle = '#3a2a00';
    g.font = 'bold 15px sans-serif';
    g.textAlign = 'center';
    g.textBaseline = 'middle';
    g.fillText('\u00d73', 120, 86);
}


function roundRectOn(g, x, y, w, h, r) {
    g.beginPath();
    g.moveTo(x + r, y);
    g.arcTo(x + w, y, x + w, y + h, r);
    g.arcTo(x + w, y + h, x, y + h, r);
    g.arcTo(x, y + h, x, y, r);
    g.arcTo(x, y, x + w, y, r);
    g.closePath();
}


function roundRectPath(x, y, w, h, r) {
    r = Math.min(r, w / 2, h / 2);
    ctx.beginPath();
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
    ctx.closePath();
}


function fillPoly(g, points, style) {
    g.beginPath();
    g.moveTo(points[0][0], points[0][1]);
    for (let i = 1; i < points.length; i++) g.lineTo(points[i][0], points[i][1]);
    g.closePath();
    g.fillStyle = style;
    g.fill();
}

// --- Drawing Functions ---
// Dotted preview of where a stuck ball will go when released, plus a ring that drains toward auto-release

function ballSpriteSet(name) {
    if (ballSprites[name]) return ballSprites[name];
    const look = BALL_LOOKS[name];
    const r = BALL_RADIUS;

    // Trail blob: full-alpha radial falloff, drawn scaled with globalAlpha
    const blob = makeSprite(64, 64, g => {
        const gr = g.createRadialGradient(32, 32, 0, 32, 32, 32);
        gr.addColorStop(0, 'rgba(' + look.trailCore + ', 1)');
        gr.addColorStop(1, 'rgba(' + look.trailEdge + ', 0)');
        g.fillStyle = gr;
        g.fillRect(0, 0, 64, 64);
    });

    // Halo behind the ball
    const haloR = r * look.haloR;
    const haloSize = Math.ceil(haloR * 2) + 2;
    const halo = makeSprite(haloSize, haloSize, g => {
        const c = haloSize / 2;
        const gr = g.createRadialGradient(c, c, r * 0.6, c, c, haloR);
        gr.addColorStop(0, 'rgba(' + look.halo + ', ' + look.haloA + ')');
        gr.addColorStop(1, 'rgba(' + look.halo + ', 0)');
        g.fillStyle = gr;
        g.beginPath();
        g.arc(c, c, haloR, 0, Math.PI * 2);
        g.fill();
    });

    // The ball: a sphere with a highlight
    const bodySize = r * 2 + 2;
    const body = makeSprite(bodySize, bodySize, g => {
        const c = bodySize / 2;
        const gr = g.createRadialGradient(c - r * 0.35, c - r * 0.35, 1, c, c, r);
        gr.addColorStop(0, '#ffffff');
        gr.addColorStop(0.35, look.mid);
        gr.addColorStop(1, look.edge);
        g.fillStyle = gr;
        g.beginPath();
        g.arc(c, c, r, 0, Math.PI * 2);
        g.fill();
    });

    ballSprites[name] = { blob, halo, body, haloSize, bodySize };
    return ballSprites[name];
}


function makeSprite(w, h, paint) {
    const sprite = document.createElement('canvas');
    sprite.width = w;
    sprite.height = h;
    paint(sprite.getContext('2d'));
    return sprite;
}


function paintBrick(g, color, steel, tnt) {
    const w = BRICK_W;
    const h = BRICK_H;
    const bev = 3; // bevel thickness
    g.fillStyle = color;
    g.fillRect(0, 0, w, h);
    // Beveled edges: light from the top-left, shadow on the bottom-right
    fillPoly(g, [[0, 0], [w, 0], [w - bev, bev], [bev, bev]], 'rgba(255, 255, 255, 0.38)');
    fillPoly(g, [[0, 0], [bev, bev], [bev, h - bev], [0, h]], 'rgba(255, 255, 255, 0.2)');
    fillPoly(g, [[0, h], [bev, h - bev], [w - bev, h - bev], [w, h]], 'rgba(0, 0, 0, 0.38)');
    fillPoly(g, [[w, 0], [w, h], [w - bev, h - bev], [w - bev, bev]], 'rgba(0, 0, 0, 0.25)');
    // Soft sheen on the upper half of the face
    g.fillStyle = 'rgba(255, 255, 255, 0.08)';
    g.fillRect(bev, bev, w - 2 * bev, (h - 2 * bev) / 2);
    g.strokeStyle = 'rgba(0, 0, 0, 0.45)';
    g.lineWidth = 1;
    g.strokeRect(0.5, 0.5, w - 1, h - 1);

    if (steel) {
        // Steel brick metallic border
        g.strokeStyle = '#B0C4DE';
        g.lineWidth = 1.5;
        g.strokeRect(2, 2, w - 4, h - 4);
    }
    if (tnt) {
        // Hazard stripes and a label so it reads as a bomb
        for (let sx = 4; sx < w - 8; sx += 14) {
            fillPoly(g, [[sx, h - bev], [sx + 6, h - bev], [sx + 10, bev], [sx + 4, bev]], 'rgba(255, 210, 0, 0.28)');
        }
        g.font = 'bold 12px sans-serif';
        g.textAlign = 'center';
        g.textBaseline = 'middle';
        g.fillStyle = '#ffe14d';
        g.fillText('TNT', w / 2, h / 2 + 1);
    }
}


function brickSprite(brick) {
    const key = brick.tnt ? 'tnt' : brick.color + (brick.steel ? '|steel' : '');
    if (!brickSprites[key]) {
        brickSprites[key] = makeSprite(BRICK_W, BRICK_H, g => paintBrick(g, brick.tnt ? TNT_COLOR : brick.color, brick.steel, brick.tnt));
    }
    return brickSprites[key];
}

// A crack: a dented spot where the ball struck, then each fissure as a dark groove with a bright lip

function paintCrack(g, crack) {
    const dent = g.createRadialGradient(crack.ox, crack.oy, 0, crack.ox, crack.oy, 10);
    dent.addColorStop(0, 'rgba(15, 20, 25, 0.6)');
    dent.addColorStop(1, 'rgba(15, 20, 25, 0)');
    g.fillStyle = dent;
    g.fillRect(0, 0, BRICK_W, BRICK_H);

    g.lineJoin = 'round';
    g.lineCap = 'round';
    const passes = [
        { off: 0.9, style: 'rgba(0, 0, 0, 0.7)', width: 2.6 },
        { off: 0, style: 'rgba(255, 255, 255, 0.92)', width: 1.2 }
    ];
    for (const pass of passes) {
        g.strokeStyle = pass.style;
        g.lineWidth = pass.width;
        g.beginPath();
        for (const line of crack.lines) {
            g.moveTo(line[0][0] + pass.off, line[0][1] + pass.off);
            for (let i = 1; i < line.length; i++) {
                g.lineTo(line[i][0] + pass.off, line[i][1] + pass.off);
            }
        }
        g.stroke();
    }
}

// Called once when a steel brick cracks: bake the cracked look into that brick's own sprite

function bakeCrack(brick) {
    brick.sprite = makeSprite(BRICK_W, BRICK_H, g => {
        g.drawImage(brickSprite(brick), 0, 0);
        paintCrack(g, brick.crack);
    });
}


function alienSprite(frame, color) {
    const key = frame + color;
    if (!alienSprites[key]) {
        alienSprites[key] = makeSprite(11 * 3, 8 * 3, g => {
            g.fillStyle = color;
            const sprite = ALIEN_SPRITES[frame];
            for (let r = 0; r < 8; r++) {
                for (let c = 0; c < 11; c++) {
                    if (sprite[r][c] === '1') g.fillRect(c * 3, r * 3, 3, 3);
                }
            }
        });
    }
    return alienSprites[key];
}

