// === sprites.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

// Sprites with text in them (TNT, the "?" brick, crate labels, the boss hatch) are painted once and cached,
// so one painted before the web fonts finished loading would keep the fallback font for good. Once the
// fonts are in, drop those caches and let them repaint on next use. Offline with the fonts never cached,
// the loads fail and the fallback font simply stays.
if (document.fonts && document.fonts.load) {
    Promise.all([document.fonts.load(pixelFont(16)), document.fonts.load(termFont(20))]).then(() => {
        for (const k in brickSprites) delete brickSprites[k];
        for (const k in crateSprites) delete crateSprites[k];
        popupSprites.clear();
        bossSprite = null;
    }, () => {});
}

// --- Steel brick cracks ---
// Pixel art on the same 2px grid as the ball: from where the ball actually struck, two fissures run out
// sideways (the brick is wide and flat), stepping up or down now and then, with short offshoots and a
// spur toward the struck edge, plus a few pixels chipped clean out of that edge. Random per hit; stored
// as grid cells in brick-local coordinates and baked into the brick's sprite once by bakeCrack().
const CRACK_CELL = 2;

function makeCrack(brick, hitX, hitY) {
    const cols = Math.floor(brick.w / CRACK_CELL), rows = Math.floor(brick.h / CRACK_CELL);
    const ox = Math.max(3, Math.min(cols - 4, Math.floor((hitX - brick.x) / CRACK_CELL)));
    const hitRow = Math.floor((hitY - brick.y) / CRACK_CELL);
    const towardTop = hitRow < rows / 2;
    const oy = towardTop ? 3 : rows - 4; // a few cells in from the struck edge, so the fissures cross the face
    const seen = new Set();
    const cells = [];
    const add = (x, y) => {
        const k = x + ',' + y;
        if (!seen.has(k)) { seen.add(k); cells.push([x, y]); }
    };
    // A walk that mostly heads (dx, dy) with a sideways wobble, ending at the edge or after `len` cells
    const walk = (x, y, dx, dy, len, branchChance) => {
        for (let i = 0; i < len; i++) {
            if (dx) { x += dx; if (Math.random() < 0.35) y += Math.random() < 0.5 ? -1 : 1; }
            else { y += dy; if (Math.random() < 0.3) x += Math.random() < 0.5 ? -1 : 1; }
            if (x < 1 || x > cols - 2 || y < 1 || y > rows - 2) return;
            add(x, y);
            if (branchChance && Math.random() < branchChance) {
                walk(x, y, 0, Math.random() < 0.5 ? -1 : 1, 1 + Math.floor(Math.random() * 3), 0);
            }
        }
    };
    add(ox, oy);
    walk(ox, oy, -1, 0, 8 + Math.floor(Math.random() * 7), 0.22);
    walk(ox, oy, 1, 0, 8 + Math.floor(Math.random() * 7), 0.22);
    // A straight spur from the origin to the notch, so the damage reads as spreading out from the impact
    for (let y = oy, step = towardTop ? -1 : 1; y > 0 && y < rows - 1; y += step) add(ox, y);

    // A notch knocked out of the edge the ball struck: 2-4 cells wide, a cell deeper in the middle
    const chips = [];
    const edgeY = towardTop ? 0 : rows - 1;
    const inY = towardTop ? 1 : rows - 2;
    const w = 2 + Math.floor(Math.random() * 3);
    const start = Math.max(1, Math.min(cols - 1 - w, ox - Math.floor(w / 2)));
    for (let x = start; x < start + w; x++) chips.push([x, edgeY]);
    if (w > 2) chips.push([start + Math.floor(w / 2), inY]);
    return { cells, chips, inward: towardTop ? 1 : -1 };
}

function crateSprite(cr) {
    if (!crateSprites[cr.type]) {
        crateSprites[cr.type] = makeSprite(BRICK_W, BRICK_H, g => {
            g.drawImage(brickSprite({ color: '#c9971c', steel: false, tnt: false }), 0, 0); // a gold brick...
            g.strokeStyle = 'rgba(255, 240, 170, 0.8)'; // ...with a crate frame
            g.lineWidth = 1.5;
            g.strokeRect(2, 2, BRICK_W - 4, BRICK_H - 4);
            // The powerup's badge, so you can see what's inside
            const cx = BRICK_W / 2;
            const cy = BRICK_H / 2;
            g.fillStyle = cr.color;
            g.beginPath();
            g.arc(cx, cy, 8, 0, Math.PI * 2);
            g.fill();
            g.strokeStyle = '#ffffff';
            g.lineWidth = 1;
            g.stroke();
            g.fillStyle = '#ffffff';
            if (cr.label) {
                g.font = cr.label.length > 1 ? termFont(13) : pixelFont(8);
                g.textAlign = 'center';
                g.textBaseline = 'middle';
                g.fillText(cr.label, cx, cy + 1);
            } else { // shield icon
                g.beginPath();
                g.moveTo(cx, cy - 5);
                g.lineTo(cx + 4, cy - 3);
                g.lineTo(cx + 4, cy + 1);
                g.quadraticCurveTo(cx + 3, cy + 4, cx, cy + 5.5);
                g.quadraticCurveTo(cx - 3, cy + 4, cx - 4, cy + 1);
                g.lineTo(cx - 4, cy - 3);
                g.closePath();
                g.fill();
            }
        });
    }
    return crateSprites[cr.type];
}


// The mothership boss is a giant space invader: the regular aliens' two-frame crab (ALIEN_SPRITES) at
// BOSS_CELL px per pixel instead of 3, so it plainly belongs with them, with chunky edge shading, glowing red
// eyes and the amber x3 weak-point hatch on its belly (row 5, between the legs, where a ball from below can
// reach it). The boss's origin is the sprite's centre. BOSS_RUNS is its solid outline (both frames, so the
// hitbox doesn't twitch as the legs march): bossRects in boss.js turns it into rectangles.
const BOSS_CELL = 16;
const BOSS_W = 11 * BOSS_CELL;
const BOSS_H = 8 * BOSS_CELL;
const BOSS_COLOR = '#a45cff';
const BOSS_LIGHT = '#d4adff';
const BOSS_DARK = '#6a2fc0';
const BOSS_EYES = [[3, 3], [4, 3], [6, 3], [7, 3]]; // the empty cells in the face (two-cell eyes)
const BOSS_HATCH = { x: -40, y: 16, w: 80, h: 16 }; // relative to the boss's origin: row 5, columns 3-7
const BOSS_RUNS = (() => { // [row, firstCol, lastCol] for each unbroken run of solid cells in either frame
    const runs = [];
    for (let r = 0; r < 8; r++) {
        let start = -1;
        for (let c = 0; c <= 11; c++) {
            const on = c < 11 && (ALIEN_SPRITES[0][r][c] === '1' || ALIEN_SPRITES[1][r][c] === '1');
            if (on && start < 0) start = c;
            if (!on && start >= 0) { runs.push([r, start, c - 1]); start = -1; }
        }
    }
    return runs;
})();

function paintBossSprite(g, frame) {
    const C = BOSS_CELL;
    const rows = ALIEN_SPRITES[frame];
    const on = (c, r) => r >= 0 && r < 8 && c >= 0 && c < 11 && rows[r][c] === '1';
    for (let r = 0; r < 8; r++) {
        for (let c = 0; c < 11; c++) {
            if (!on(c, r)) continue;
            g.fillStyle = BOSS_COLOR;
            g.fillRect(c * C, r * C, C, C);
            // Lit from above: a light lip on top edges, a shadow on bottom edges and the right side
            g.fillStyle = BOSS_LIGHT;
            if (!on(c, r - 1)) g.fillRect(c * C, r * C, C, 4);
            g.fillStyle = BOSS_DARK;
            if (!on(c, r + 1)) g.fillRect(c * C, r * C + C - 4, C, 4);
            if (!on(c + 1, r)) g.fillRect(c * C + C - 4, r * C, 4, C);
        }
    }
    // Eyes: glowing red in the holes of the face
    for (const [c, r] of BOSS_EYES) {
        g.fillStyle = '#5a0010';
        g.fillRect(c * C, r * C, C, C);
        g.fillStyle = '#ff4d6a';
        g.fillRect(c * C + 3, r * C + 3, C - 6, C - 6);
        g.fillStyle = '#ffd0d8';
        g.fillRect(c * C + 3, r * C + 3, 4, 4);
    }
    // The weak point: an amber hatch, bevelled, marked x3
    const hx = BOSS_W / 2 + BOSS_HATCH.x, hy = BOSS_H / 2 + BOSS_HATCH.y;
    g.fillStyle = '#3a2a00';
    g.fillRect(hx, hy, BOSS_HATCH.w, BOSS_HATCH.h);
    g.fillStyle = '#ffc53d';
    g.fillRect(hx + 3, hy + 3, BOSS_HATCH.w - 6, BOSS_HATCH.h - 6);
    g.fillStyle = '#ffe58a';
    g.fillRect(hx + 3, hy + 3, BOSS_HATCH.w - 6, 3);
    g.fillStyle = '#3a2a00';
    g.font = pixelFont(9);
    g.textAlign = 'center';
    g.textBaseline = 'middle';
    g.fillText('\u00d73', BOSS_W / 2, hy + BOSS_HATCH.h / 2 + 1);
}

function roundRectOn(g, x, y, w, h, r) {
    g.beginPath();
    g.moveTo(x + r, y);
    g.arcTo(x + w, y, x + w, y + h, r);
    g.arcTo(x + w, y + h, x, y + h, r);
    g.arcTo(x, y + h, x, y, r);
    g.arcTo(x, y, x + w, y, r);
    g.closePath();
}


function fillPoly(g, points, style) {
    g.beginPath();
    g.moveTo(points[0][0], points[0][1]);
    for (let i = 1; i < points.length; i++) g.lineTo(points[i][0], points[i][1]);
    g.closePath();
    g.fillStyle = style;
    g.fill();
}

// --- Drawing Functions ---
// Dotted preview of where a stuck ball will go when released, plus a ring that drains toward auto-release

function ballSpriteSet(name) {
    if (ballSprites[name]) return ballSprites[name];
    const look = BALL_LOOKS[name];
    const r = BALL_RADIUS;

    // Trail blob: full-alpha radial falloff, drawn scaled with globalAlpha
    const blob = makeSprite(64, 64, g => {
        const gr = g.createRadialGradient(32, 32, 0, 32, 32, 32);
        gr.addColorStop(0, 'rgba(' + look.trailCore + ', 1)');
        gr.addColorStop(1, 'rgba(' + look.trailEdge + ', 0)');
        g.fillStyle = gr;
        g.fillRect(0, 0, 64, 64);
    });

    // Halo behind the ball
    const haloR = r * look.haloR;
    const haloSize = Math.ceil(haloR * 2) + 2;
    const halo = makeSprite(haloSize, haloSize, g => {
        const c = haloSize / 2;
        const gr = g.createRadialGradient(c, c, r * 0.6, c, c, haloR);
        gr.addColorStop(0, 'rgba(' + look.halo + ', ' + look.haloA + ')');
        gr.addColorStop(1, 'rgba(' + look.halo + ', 0)');
        g.fillStyle = gr;
        g.beginPath();
        g.arc(c, c, haloR, 0, Math.PI * 2);
        g.fill();
    });

    // The ball: a pixel-art sphere on a coarse grid (2px cells), shaded in three hard steps from a
    // top-left highlight — the page's retro look rather than a smooth gradient
    const bodySize = r * 2 + 2;
    const body = makeSprite(bodySize, bodySize, g => {
        const cell = 2;
        const n = Math.round((r * 2) / cell);
        for (let i = 0; i < n; i++) {
            for (let j = 0; j < n; j++) {
                const px = (i + 0.5) * cell - r, py = (j + 0.5) * cell - r;
                if (px * px + py * py > r * r) continue;
                const d = Math.hypot(px + r * 0.35, py + r * 0.35) / (r * 1.6);
                g.fillStyle = d < 0.22 ? '#ffffff' : d < 0.62 ? look.mid : look.edge;
                g.fillRect(1 + i * cell, 1 + j * cell, cell, cell);
            }
        }
    });

    ballSprites[name] = { blob, halo, body, haloSize, bodySize };
    return ballSprites[name];
}


function makeSprite(w, h, paint) {
    const sprite = document.createElement('canvas');
    sprite.width = w;
    sprite.height = h;
    paint(sprite.getContext('2d'));
    return sprite;
}


function paintBrick(g, color, steel, tnt, cheat) {
    const w = BRICK_W;
    const h = BRICK_H;
    const bev = 3; // bevel thickness
    g.fillStyle = color;
    g.fillRect(0, 0, w, h);
    // Beveled edges: light from the top-left, shadow on the bottom-right
    fillPoly(g, [[0, 0], [w, 0], [w - bev, bev], [bev, bev]], 'rgba(255, 255, 255, 0.38)');
    fillPoly(g, [[0, 0], [bev, bev], [bev, h - bev], [0, h]], 'rgba(255, 255, 255, 0.2)');
    fillPoly(g, [[0, h], [bev, h - bev], [w - bev, h - bev], [w, h]], 'rgba(0, 0, 0, 0.38)');
    fillPoly(g, [[w, 0], [w, h], [w - bev, h - bev], [w - bev, bev]], 'rgba(0, 0, 0, 0.25)');
    // Soft sheen on the upper half of the face
    g.fillStyle = 'rgba(255, 255, 255, 0.08)';
    g.fillRect(bev, bev, w - 2 * bev, (h - 2 * bev) / 2);
    g.strokeStyle = 'rgba(0, 0, 0, 0.45)';
    g.lineWidth = 1;
    g.strokeRect(0.5, 0.5, w - 1, h - 1);

    if (steel) {
        // Steel brick metallic border
        g.strokeStyle = '#B0C4DE';
        g.lineWidth = 1.5;
        g.strokeRect(2, 2, w - 4, h - 4);
    }
    if (tnt) {
        // Hazard stripes and a label so it reads as a bomb
        for (let sx = 4; sx < w - 8; sx += 14) {
            fillPoly(g, [[sx, h - bev], [sx + 6, h - bev], [sx + 10, bev], [sx + 4, bev]], 'rgba(255, 210, 0, 0.28)');
        }
        g.font = pixelFont(8);
        g.textAlign = 'center';
        g.textBaseline = 'middle';
        g.fillStyle = '#ffe14d';
        g.fillText('TNT', w / 2, h / 2 + 1);
    }
    if (cheat) {
        // A gold border and a "?" — deliberately nothing like TNT's look, so the two are never mixed up
        g.strokeStyle = '#fff3c4';
        g.lineWidth = 1.5;
        g.strokeRect(2, 2, w - 4, h - 4);
        // A few small sparkle marks so it reads as "special" even at a glance
        const sparkle = (sx, sy, size) => {
            g.beginPath();
            g.moveTo(sx, sy - size);
            g.lineTo(sx + size * 0.3, sy - size * 0.3);
            g.lineTo(sx + size, sy);
            g.lineTo(sx + size * 0.3, sy + size * 0.3);
            g.lineTo(sx, sy + size);
            g.lineTo(sx - size * 0.3, sy + size * 0.3);
            g.lineTo(sx - size, sy);
            g.lineTo(sx - size * 0.3, sy - size * 0.3);
            g.closePath();
            g.fill();
        };
        g.fillStyle = 'rgba(255, 243, 196, 0.85)';
        sparkle(9, 5, 3);
        sparkle(w - 9, h - 5, 3);
        g.font = pixelFont(10);
        g.textAlign = 'center';
        g.textBaseline = 'middle';
        g.fillStyle = '#fff3c4';
        g.fillText('?', w / 2, h / 2 + 1);
    }
}


function brickSprite(brick) {
    const key = brick.tnt ? 'tnt' : brick.cheat ? 'cheat' : brick.color + (brick.steel ? '|steel' : '');
    if (!brickSprites[key]) {
        const color = brick.tnt ? TNT_COLOR : brick.cheat ? CHEAT_COLOR : brick.color;
        brickSprites[key] = makeSprite(BRICK_W, BRICK_H, g => paintBrick(g, color, brick.steel, brick.tnt, brick.cheat));
    }
    return brickSprites[key];
}

// A crack: a dented spot where the ball struck, then each fissure as a dark groove with a bright lip

function paintCrack(g, crack) {
    const C = CRACK_CELL;
    // Engraved: a light lip one cell below each fissure pixel, then the dark fissure itself on top
    g.fillStyle = 'rgba(255, 255, 255, 0.4)';
    for (const [x, y] of crack.cells) g.fillRect(x * C, (y + 1) * C, C, C);
    g.fillStyle = '#1b2026';
    for (const [x, y] of crack.cells) g.fillRect(x * C, y * C, C, C);
    // The chipped notch: a thin dark lip on its inner side, then the chipped cells cleared right through the sprite
    g.fillStyle = 'rgba(10, 12, 16, 0.6)';
    for (const [x, y] of crack.chips) g.fillRect(x * C, (y + crack.inward) * C, C, C);
    for (const [x, y] of crack.chips) g.clearRect(x * C, y * C, C, C);
}

// Called once when a steel brick cracks: bake the cracked look into that brick's own sprite

function bakeCrack(brick) {
    brick.sprite = makeSprite(BRICK_W, BRICK_H, g => {
        g.drawImage(brickSprite(brick), 0, 0);
        paintCrack(g, brick.crack);
    });
}


function alienSprite(frame, color) {
    const key = frame + color;
    if (!alienSprites[key]) {
        alienSprites[key] = makeSprite(11 * 3, 8 * 3, g => {
            g.fillStyle = color;
            const sprite = ALIEN_SPRITES[frame];
            for (let r = 0; r < 8; r++) {
                for (let c = 0; c < 11; c++) {
                    if (sprite[r][c] === '1') g.fillRect(c * 3, r * 3, 3, 3);
                }
            }
        });
    }
    return alienSprites[key];
}

