// === state.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

let canvas, ctx;

let balls, paddle, bricks, score = 0, lives = START_LIVES, level = 1;

let gameState = 'ready'; // ready, playing, won, lost

let isMuted = false;

let movingWalls = []; // sliding barriers from level 3+

let bumpers = [];     // pinball bumpers: { x, y, r, lit, hits } — see bumpers.js

let touchDetected = false;

// Run stats and best score (shown on the end screen)

let bestScore = 0;      // persisted high score

let foundCodes = {};    // persisted: { [level]: code } — earned by catching a cheat-code capsule, see ui.js

let bestAtStart = 0;    // best when this run began, to detect beating it

let newBestShown = false;

let runStats = { maxCombo: 0, bricks: 0, aliens: 0, bosses: 0, warps: 0 };

let bricksLeft = 0;

let levelBricksTotal = 0;

let inputLockUntil = 0; // ignore restart/continue input briefly after an end screen appears

let plan = { boss: false, tetris: false, tnt: 0, walls: 0, aliens: null, chaos: null };

let introPending = false;


const ghostLevelCache = {};

let chaos = { type: null, pending: null, warn: 0, left: 0, total: 0, scale: 1 };

let chaosTimer = Infinity;   // frames until the next event's warning

let chaosEventsLeft = 0;     // events still to come on this level

let timeScale = 1;           // game speed multiplier (Time Warp)

let reverseFrames = 0;       // controls reversed by the boss's mind-flip beam (separate from the timed events)

let reverseTotal = 1;


const bannerCache = { text: null, pct: -1, kind: null };
// `low` puts the banner at the bottom: when the view is flipped vertically the paddle is at the top of the screen

let boss = null;

let crates = [];

let crateTimer = 0; // frames until the next replacement crate (0 = none pending); one comes back 10-18s after a break


const crateSprites = {};

let bossSprite = null;


let warpRift = null;    // { x, y, r, pullR, warn, life, t }

const explainedDrops = new Set(); // drop types whose tip has been shown this session
let warpOffer = null;   // { steps, ball } while the warp dialog asks whether to jump
let warpTimer = 0;      // frames until the next one may appear

let portals = null;     // { a, b, warn, life, t }: a linked pair, see portals.js

let portalTimer = 0;    // frames until the next pair may open

// Longer than a boss/ghost level takes to notice help is needed, shorter later on; always some randomness

let ghost = null;        // { rows, cells[c][r] = { state, dy } }; state 0 none, 1 ghost, 2 arming (ball inside), 3 solid

let ghostFlashes = [];   // row-clear flashes: { y, t }

let ghostIntroSeen = false;
let chainIntroSeen = false;
let mazeIntroSeen = false;
const bossIntroSeen = {}; // boss kind -> its tips were shown this session
let introCard = null;       // { title, lines, y, life } while a level intro card is up


let bgGradient = null;

const stars = Array.from({ length: 70 }, () => {
    const z = 0.2 + Math.random() * 0.8; // depth: nearer stars are bigger, brighter and move faster
    return {
        x: Math.random() * CANVAS_W,
        y: Math.random() * CANVAS_H,
        z: z,
        layer: Math.min(STAR_LAYERS - 1, Math.floor(((z - 0.2) / 0.8) * STAR_LAYERS))
    };
});


const ballSprites = {};

const brickSprites = {};

const hudCache = {};

let shownCombo = -1;


let audioCtx = null;

let musicGain = null; // the music bus (see music.js)

let sfxGain = null;   // the sound-effects bus

let activeVoices = 0;

const lastPlayedAt = {};


let lastHapticAt = 0;

let iosHapticEl = null;

let powerups = [];

let slowTimer = 0;
let slowRecover = 0;       // steps left bringing the balls back up to speed after Slow ends (see update)

let wideTimer = 0;

let narrowTimer = 0;       // seconds of shrunk paddle left (the snake's "shrink" venom — see snakeBoss.js)

let splitTimer = 0;        // seconds of Split Paddle left — see mirrorPaddleRect() in aliens.js

let doubleTimer = 0;       // seconds of 2x score left

let fireTimer = 0;         // seconds of fire ball left: pierces every brick, never bounces off them

let guidedTimer = 0;       // seconds of guided ball left: aims for the highest-damage shot

let stickyCatches = 0;     // the next N paddle catches stick to the paddle until released

let blasts = [];           // expanding shockwave rings from explosions (decoration)

let shield = 0;            // banked free misses: a falling ball bounces off the bottom edge instead of costing a life

let explosiveReady = false; // next brick hit detonates a 3x3 area

let multiReady = false;    // next paddle bounce splits the ball (cap 4)

let combo = 0; // bricks destroyed in a row without a paddle bounce

let popups = []; // floating text popups

let particles = []; // brick shrapnel

let shake = 0; // screen shake magnitude in px, decays each frame

// Timed / one-shot effects that end when a ball is lost or a level is cleared (the shield persists)

let aliens = [];

let alienBullets = [];

let alienTimer = 0;       // frames until the next alien may warp in
let aliensThisLevel = 0;  // arrivals so far on this level (the tutorial's second alien is a tougher one)

let invaderMarchIn = 0;   // frames until the invaders' march takes its next step (see updateAliens)

let paddleHoles = [];     // { x: hole centre in paddle-local px, w, life: seconds left }


const alienSprites = {};

let paddleGradient = null;
let paddleCapGradient = null;

let paddleVX = 0;

let paddlePrevX = 0;

let paddleTargetX = 0;     // last input target BEFORE the screen-edge clamp (see setPaddleX in input.js)

let paddleTargetPrevX = 0; // lets a paddle "throw" keep its real swipe speed even while pinned at an edge
// One 60 Hz simulation step

let lastFrameTime = 0;

let stepAccumulator = 0;

const perf = { last: 0, intervals: [], renderMs: 0, worstRender: 0, maxSteps: 0, dropped: 0 };

const keys = {};
// --- Touch controls ---
// Two modes, switched with the button in the HUD and remembered:
//   FOLLOW (default): the paddle follows your finger's horizontal position from ANYWHERE on the screen.
//     Rest your thumb below or beside the game instead of on top of the paddle, and after lifting just
//     touch again anywhere: there is nothing to find. The thumb pad's width (or, with no pad on screen,
//     the window's) maps to the full paddle range — see followPaddleTarget in input.js — and the paddle
//     slides toward the target at a capped speed instead of teleporting.
//   DRAG: relative drag from wherever the finger lands (works from anywhere too).

let touchMode = 'follow';

let followTarget = null;      // paddle.x that follow mode is sliding toward

let stageEl = null;

let touchpadDot = null;

let touchpadPct = -1;


let pointerLockWanted = true; // defaults on for mouse players (see ui.js); the Lock button/L key turns it
                               // off, and the browser may still grant/revoke it independently either way

let pointerLocked = false;     // document.pointerLockElement === canvas, cached on pointerlockchange


let lastTapAt = 0;

let isTap = false;

let tapStartX = 0;

let tapStartY = 0;

let dragPointerId = null; // the touch/pen pointer currently dragging the paddle

let dragOffset = 0;       // paddle.x minus the finger's canvas x at touch-down (drag mode)

let lastDragClientX = null; // where the dragging finger currently is

