// === ui.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function isTouchDevice() {
    return (
        touchDetected ||
        ('ontouchstart' in window) ||
        (navigator.maxTouchPoints > 0) ||
        (window.matchMedia && window.matchMedia('(pointer: coarse)').matches)
    );
}


function getLaunchMessage(levelWon = false) {
    const isTouch = isTouchDevice();
    if (levelWon) {
        const name = plan.boss ? 'Boss fight' : plan.tetris ? 'Ghost rows' : currentLayout().name;
        return 'Level ' + level + ' · ' + name + '\n' + (isTouch ? 'Tap to continue' : 'Press SPACE to continue');
    }
    return 'Ready?\n' + (isTouch ? 'Tap or press SPACE to launch' : 'Press SPACE to launch');
}

// The first line of the message is the headline; any further lines are a smaller hint under it

function setOverlayMessage(text) {
    const msg = document.getElementById('overlay-message');
    if (!msg) return;
    const [title, ...rest] = String(text).split('\n');
    msg.textContent = '';
    const t = document.createElement('span');
    t.className = 'ov-title';
    t.textContent = title;
    msg.appendChild(t);
    if (rest.length) {
        const h = document.createElement('span');
        h.className = 'ov-hint';
        h.textContent = rest.join(' ');
        msg.appendChild(h);
    }
}

// summary (optional): { newBest, rows: [[label, value], ...] } rendered as stat tiles

function showOverlay(message, buttonText = 'Launch', summary = null) {
    suspendLock(); // an overlay means the mouse needs to click something — give the cursor back
    const overlay = document.getElementById('overlay');
    const msg = document.getElementById('overlay-message');
    const btn = document.getElementById('overlay-button');
    setOverlayMessage(message);
    if (btn) {
        btn.textContent = buttonText;
        btn.style.display = 'inline-block';
    }
    renderSummary(summary);
    updateCheatCodeUi();
    if (overlay) overlay.style.display = 'block';
}

// --- Level codes ---
// A code is just the level number: plain enough to read aloud or text to a friend, and getStartingLevel()
// already understands ?level=N, so re-entering one is a normal fresh run starting there. Shown whenever
// the overlay is up outside of Paused (mid-pause isn't really a moment to go share or jump levels).
// --- Cheat codes ---
// Your own current level's code is no longer just handed to you here — that made it trivial. Now the only
// way to get one is to catch a cheat-code capsule dropped by the rare gold "?" brick in a level (see
// spawnCheatCapsule/revealLevelCode). This overlay area just holds the "Enter Cheat Code" toggle, so
// someone can type in a code a friend found, and stays collapsed the rest of the time.
function updateCheatCodeUi() {
    const area = document.getElementById('cheat-code-area');
    if (!area) return;
    const show = gameState !== 'paused';
    area.style.display = show ? 'flex' : 'none'; // the whole area (button + entry row), not just the button
    if (!show) collapseCheatCodeEntry();
}

function collapseCheatCodeEntry() {
    const entry = document.getElementById('level-code-entry');
    const toggleBtn = document.getElementById('cheat-code-toggle');
    if (entry) entry.style.display = 'none';
    if (toggleBtn) toggleBtn.textContent = 'Enter Cheat Code';
}

function toggleCheatCodeEntry() {
    const entry = document.getElementById('level-code-entry');
    const toggleBtn = document.getElementById('cheat-code-toggle');
    if (!entry || !toggleBtn) return;
    const opening = entry.style.display !== 'flex';
    if (opening) {
        entry.style.display = 'flex';
        toggleBtn.textContent = 'Hide';
        const input = document.getElementById('level-code-input');
        if (input) input.focus();
    } else {
        collapseCheatCodeEntry();
    }
}

// Reads the code input, decodes it (see codeToLevel in level.js), and starts a fresh run at that level.
// A code typed in this way (e.g. one a friend shared) is recorded into foundCodes exactly like one you
// caught yourself, so it joins the panel below the canvas and you don't have to retype it to get back.
function startAtLevelCode() {
    const input = document.getElementById('level-code-input');
    if (!input) return;
    const n = codeToLevel(input.value);
    if (n === null) {
        input.classList.remove('shake');
        void input.offsetWidth; // restart the CSS animation even if it's already mid-shake
        input.classList.add('shake');
        input.focus();
        return;
    }
    input.value = '';
    const isNew = !foundCodes[n];
    const code = levelToCode(n); // the canonical code for n, not necessarily what was typed (see codeToLevel)
    if (isNew) {
        foundCodes[n] = code;
        saveFoundCodes();
    }
    resetGame(n);
    if (isNew) renderFoundCodesPanel(code);
}

function saveFoundCodes() {
    try {
        localStorage.setItem('breakout-found-codes', JSON.stringify(foundCodes));
    } catch (e) {
        // Storage unavailable; the code found this run just won't persist
    }
}

// Called when a cheat-code capsule is caught (or, if it was the level's last brick, awarded directly —
// see collisionDetection in main.js). Records the code, makes a fuss about it, and adds it to the panel
// below the canvas, where it stays for good — there's no rush to write it down.
//
// A level you've already cracked can still roll a cheat brick on a later replay (the game restarts from
// level 1 every run, so nothing is permanently excluded just because you found it once) — that capsule
// pays out in score instead of repeating the fanfare for a code you already have.
function revealLevelCode() {
    if (foundCodes[level]) {
        const bonus = 200 * (doubleTimer > 0 ? 2 : 1);
        addScore(bonus);
        addPopup(CANVAS_W / 2, CANVAS_H * 0.4, 'CODE ALREADY KNOWN +' + bonus, '#ffe58a', { size: 22, life: 1.6, rise: 0.3, pop: true });
        beep(720, 'codeKnown');
        return;
    }
    const code = levelToCode(level);
    foundCodes[level] = code;
    saveFoundCodes();
    renderFoundCodesPanel(code);
    addPopup(CANVAS_W / 2, CANVAS_H * 0.4, 'CODE FOUND: ' + code + '!', '#ffe58a', { size: 26, life: 2, rise: 0.3, pop: true });
    addShake(6);
    haptic([20, 20, 20, 20, 60], true);
    tone(660, 0.1, { type: 'triangle', vol: 0.22, key: 'codeFound', force: true });
    tone(990, 0.14, { type: 'triangle', vol: 0.22, delay: 0.09, force: true });
    tone(1320, 0.2, { type: 'triangle', vol: 0.22, delay: 0.18, force: true });
}

// Rebuilds the found-codes strip below the canvas from scratch, sorted by level. Each chip loads that
// level directly when clicked — you already earned it, no need to type it back in. `justFound`, if given,
// gets a brief pop-in highlight so a fresh find is obvious among any others already there.
function renderFoundCodesPanel(justFound) {
    const panel = document.getElementById('found-codes');
    const list = document.getElementById('found-codes-list');
    const empty = document.getElementById('found-codes-empty');
    if (!panel || !list) return;
    const levels = Object.keys(foundCodes).map(Number).sort((a, b) => a - b);
    list.textContent = '';
    if (empty) empty.style.display = levels.length ? 'none' : 'block';
    for (const lvl of levels) {
        const chip = document.createElement('button');
        chip.type = 'button';
        chip.className = 'found-code-chip';
        if (foundCodes[lvl] === justFound && lvl === level) chip.classList.add('just-found');
        chip.title = 'Load level ' + lvl;
        const num = document.createElement('span');
        num.className = 'found-code-lvl';
        num.textContent = 'Lv' + lvl;
        const code = document.createElement('b');
        code.textContent = foundCodes[lvl];
        chip.append(num, code);
        chip.addEventListener('click', () => resetGame(lvl));
        list.appendChild(chip);
    }
}


function renderSummary(summary) {
    const flag = document.getElementById('overlay-flag');
    const list = document.getElementById('overlay-stats');
    if (flag) flag.style.display = summary && summary.newBest ? 'block' : 'none';
    if (!list) return;
    list.textContent = '';
    if (!summary) {
        list.style.display = 'none';
        return;
    }
    for (const [label, value] of summary.rows) {
        const tile = document.createElement('div');
        tile.className = 'stat';
        const v = document.createElement('b');
        v.textContent = value;
        const l = document.createElement('span');
        l.textContent = label;
        tile.append(v, l);
        list.appendChild(tile);
    }
    // Balanced rows instead of an orphan tile: up to 5 in one row, otherwise split evenly (6 -> 3+3, 7 -> 4+3)
    const n = summary.rows.length;
    list.style.gridTemplateColumns = 'repeat(' + (n <= 5 ? n : Math.ceil(n / 2)) + ', 1fr)';
    list.style.display = 'grid';
}


function buildSummary(levelCleared) {
    // Short labels so the tiles stay small on a phone; aliens and bosses only appear once you have some
    const rows = [
        ['Score', score],
        ['Best', bestScore],
        [levelCleared ? 'Cleared' : 'Level', levelCleared ? level - 1 : level],
        ['Combo', runStats.maxCombo],
        ['Bricks', runStats.bricks]
    ];
    if (runStats.aliens > 0) rows.push(['Aliens', runStats.aliens]);
    if (runStats.bosses > 0) rows.push(['Bosses', runStats.bosses]);
    if (runStats.warps > 0) rows.push(['Warps', runStats.warps]);
    return { newBest: score > 0 && score > bestAtStart, rows };
}


function hideOverlay() {
    const overlay = document.getElementById('overlay');
    if (overlay) overlay.style.display = 'none';
}

// Stray input right after an end screen appears shouldn't dismiss it before it can be read

function endScreenLocked() {
    return (gameState === 'won' || gameState === 'lost') && performance.now() < inputLockUntil;
}


function handleOverlayAction() {
    if (endScreenLocked()) return;
    if (gameState === 'lost') {
        resetGame(getStartingLevel());
    } else if (gameState === 'ready' || gameState === 'won') {
        launchGame();
    } else if (gameState === 'paused') {
        togglePause();
    }
}

// --- Fullscreen & Orientation Lock ---

async function lockLandscape() {
    try {
        if (screen.orientation && typeof screen.orientation.lock === 'function') {
            await screen.orientation.lock('landscape');
        } else if (screen.lockOrientation) {
            screen.lockOrientation('landscape');
        } else if (screen.mozLockOrientation) {
            screen.mozLockOrientation('landscape');
        } else if (screen.msLockOrientation) {
            screen.msLockOrientation('landscape');
        }
    } catch (e) {
        // Ignored if browser/device doesn't support programmatic orientation lock without fullscreen/PWA
    }
}


function unlockOrientation() {
    try {
        if (screen.orientation && typeof screen.orientation.unlock === 'function') {
            screen.orientation.unlock();
        } else if (screen.unlockOrientation) {
            screen.unlockOrientation();
        } else if (screen.mozUnlockOrientation) {
            screen.mozUnlockOrientation();
        } else if (screen.msUnlockOrientation) {
            screen.msUnlockOrientation();
        }
    } catch (e) {}
}


async function toggleFullscreen() {
    const doc = document;
    const docEl = doc.documentElement;
    const isFS = !!(doc.fullscreenElement || doc.webkitFullscreenElement);

    try {
        if (!isFS) {
            // Must be called synchronously from the tap/click (user activation), before any await
            const request = docEl.requestFullscreen || docEl.webkitRequestFullscreen;
            if (!request) throw new Error('not supported by this browser');
            if (doc.fullscreenEnabled === false) throw new Error('not allowed on this page (embedded or blocked)');
            await request.call(docEl);
            await lockLandscape();
        } else {
            if (doc.exitFullscreen) {
                await doc.exitFullscreen();
            } else if (doc.webkitExitFullscreen) {
                await doc.webkitExitFullscreen();
            }
            unlockOrientation();
        }
    } catch (err) {
        console.warn('Fullscreen / orientation error:', err);
        // Say why on screen: a refused request is otherwise silent, especially on a phone
        addPopup(CANVAS_W / 2, CANVAS_H * 0.5, 'Fullscreen unavailable: ' + ((err && err.message) || err),
            '#ff9a9a', { life: 2.5, size: 18, rise: 0.3 });
    }
}


function updateFullscreenBtn() {
    const btn = document.getElementById('fullscreen-btn');
    if (!btn) return;
    const isFS = !!(document.fullscreenElement || document.webkitFullscreenElement);
    btn.classList.toggle('active', isFS);
    btn.title = isFS ? 'Exit fullscreen (F)' : 'Fullscreen & Lock Landscape (F)';
}


function launchGame() {
    if (gameState !== 'ready' && gameState !== 'won') return;
    gameState = 'playing';
    const sp = currentSpeed();
    for (const b of balls) {
        b.vx = sp;
        b.vy = -sp;
    }
    hideOverlay();
    showLevelIntro();

    // If currently in fullscreen, ensure landscape orientation lock
    if (document.fullscreenElement || document.webkitFullscreenElement) {
        lockLandscape();
    }
}

// --- Initialization Function ---

function setText(id, text) {
    if (hudCache[id] === text) return;
    hudCache[id] = text;
    const el = document.getElementById(id);
    if (el) el.textContent = text;
}

// Combo meter: x1 -> x5, one pip per chained brick; the multiplier caps at COMBO_MAX

function updateComboMeter() {
    const filled = Math.min(combo, COMBO_MAX);
    if (filled === shownCombo) return;
    const increased = filled > shownCombo;
    shownCombo = filled;
    const meter = document.getElementById('combo');
    if (!meter) return;
    setText('combo-label', '×' + Math.max(1, filled));
    meter.querySelectorAll('#combo-pips i').forEach((pip, i) => pip.classList.toggle('on', i < filled));
    meter.classList.toggle('max', filled === COMBO_MAX);
    if (increased && filled > 1) {
        meter.classList.remove('bump');
        void meter.offsetWidth; // restart the CSS animation
        meter.classList.add('bump');
    }
}


function updateHUD() {
    setText('score', score);
    setText('level', level);
    setText('best', bestScore);
    const heartsEl = document.getElementById('hud-lives');
    if (heartsEl) heartsEl.querySelectorAll('svg').forEach((el, i) => el.classList.toggle('on', i < Math.max(0, lives)));
    updateComboMeter();
}

// Score goes through here so the best score is saved and beating it is announced

function updateTouchUi() {
    const touch = isTouchDevice();
    document.body.classList.toggle('touch', touch);
    const btn = document.getElementById('touch-btn');
    if (btn) {
        btn.style.display = touch ? 'inline-flex' : 'none';
        btn.classList.toggle('active', touchMode !== 'follow');
        btn.title = touchMode === 'follow'
            ? 'Follow mode: paddle follows your finger from anywhere. Tap to switch to relative drag.'
            : 'Drag mode: drag anywhere to nudge the paddle. Tap to switch to follow.';
    }
    const label = document.getElementById('touchpad-label');
    if (label) {
        label.textContent = touchMode === 'follow'
            ? 'Slide your thumb anywhere: the paddle follows'
            : 'Drag anywhere to move the paddle';
    }
    updateLockUi(); // the two buttons are mutually exclusive: only one device type is in play at a time
}

// --- Pointer Lock (mouse only, desktop) ---
// Grabs the OS mouse cursor: the browser reports only relative movement (movementX) instead of an absolute
// position, so the paddle is never limited by screen edges or window size, and moving the mouse fast keeps
// working even past the edge of the monitor. On by default for mouse players (see pointerLockWanted in
// state.js) — without it, an ordinary fast mouse move overshoots the canvas and the paddle just stops
// tracking until the cursor comes back. The Lock button/L key still lets anyone turn it back off; a click
// on the canvas re-requests it (the browser requires a fresh gesture each time), including right after Esc.

function updateLockUi() {
    const btn = document.getElementById('lock-btn');
    if (!btn) return;
    const supported = !!(canvas && canvas.requestPointerLock);
    btn.style.display = supported && !isTouchDevice() ? 'inline-flex' : 'none';
    btn.classList.toggle('active', pointerLocked);
    btn.title = pointerLocked
        ? 'Mouse is locked to the game (Esc to release, or click here) (L)'
        : 'Lock the mouse for unlimited-range relative control (L)';
}


function setTouchMode(mode) {
    touchMode = mode;
    followTarget = null;
    try {
        localStorage.setItem('breakout-touch-mode', mode);
    } catch (e) {
        // Storage unavailable; the choice lasts for this session
    }
    updateTouchUi();
}


function initTouchUi() {
    try {
        if (localStorage.getItem('breakout-touch-mode') === 'drag') touchMode = 'drag';
    } catch (e) {
        // Storage unavailable
    }
    updateTouchUi();
    const btn = document.getElementById('touch-btn');
    if (btn) btn.addEventListener('click', () => setTouchMode(touchMode === 'follow' ? 'drag' : 'follow'));
    // Switching apps or tabs pauses the game rather than dropping the ball
    document.addEventListener('visibilitychange', () => {
        if (document.hidden && gameState === 'playing') togglePause();
    });
}

// The thumb pad's dot shows where your finger maps to on the playfield

function updateTouchpad() {
    if (!document.body.classList.contains('touch')) return;
    if (!touchpadDot) touchpadDot = document.getElementById('touchpad-dot');
    if (!touchpadDot) return;
    let frac = (paddle.x + paddle.w / 2) / CANVAS_W;
    if (mapMirror()) frac = 1 - frac;
    const pct = Math.round(frac * 100);
    if (pct !== touchpadPct) {
        touchpadPct = pct;
        touchpadDot.style.left = pct + '%';
    }
}


function togglePause() {
    const pauseBtn = document.getElementById('pause-btn');
    if (gameState === 'playing') {
        gameState = 'paused';
        if (pauseBtn) { pauseBtn.classList.add('active'); pauseBtn.title = 'Resume (P)'; }
        showOverlay('Paused\nTap or press P to resume', 'Resume');
    } else if (gameState === 'paused') {
        gameState = 'playing';
        if (pauseBtn) { pauseBtn.classList.remove('active'); pauseBtn.title = 'Pause (P)'; }
        hideOverlay();
    }
}

// The keys/powerup legend: reference material, not something that needs its own permanent strip of
// screen — a dialog opened on demand instead (see #legend-dialog in index.html). Opening it mid-play
// pauses the game so the ball doesn't fall through an empty paddle while it's read; legendPausedGame
// tracks that so closing it only resumes play it itself paused, never overriding a manual P pause.
let legendPausedGame = false;

function legendOpen() {
    const dlg = document.getElementById('legend-dialog');
    return !!dlg && dlg.classList.contains('open');
}

function showLegend() {
    if (gameState === 'playing') {
        gameState = 'paused';
        legendPausedGame = true;
    }
    const dlg = document.getElementById('legend-dialog');
    const backdrop = document.getElementById('legend-backdrop');
    if (dlg) dlg.classList.add('open');
    if (backdrop) backdrop.classList.add('open');
}

function hideLegend() {
    const dlg = document.getElementById('legend-dialog');
    const backdrop = document.getElementById('legend-backdrop');
    if (dlg) dlg.classList.remove('open');
    if (backdrop) backdrop.classList.remove('open');
    if (legendPausedGame) {
        legendPausedGame = false;
        if (gameState === 'paused') gameState = 'playing';
    }
}

function toggleLegend() {
    if (legendOpen()) hideLegend(); else showLegend();
}

