// === ui.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function isTouchDevice() {
    return (
        touchDetected ||
        ('ontouchstart' in window) ||
        (navigator.maxTouchPoints > 0) ||
        (window.matchMedia && window.matchMedia('(pointer: coarse)').matches)
    );
}


function getLaunchMessage(levelWon = false) {
    const isTouch = isTouchDevice();
    if (levelWon) {
        const name = plan.boss ? 'Boss fight' : plan.tetris ? 'Ghost rows' : currentLayout().name;
        return 'Level ' + level + ' · ' + name + '\n' + (isTouch ? 'Tap to continue' : 'Press SPACE to continue');
    }
    return 'Ready?\n' + (isTouch ? 'Tap or press SPACE to launch' : 'Press SPACE to launch');
}

// The first line of the message is the headline; any further lines are a smaller hint under it

function setOverlayMessage(text) {
    const msg = document.getElementById('overlay-message');
    if (!msg) return;
    const [title, ...rest] = String(text).split('\n');
    msg.textContent = '';
    const t = document.createElement('span');
    t.className = 'ov-title';
    t.textContent = title;
    msg.appendChild(t);
    if (rest.length) {
        const h = document.createElement('span');
        h.className = 'ov-hint';
        h.textContent = rest.join(' ');
        msg.appendChild(h);
    }
}

// summary (optional): { newBest, rows: [[label, value], ...] } rendered as stat tiles

function showOverlay(message, buttonText = 'Launch', summary = null) {
    const overlay = document.getElementById('overlay');
    const msg = document.getElementById('overlay-message');
    const btn = document.getElementById('overlay-button');
    setOverlayMessage(message);
    if (btn) {
        btn.textContent = buttonText;
        btn.style.display = 'inline-block';
    }
    renderSummary(summary);
    if (overlay) overlay.style.display = 'block';
}


function renderSummary(summary) {
    const flag = document.getElementById('overlay-flag');
    const list = document.getElementById('overlay-stats');
    if (flag) flag.style.display = summary && summary.newBest ? 'block' : 'none';
    if (!list) return;
    list.textContent = '';
    if (!summary) {
        list.style.display = 'none';
        return;
    }
    for (const [label, value] of summary.rows) {
        const tile = document.createElement('div');
        tile.className = 'stat';
        const v = document.createElement('b');
        v.textContent = value;
        const l = document.createElement('span');
        l.textContent = label;
        tile.append(v, l);
        list.appendChild(tile);
    }
    // Balanced rows instead of an orphan tile: up to 5 in one row, otherwise split evenly (6 -> 3+3, 7 -> 4+3)
    const n = summary.rows.length;
    list.style.gridTemplateColumns = 'repeat(' + (n <= 5 ? n : Math.ceil(n / 2)) + ', 1fr)';
    list.style.display = 'grid';
}


function buildSummary(levelCleared) {
    // Short labels so the tiles stay small on a phone; aliens and bosses only appear once you have some
    const rows = [
        ['Score', score],
        ['Best', bestScore],
        [levelCleared ? 'Cleared' : 'Level', levelCleared ? level - 1 : level],
        ['Combo', runStats.maxCombo],
        ['Bricks', runStats.bricks]
    ];
    if (runStats.aliens > 0) rows.push(['Aliens', runStats.aliens]);
    if (runStats.bosses > 0) rows.push(['Bosses', runStats.bosses]);
    if (runStats.warps > 0) rows.push(['Warps', runStats.warps]);
    return { newBest: score > 0 && score > bestAtStart, rows };
}


function hideOverlay() {
    const overlay = document.getElementById('overlay');
    if (overlay) overlay.style.display = 'none';
}

// Stray input right after an end screen appears shouldn't dismiss it before it can be read

function endScreenLocked() {
    return (gameState === 'won' || gameState === 'lost') && performance.now() < inputLockUntil;
}


function handleOverlayAction() {
    if (endScreenLocked()) return;
    if (gameState === 'lost') {
        resetGame(getStartingLevel());
    } else if (gameState === 'ready' || gameState === 'won') {
        launchGame();
    } else if (gameState === 'paused') {
        togglePause();
    }
}

// --- Fullscreen & Orientation Lock ---

async function lockLandscape() {
    try {
        if (screen.orientation && typeof screen.orientation.lock === 'function') {
            await screen.orientation.lock('landscape');
        } else if (screen.lockOrientation) {
            screen.lockOrientation('landscape');
        } else if (screen.mozLockOrientation) {
            screen.mozLockOrientation('landscape');
        } else if (screen.msLockOrientation) {
            screen.msLockOrientation('landscape');
        }
    } catch (e) {
        // Ignored if browser/device doesn't support programmatic orientation lock without fullscreen/PWA
    }
}


function unlockOrientation() {
    try {
        if (screen.orientation && typeof screen.orientation.unlock === 'function') {
            screen.orientation.unlock();
        } else if (screen.unlockOrientation) {
            screen.unlockOrientation();
        } else if (screen.mozUnlockOrientation) {
            screen.mozUnlockOrientation();
        } else if (screen.msUnlockOrientation) {
            screen.msUnlockOrientation();
        }
    } catch (e) {}
}


async function toggleFullscreen() {
    const doc = document;
    const docEl = doc.documentElement;
    const isFS = !!(doc.fullscreenElement || doc.webkitFullscreenElement);

    try {
        if (!isFS) {
            // Must be called synchronously from the tap/click (user activation), before any await
            const request = docEl.requestFullscreen || docEl.webkitRequestFullscreen;
            if (!request) throw new Error('not supported by this browser');
            if (doc.fullscreenEnabled === false) throw new Error('not allowed on this page (embedded or blocked)');
            await request.call(docEl);
            await lockLandscape();
        } else {
            if (doc.exitFullscreen) {
                await doc.exitFullscreen();
            } else if (doc.webkitExitFullscreen) {
                await doc.webkitExitFullscreen();
            }
            unlockOrientation();
        }
    } catch (err) {
        console.warn('Fullscreen / orientation error:', err);
        // Say why on screen: a refused request is otherwise silent, especially on a phone
        addPopup(CANVAS_W / 2, CANVAS_H * 0.5, 'Fullscreen unavailable: ' + ((err && err.message) || err),
            '#ff9a9a', { life: 2.5, size: 18, rise: 0.3 });
    }
}


function updateFullscreenBtn() {
    const btn = document.getElementById('fullscreen-btn');
    if (!btn) return;
    const isFS = !!(document.fullscreenElement || document.webkitFullscreenElement);
    btn.textContent = isFS ? '⛶ Exit' : '⛶ Fullscreen';
}


function launchGame() {
    if (gameState !== 'ready' && gameState !== 'won') return;
    gameState = 'playing';
    const sp = currentSpeed();
    for (const b of balls) {
        b.vx = sp;
        b.vy = -sp;
    }
    hideOverlay();
    showLevelIntro();

    // If currently in fullscreen, ensure landscape orientation lock
    if (document.fullscreenElement || document.webkitFullscreenElement) {
        lockLandscape();
    }
}

// --- Initialization Function ---

function setText(id, text) {
    if (hudCache[id] === text) return;
    hudCache[id] = text;
    const el = document.getElementById(id);
    if (el) el.textContent = text;
}

// Combo meter: x1 -> x5, one pip per chained brick; the multiplier caps at COMBO_MAX

function updateComboMeter() {
    const filled = Math.min(combo, COMBO_MAX);
    if (filled === shownCombo) return;
    const increased = filled > shownCombo;
    shownCombo = filled;
    const meter = document.getElementById('combo');
    if (!meter) return;
    setText('combo-label', '×' + Math.max(1, filled));
    meter.querySelectorAll('#combo-pips i').forEach((pip, i) => pip.classList.toggle('on', i < filled));
    meter.classList.toggle('max', filled === COMBO_MAX);
    if (increased && filled > 1) {
        meter.classList.remove('bump');
        void meter.offsetWidth; // restart the CSS animation
        meter.classList.add('bump');
    }
}


function updateHUD() {
    setText('score', 'Score: ' + score);
    setText('lives', 'Lives: ' + '●'.repeat(Math.max(0, lives)));
    setText('level', 'Level: ' + level);
    setText('best', 'Best: ' + bestScore);
    updateComboMeter();
}

// Score goes through here so the best score is saved and beating it is announced

function updateTouchUi() {
    const touch = isTouchDevice();
    document.body.classList.toggle('touch', touch);
    const btn = document.getElementById('touch-btn');
    if (btn) {
        btn.style.display = touch ? 'inline-block' : 'none';
        btn.textContent = touchMode === 'follow' ? '👆 Follow' : '↔ Drag';
        btn.title = touchMode === 'follow'
            ? 'Paddle follows your finger from anywhere. Tap to switch to relative drag.'
            : 'Drag anywhere to nudge the paddle. Tap to switch to follow.';
    }
    const label = document.getElementById('touchpad-label');
    if (label) {
        label.textContent = touchMode === 'follow'
            ? 'Slide your thumb anywhere: the paddle follows'
            : 'Drag anywhere to move the paddle';
    }
    updateLockUi(); // the two buttons are mutually exclusive: only one device type is in play at a time
}

// --- Pointer Lock (mouse only, desktop) ---
// Grabs the OS mouse cursor: the browser reports only relative movement (movementX) instead of an absolute
// position, so the paddle is never limited by screen edges or window size, and moving the mouse fast keeps
// working even past the edge of the monitor. Opt-in (a friend asked for it) since it hides the cursor and
// takes over the mouse, which not everyone wants.

function updateLockUi() {
    const btn = document.getElementById('lock-btn');
    if (!btn) return;
    const supported = !!(canvas && canvas.requestPointerLock);
    btn.style.display = supported && !isTouchDevice() ? 'inline-block' : 'none';
    btn.textContent = pointerLocked ? '🔒 Locked' : '🔓 Lock';
    btn.classList.toggle('active', pointerLocked);
    btn.title = pointerLocked
        ? 'Mouse is locked to the game (Esc to release, or click here) (L)'
        : 'Lock the mouse for unlimited-range relative control (L)';
}


function setTouchMode(mode) {
    touchMode = mode;
    followTarget = null;
    try {
        localStorage.setItem('breakout-touch-mode', mode);
    } catch (e) {
        // Storage unavailable; the choice lasts for this session
    }
    updateTouchUi();
}


function initTouchUi() {
    try {
        if (localStorage.getItem('breakout-touch-mode') === 'drag') touchMode = 'drag';
    } catch (e) {
        // Storage unavailable
    }
    updateTouchUi();
    const btn = document.getElementById('touch-btn');
    if (btn) btn.addEventListener('click', () => setTouchMode(touchMode === 'follow' ? 'drag' : 'follow'));
    // Switching apps or tabs pauses the game rather than dropping the ball
    document.addEventListener('visibilitychange', () => {
        if (document.hidden && gameState === 'playing') togglePause();
    });
}

// The thumb pad's dot shows where your finger maps to on the playfield

function updateTouchpad() {
    if (!document.body.classList.contains('touch')) return;
    if (!touchpadDot) touchpadDot = document.getElementById('touchpad-dot');
    if (!touchpadDot) return;
    let frac = (paddle.x + paddle.w / 2) / CANVAS_W;
    if (mapMirror()) frac = 1 - frac;
    const pct = Math.round(frac * 100);
    if (pct !== touchpadPct) {
        touchpadPct = pct;
        touchpadDot.style.left = pct + '%';
    }
}


function togglePause() {
    const pauseBtn = document.getElementById('pause-btn');
    if (gameState === 'playing') {
        gameState = 'paused';
        if (pauseBtn) pauseBtn.textContent = '▶ Resume';
        showOverlay('Paused\nTap or press P to resume', 'Resume');
    } else if (gameState === 'paused') {
        gameState = 'playing';
        if (pauseBtn) pauseBtn.textContent = '⏸ Pause';
        hideOverlay();
    }
}

