// === warpRift.js === (generated by the maintainability refactor; part of a classic-script
// split of the former game.js — every file shares one global scope, exactly as before, so nothing
// here needed import/export changes. See index.html for the required load order.)

function warpInterval() {
    const base = Math.max(38, 75 - level * 0.6);
    return Math.round(60 * base * (0.75 + Math.random() * 0.6));
}


function canSpawnWarp() {
    return gameState === 'playing' && !warpRift &&
        !(boss && (boss.intro > 0 || boss.dying > 0)) &&
        !(ghost && ghostCount() <= 6) &&
        !(!ghost && !boss && bricksLeft <= 3);
}


function spawnWarpRift() {
    warpRift = {
        x: 90 + Math.random() * (CANVAS_W - 180),
        y: 300 + Math.random() * 140,
        r: WARP_R,
        pullR: WARP_PULL_R,
        warn: WARP_WARN_FRAMES,
        life: WARP_LIFE_FRAMES,
        t: 0
    };
    addPopup(CANVAS_W / 2, 100, '⚡ WARP RIFT OPENING…', '#7be8ff', { size: 20, life: 1.6, rise: 0.2, pop: true });
    tone(220, 0.4, { type: 'sine', vol: 0.2, slideTo: 600, key: 'warpWarn', force: true });
    haptic([20, 40, 20, 40], true);
}


function triggerWarp() {
    const from = level;
    const steps = 1 + Math.floor(Math.random() * WARP_MAX_STEPS); // 1-5 levels forward, never more
    level += steps;
    gameState = 'ready';
    runStats.warps++;
    powerups.length = 0;
    clearTimedEffects();
    endChaos(false);
    combo = 0;
    addScore(50 * steps);
    warpRift = null;
    spawnLevel();
    const sp = currentSpeed();
    balls = [makeBall(paddle.x + paddle.w / 2, paddle.y - BALL_RADIUS, sp, -sp)];
    inputLockUntil = performance.now() + 700;
    addShake(8);
    haptic([30, 20, 30, 20, 60], true);
    tone(300, 0.12, { type: 'sine', vol: 0.22, key: 'warpJump', force: true });
    tone(900, 0.35, { type: 'sine', vol: 0.22, slideTo: 1800, delay: 0.1, force: true });
    showOverlay('WARP!\nJumped from level ' + from + ' to ' + level, 'Continue');
}


function updateWarpRift() {
    if (warpRift) {
        warpRift.t++;
        if (warpRift.warn > 0) {
            warpRift.warn--;
        } else if (--warpRift.life <= 0) {
            warpRift = null; // closed unused
        }
    } else if (canSpawnWarp() && --warpTimer <= 0) {
        spawnWarpRift();
        warpTimer = warpInterval();
    }
}


function warpRiftBallCollision(b) {
    if (!warpRift || warpRift.warn > 0) return;
    const dx = warpRift.x - b.x;
    const dy = warpRift.y - b.y;
    const dist = Math.hypot(dx, dy);
    if (dist < warpRift.pullR) {
        // Gravity: bend the ball's velocity toward the rift's centre, stronger the closer it gets, then
        // restore its original speed so it curves in rather than speeding up or stalling
        const speed = Math.hypot(b.vx, b.vy);
        const pull = 1 - dist / warpRift.pullR; // 0 at the edge of the field, 1 at the rift's own centre
        const nx = dist > 0.01 ? dx / dist : 0;
        const ny = dist > 0.01 ? dy / dist : 0;
        b.vx += nx * pull * WARP_PULL_MAX;
        b.vy += ny * pull * WARP_PULL_MAX;
        const mag = Math.hypot(b.vx, b.vy);
        if (mag > 0.01) {
            const f = speed / mag;
            b.vx *= f;
            b.vy *= f;
        }
        if (Math.random() < 0.4) spawnParticles(b.x, b.y, '#a78bff', 1);
    }
    if (dist < warpRift.r + b.r) triggerWarp();
}


function drawWarpRift() {
    if (!warpRift) return;
    const r = warpRift;
    ctx.save();
    if (r.warn > 0) {
        // Telegraph: a growing dashed ring
        const k = 1 - r.warn / WARP_WARN_FRAMES;
        ctx.globalAlpha = 0.5 + 0.4 * k;
        ctx.strokeStyle = '#7be8ff';
        ctx.lineWidth = 2;
        ctx.setLineDash([5, 5]);
        ctx.beginPath();
        ctx.arc(r.x, r.y, 4 + r.r * k, 0, Math.PI * 2);
        ctx.stroke();
    } else {
        const spin = r.t / 12;
        const fade = r.life < 90 && Math.floor(r.life / 6) % 2 === 0 ? 0.35 : 1; // blinks just before closing
        ctx.globalAlpha = fade;
        // The pull field itself: a faint vignette out to pullR, so its reach is visible, not just felt
        const field = ctx.createRadialGradient(r.x, r.y, r.r, r.x, r.y, r.pullR);
        field.addColorStop(0, 'rgba(120, 90, 255, 0.16)');
        field.addColorStop(1, 'rgba(120, 90, 255, 0)');
        ctx.fillStyle = field;
        ctx.beginPath();
        ctx.arc(r.x, r.y, r.pullR, 0, Math.PI * 2);
        ctx.fill();
        ctx.translate(r.x, r.y);
        for (let i = 0; i < 3; i++) {
            ctx.rotate(spin * (i % 2 === 0 ? 1 : -1) + i);
            const grad = ctx.createRadialGradient(0, 0, 2, 0, 0, r.r - i * 5);
            grad.addColorStop(0, 'rgba(255, 255, 255, 0.9)');
            grad.addColorStop(0.5, 'rgba(120, 90, 255, 0.55)');
            grad.addColorStop(1, 'rgba(60, 30, 180, 0)');
            ctx.fillStyle = grad;
            ctx.beginPath();
            ctx.ellipse(0, 0, r.r - i * 5, (r.r - i * 5) * 0.4, 0, 0, Math.PI * 2);
            ctx.fill();
        }
    }
    ctx.restore();
}

// --- Ghost rows ("Tetris") levels ---
// The bricks are ghosts: the ball flies straight through them, and each ghost it has passed through turns
// solid once the ball has left it. Solid cells bounce the ball like walls and are never destroyed by it.
// Instead, when every cell of a row is solid the row clears (like a Tetris line) and the rows above fall.
// Clear every row to finish the level. Rows have random gaps so they complete at different times, and a
// ghost the ball can no longer reach (walled in by solid cells) solidifies by itself, so a level can
// always be finished.
